import {Link} from 'react-router-dom';
import {ArrowRight,CalendarDays,MapPin,Music2,Users} from 'lucide-react';
import {SEO,Breadcrumbs,ContentSection,Sources} from '../Portal';
import {cultureCategories,cultureDirectory} from '../../data/culture';

const Cards=({items=[]})=>items.length?<div className="performance-cards">{items.map((x,i)=><article key={x.title||x.name||i}><h3>{x.title||x.name}</h3><p>{x.text||x.note}</p>{x.to&&<Link to={x.to}>और जानें <ArrowRight/></Link>}</article>)}</div>:null;
const Related=({items=[]})=>items.length?<section className="performance-related"><h2>आगे की कड़ियाँ</h2><div>{items.map(x=><Link to={x.to} key={`${x.to}-${x.title}`}><small>{x.type}</small><b>{x.title}</b><ArrowRight/></Link>)}</div></section>:null;

export function PerformanceProfile({profile}){if(!profile)return null;const entries=[['प्रकार',profile.type],['भाषा',profile.language],['क्षेत्र',profile.region],['अवसर',profile.occasion],['कलाकार',profile.performers],['संगीत',profile.music],['गतिशैली',profile.movement],['मुख्य विषय',profile.themes]];return <section className="performance-profile" aria-label="प्रदर्शन परिचय"><h2>प्रदर्शन परिचय</h2><dl>{entries.filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>}
export function SeasonalContext({context}){if(!context)return null;return <ContentSection id="season" title="ऋतु और पारंपरिक कैलेंडर"><div className="seasonal-context"><CalendarDays/><div><b>{context.season} · {context.traditionalCalendar}</b><p>{context.socialContext}</p><p><strong>प्रस्तुति:</strong> {context.performanceSetting}</p>{context.associatedFestivals?.length>0&&<p><strong>संबंधित अवसर:</strong> {context.associatedFestivals.join(' · ')}</p>}</div></div></ContentSection>}
export function OralTraditionContext({context}){if(!context)return null;return <ContentSection id="oral" title="मौखिक परंपरा और बदलता पाठ"><div className="oral-context"><p>{context.text}</p><b>रूप किन बातों से बदल सकता है?</b><ul>{context.variationFactors.map(x=><li key={x}>{x}</li>)}</ul></div></ContentSection>}
export function InstrumentsUsed({items=[]}){if(!items.length)return null;return <ContentSection id="instruments" title="वाद्य-संगत"><Cards items={items}/><p className="research-note">ये दस्तावेजीकृत या प्रचलित संगत के उदाहरण हैं—हर मंडली या प्रस्तुति में सभी वाद्य अनिवार्य नहीं हैं।</p></ContentSection>}

export function PerformanceCollections(){const performances=cultureDirectory.filter(x=>x.performanceType),theatre=performances.filter(x=>x.category==='theatre'),music=performances.filter(x=>x.category==='music');const Row=({title,items})=><section className="culture-performance-row"><span>जीवित प्रदर्शन परंपराएँ</span><h2>{title}</h2><div>{items.map(x=><Link to={`/culture/${x.slug}`} key={x.slug}><small>{x.performanceType} · {x.language}</small><h3>{x.nameHi}</h3><p>{x.summary}</p><b>विस्तार से पढ़ें <ArrowRight/></b></Link>)}</div></section>;return <div className="culture-performance-collections"><Row title="लोकनाट्य और रंगपरंपरा" items={theatre}/><Row title="लोकसंगीत" items={music}/></div>}

export default function PerformanceCultureDetailPage({topic:x}){const related=[...x.relatedCulture,...x.relatedDistricts,...x.relatedHistory,...x.relatedTourism];const schema={'@type':'Article',headline:x.nameHi,alternativeHeadline:x.nameEn,inLanguage:x.languages,about:{'@type':'Thing',name:x.nameEn,alternateName:x.aliases},spatialCoverage:x.regions.join(', ')};return <main className="culture-detail performance-detail"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical} schema={schema}/><Breadcrumbs items={[{label:'संस्कृति',to:'/culture'},{label:x.nameHi}]}/><header className="performance-hero"><div className="culture-kicker"><span>{cultureCategories[x.category]}</span><span>{x.subcategory}</span></div><h1>{x.nameHi}</h1><b>{x.nameEn}</b><p>{x.intro}</p><small><MapPin/> {x.regions.join(' · ')} · {x.languages.join(' · ')}</small></header><nav className="culture-section-nav" aria-label="इस पृष्ठ पर">{[['overview','परिचय'],['performance','प्रदर्शन'],['themes','विषय'],['oral','मौखिकता'],['today','आज का रूप'],['sources','स्रोत']].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="culture-shell"><article><ContentSection id="overview" title="परंपरा को समझें"><p className="culture-lede">{x.summary}</p><blockquote>{x.terminologyNote}</blockquote><div className="performance-context"><Music2/><p><b>प्रदर्शन संदर्भ</b>{x.performanceContext.join(' · ')}</p><Users/><p><b>भाषा और क्षेत्र</b>{x.languages.join(' · ')} — {x.culturalRegion}</p></div></ContentSection><PerformanceProfile profile={x.performanceProfile}/><ContentSection id="performance" title="प्रदर्शन कैसे आकार लेता है"><Cards items={x.characteristics}/></ContentSection><ContentSection id="themes" title="मुख्य विषय"><Cards items={x.themes}/></ContentSection><InstrumentsUsed items={x.instruments}/><SeasonalContext context={x.performanceSeason}/><OralTraditionContext context={x.oralTransmission}/><ContentSection title="समाज और इतिहास">{x.socialContext.map(p=><p key={p}>{p}</p>)}<Cards items={x.notablePeople}/></ContentSection><ContentSection id="today" title="आज का रूप">{x.contemporaryPractice.map(p=><p key={p}>{p}</p>)}</ContentSection><Related items={related}/><div id="sources"><Sources sources={x.sources}/></div></article><aside><small>त्वरित परिचय</small><h2>{x.nameHi}</h2><p>{x.summary}</p><h3>प्रकार</h3><span>{x.subcategory}</span><h3>क्षेत्र</h3><div>{x.regions.map(v=><span key={v}>{v}</span>)}</div><h3>जिले केवल orientation हैं</h3>{x.relatedDistricts.map(v=><Link to={v.to} key={v.to}>{v.title}<ArrowRight/></Link>)}</aside></div></main>}
