import {useId,useState} from 'react';
import '../../politics.css';
import {Link,NavLink,useSearchParams} from 'react-router-dom';
import {ArrowRight,BookOpen,Landmark,ShieldCheck} from 'lucide-react';
import {Breadcrumbs,SEO,PageHero,ContentSection,RelatedContent,Sources} from '../Portal';
import {Card,EmptyState} from '../ui';
import {CurrentDataCard,CurrentDataNotice,CurrentOfficeholder} from '../current/CurrentData';
import {currentDataRegistry,currentRecordById,isCurrent} from '../../data/current';
import {districts} from '../../data/districts';
import {siteConfig} from '../../siteConfig';
import {parties,institutions,elections,governments,chiefMinisters,politicalFigures,politicalHistory,historicalEvents,partyHistory,alliances,constituencies,politicsNavigation,departmentDirectory,serviceTopics} from '../../data/politics';
import {partyBySlug,partyCategories,categoryForParty} from '../../data/politics/parties';
import {constituencyBySlug} from '../../data/politics/constituencies';
import {governmentCoverage} from '../../data/politics/governments';
import {electionTypes} from '../../data/politics/elections';
import {movements} from '../../data/politics/movements';
import {coverageNote,evidenceLabels,matchesQuery} from '../../data/politics/model';
import {sourcesFor} from '../../data/politics/sources';

const unknown='संकलित / सत्यापित नहीं';
const statusLabels={constitutional:'संवैधानिक',statutory:'वैधानिक',administrative:'प्रशासनिक'};
const chamberLabels={assembly:'विधानसभा',lokSabha:'लोकसभा'};
const reservationLabels={unreserved:'अनारक्षित',SC:'अनुसूचित जाति (SC)',ST:'अनुसूचित जनजाति (ST)'};
const alpha=items=>[...items].sort((a,b)=>a.nameHi.localeCompare(b.nameHi,'hi'));
export const dateLabel=value=>value?new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`)):unknown;
export function Evidence({type='fact'}){return <span className={`politics-evidence politics-evidence--${type}`}>{evidenceLabels[type]||evidenceLabels.fact}</span>;}
export function Note({children}){return <aside className="politics-note"><ShieldCheck aria-hidden="true"/><div>{children}</div></aside>;}
export function SourceNotes({ids=[],extra=[]}){
 const records=[...new Map([...sourcesFor(ids),...extra].map(source=>[source.url,source])).values()];
 return <div className="politics-sources"><Sources sources={records}/><details><summary>स्रोत का दायरा और सीमाएँ</summary><ul>{records.map(source=><li key={source.url}><b>{source.publisher||source.title}</b><p>{source.scope||'मूल अभिलेख और संबंधित विस्तृत लेख में संदर्भ देखें।'}</p></li>)}</ul></details></div>;
}
export function PoliticsShell({record,children,governance=false}){
 const isHome=record.route==='/politics';
 const parent=governance?{label:'शासन',to:'/governance'}:{label:'राजनीति और शासन',to:'/politics'};
 const schema={'@type':record.type==='person'?'Person':'WebPage',name:record.nameHi,alternateName:record.nameEn,description:record.summary,url:`${siteConfig.url}${record.route}`,citation:sourcesFor(record.sourceIds).map(source=>source.url)};
 return <div className="politics-page" data-politics-route={record.route}>
  <SEO title={`${record.nameHi} — बिहार राजनीतिक ज्ञान`} description={record.summary} canonicalPath={record.route} schema={schema}/>
  <Breadcrumbs items={isHome?[{label:record.nameHi}]:[parent,{label:record.nameHi}]}/>
  <PageHero eyebrow={record.nameEn} title={record.nameHi} description={record.summary}><Evidence type={record.evidence}/></PageHero>
  <div className="politics-wrap">
   <nav className="politics-nav" aria-label="राजनीतिक ज्ञान के विषय">{[['अवलोकन','/politics'],['सरकार','/politics/government'],['संस्थाएँ','/politics/institutions'],['दल','/politics/parties'],['तुलना','/politics/parties/compare'],['चुनाव','/politics/elections'],['क्षेत्र','/politics/constituencies'],['इतिहास','/politics/history'],['वर्तमान','/politics/current']].map(([name,to])=><NavLink key={to} end to={to}>{name}</NavLink>)}</nav>
   {children}
   <SourceNotes ids={record.sourceIds}/>
   <RelatedContent title="इस विषय के आसपास" items={[{title:'शासन और प्रशासन',to:'/governance'},{title:'नागरिक ज्ञान',to:'/governance/civic-knowledge'},{title:'बिहार के जिले',to:'/districts'},{title:'समाज और प्रतिनिधित्व',to:'/society'},{title:'अर्थव्यवस्था और बजट संदर्भ',to:'/economy'},{title:'डेटा सत्यापन नीति',to:'/about/data-freshness'}]}/>
   <p className="politics-editorial">शैक्षणिक परिचय, कानूनी या मतदान-संबंधी व्यक्तिगत सलाह नहीं। <Link to="/contact">स्रोत सहित सुधार सुझाएँ</Link> · <Link to="/editorial-policy">संपादकीय नीति</Link></p>
  </div>
 </div>;
}
export function Prose({sections=[]}){return <div className="politics-prose">{sections.map(section=><ContentSection key={section.title} title={section.title}>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</ContentSection>)}</div>;}
export function RecordCards({records}){return <div className="politics-grid">{records.map(record=><Card key={record.id} as={Link} to={record.route} interactive className="politics-card"><Evidence type={record.evidence}/><h3>{record.nameHi}</h3><small lang="en">{record.nameEn}</small><p>{record.summary}</p><span className="politics-read">विस्तार से पढ़ें <ArrowRight size={16} aria-hidden="true"/></span></Card>)}</div>;}
export function Landing({record}){return <><Note><b>राजनीतिक जानकारी, चुनावी प्रचार नहीं</b><p>{coverageNote}</p></Note><div className="politics-stats">{[['21','स्रोत-आधारित दल'],['17','संस्थागत परिचय'],['243 + 40','क्षेत्र · 2019 snapshot'],['39','बंद कार्यकाल अभिलेख']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><ContentSection title="अपनी अध्ययन-राह चुनें"><RecordCards records={politicsNavigation.filter(item=>item.slug)}/></ContentSection><Prose sections={record.sections}/><CurrentDataNotice/></>;}

function useDirectory(){
 const [params,setParams]=useSearchParams();
 const get=(key,fallback='')=>params.get(key)||fallback;
 const set=(key,value)=>setParams(previous=>{const next=new URLSearchParams(previous);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');return next;},{replace:key==='q'});
 const clear=()=>setParams({});
 return {params,get,set,clear};
}
function SearchField({state,label='नाम या English नाम से खोजें'}){const id=useId();return <label className="politics-field" htmlFor={id}>{label}<input id={id} type="search" value={state.get('q')} onChange={event=>state.set('q',event.target.value)} placeholder="हिंदी / English"/></label>;}
function Filter({label,name,state,options,all='सभी'}){const id=useId();return <label className="politics-field" htmlFor={id}>{label}<select id={id} value={state.get(name)} onChange={event=>state.set(name,event.target.value)}><option value="">{all}</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
function Clear({state}){return <button type="button" className="politics-button" onClick={state.clear}>फ़िल्टर हटाएँ</button>;}
function Paged({records,state,render=items=><RecordCards records={items}/>}){
 const size=18,pages=Math.max(1,Math.ceil(records.length/size)),requested=Number(state.get('page','1')),page=Number.isFinite(requested)?Math.max(1,Math.min(pages,Math.floor(requested))):1;
 return <><p className="politics-result-count" role="status">{records.length} परिणाम · पृष्ठ {page} / {pages}</p>{records.length?render(records.slice((page-1)*size,page*size)):<EmptyState title="कोई परिणाम नहीं मिला" description="नाम की वर्तनी बदलें या फ़िल्टर हटाएँ।" action={<Clear state={state}/>}/>}{pages>1&&<nav className="politics-pagination" aria-label="निर्देशिका के पृष्ठ"><button type="button" disabled={page===1} onClick={()=>state.set('page',String(page-1))}>पिछला</button><span>{page} / {pages}</span><button type="button" disabled={page===pages} onClick={()=>state.set('page',String(page+1))}>अगला</button></nav>}</>;
}
export function PartiesDirectory(){const state=useDirectory(),records=alpha(parties).filter(item=>matchesQuery(item,state.get('q'))&&(!state.get('category')||categoryForParty(item)===state.get('category')));return <><Note><p>{coverageNote}</p><p>श्रेणियाँ 2022/2023 के स्रोत की हैं, आज की मान्यता नहीं। सूची वर्णानुक्रम में है।</p></Note><Link className="politics-button" to="/politics/parties/compare">दल की तथ्यात्मक तुलना</Link><div className="politics-filters" role="search" aria-label="दल खोज"><SearchField state={state}/><Filter state={state} label="स्रोत की श्रेणी" name="category" options={Object.entries(partyCategories)}/><Clear state={state}/></div><Paged records={records} state={state}/></>;}
export function InstitutionsDirectory(){const state=useDirectory(),records=alpha(institutions).filter(item=>matchesQuery(item,state.get('q'))&&(!state.get('status')||item.status===state.get('status')));return <><div className="politics-filters" role="search" aria-label="संस्था खोज"><SearchField state={state}/><Filter state={state} label="संस्था का आधार" name="status" options={Object.entries(statusLabels)}/><Clear state={state}/></div><Paged records={records} state={state}/></>;}
export function PeopleDirectory(){const state=useDirectory(),records=alpha(politicalFigures).filter(item=>matchesQuery(item,state.get('q')));return <><Note><p>नाम वर्णानुक्रम में हैं। ऐतिहासिक पद का उल्लेख वर्तमान पद या लोकप्रियता का दावा नहीं। पहले से उपलब्ध व्यक्तित्व का मूल लेख ही लिंक किया गया है।</p></Note><div className="politics-filters" role="search" aria-label="व्यक्तित्व खोज"><SearchField state={state}/><Clear state={state}/></div><Paged state={state} records={records}/></>;}
export function Facts({rows}){return <dl className="politics-facts">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??unknown}</dd></div>)}</dl>;}
export function CurrentItem({id,title}){const record=currentRecordById(id);return <CurrentDataCard record={record} title={title||record?.name} showWhenUnavailable>{record&&isCurrent(record)&&<p className="current-value">{record.value?.personName||record.value?.label||unknown}</p>}</CurrentDataCard>;}
function Recognition({party}){const history=party.recognitionHistory;return history?<><Evidence type="historical"/><Facts rows={[[`मान्यता श्रेणी · ${dateLabel(history.asOf)}`,partyCategories[history.category]],['क्षेत्राधिकार',history.jurisdiction],['उस स्रोत का चिह्न',history.symbol||unknown]]}/><SourceNotes ids={history.sourceIds}/></>:<p>{unknown} — वर्तमान मान्यता का अनुमान नहीं लगाया गया।</p>;}
export function PartyProfile({party}){
 const results=elections.filter(election=>election.results?.some(row=>row.party===party.slug));
 const history=partyHistory.filter(event=>event.partyIds.includes(party.slug));
 const allianceRecords=alliances.filter(event=>event.partyIds.includes(party.slug));
 return <><div className="politics-profile-mark"><Landmark aria-hidden="true"/><div><b>{party.abbreviation||party.nameEn}</b><p>टाइपोग्राफिक पहचान — चुनाव चिह्न की प्रतिकृति नहीं</p></div></div><CurrentItem id={party.currentDataRef}/>
  <ContentSection title="परिचय और बिहार का संदर्भ"><p>{party.historicalBackground}</p><Facts rows={[["स्थापना वर्ष · उपलब्ध स्रोत",party.foundedYear],['आधिकारिक वेबसाइट',party.officialWebsite?<a href={party.officialWebsite} target="_blank" rel="noreferrer">दल का आधिकारिक पोर्टल</a>:unknown]]}/></ContentSection>
  <ContentSection title="मान्यता और चिह्न: दिनांकित अभिलेख"><Recognition party={party}/></ContentSection>
  <ContentSection title="दल के घोषित सिद्धांत"><Evidence type="position"/>{party.principles?<><p>{party.principles.text}</p><ul>{party.policyThemes.map(theme=><li key={theme}>{theme}</li>)}</ul><SourceNotes ids={party.principles.sourceIds}/></>:<p>मूल दल-दस्तावेज से सिद्धांत अभी संकलित नहीं हैं। पोर्टल स्वतंत्र रूप से विचारधारा का लेबल नहीं देता।</p>}</ContentSection>
  <ContentSection title="निर्वाचन का ऐतिहासिक रिकॉर्ड">{results.length?results.map(election=><ElectionResult key={election.id} election={election} partySlug={party.slug}/>):<p>इस संस्करण में दल की पूरी भागीदारी / परिणाम श्रृंखला संकलित नहीं है। अनुपलब्ध संख्या को शून्य न समझें।</p>}</ContentSection>
  <ContentSection title="घटनाएँ और गठबंधन">{history.length||allianceRecords.length?<Timeline records={[...history,...allianceRecords]}/>:<p>स्रोत-सत्यापित घटनाओं और गठबंधन का विस्तृत अनुक्रम अभी संकलित नहीं है।</p>}</ContentSection>
  <RelatedContent items={party.relatedPeople.map(slug=>{const person=chiefMinisters.find(item=>item.slug===slug);return {title:person.nameHi,to:person.route};})}/>
  <Link className="politics-button" to={`/politics/parties/compare?parties=${party.slug}`}>तुलना में देखें</Link>
 </>;
}
export function ScrollTable({label,headers,rows}){return <div className="politics-table" role="region" aria-label={label} tabIndex="0"><table><caption>{label} · छोटी स्क्रीन पर तालिका क्षैतिज खिसकाएँ</caption><thead><tr>{headers.map((header,index)=><th scope="col" key={index}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,i)=>i===0?<th scope="row" key={i}>{cell}</th>:<td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>;}
export function PartyComparison(){
 const state=useDirectory(),requested=state.get('parties','bjp,jdu,rjd,inc').split(','),selected=[...new Set(requested)].map(partyBySlug).filter(Boolean).slice(0,4);
 const year=state.get('year','2025'),election=elections.find(item=>String(item.year)===year&&item.electionType==='assembly');
 const toggle=slug=>{const next=selected.some(p=>p.slug===slug)?selected.filter(p=>p.slug!==slug).map(p=>p.slug):[...selected.map(p=>p.slug),slug];state.set('parties',next.join(',')||'none');};
 const rows=[['स्थापना — स्रोत का वर्ष',party=>party.foundedYear??unknown],['दिनांकित मान्यता, वर्तमान नहीं',party=>party.recognitionHistory?`${partyCategories[party.recognitionHistory.category]} · ${party.recognitionHistory.asOf} · ${party.recognitionHistory.jurisdiction}`:unknown],['चिह्न — उसी अभिलेख का',party=>party.recognitionHistory?.symbol||unknown],['आधिकारिक पक्ष, पोर्टल का निष्कर्ष नहीं',party=>party.principles?.text||unknown],['दस्तावेज में नीतिगत विषय',party=>party.policyThemes.join(' · ')||unknown],[`विधानसभा ${year} · जीती सीटें`,party=>election?.results?.find(row=>row.party===party.slug)?.seats??unknown],[`विधानसभा ${year} · गठबंधन संदर्भ`,party=>alliances.filter(item=>String(item.year)===year&&item.partyIds.includes(party.slug)).map(item=>item.nameHi).join(' · ')||unknown],['मूल स्रोत',party=><SourceNotes ids={party.sourceIds}/>]];
 return <><Note><p>2 से 4 दल चुनें। मान्यता की तारीख और चुनाव का वर्ष अलग हैं। कोई अंक, राजनीतिक निष्कर्ष या समग्र विजेता नहीं दिया जाता।</p></Note><fieldset className="politics-compare-picker"><legend>तुलना के लिए दल ({selected.length}/4)</legend>{alpha(parties).map(party=><label key={party.slug}><input type="checkbox" checked={selected.some(item=>item.slug===party.slug)} disabled={selected.length===4&&!selected.some(item=>item.slug===party.slug)} onChange={()=>toggle(party.slug)}/><span>{party.nameHi}<small>{party.abbreviation||party.nameEn}</small></span></label>)}</fieldset><div className="politics-filters"><label className="politics-field">विधानसभा चुनाव का वर्ष<select value={year} onChange={event=>state.set('year',event.target.value)}>{[2025,2020,2015].map(year=><option key={year}>{year}</option>)}</select></label><p>{selected.length} दल चयनित</p></div>{selected.length>=2?<ScrollTable label="दल: तथ्यात्मक तुलना" headers={['तथ्य',...selected.map(party=><Link to={party.route}>{party.nameHi}</Link>)]} rows={rows.map(([label,value])=>[label,...selected.map(value)])}/>:<EmptyState title="कम से कम दो दल चुनें" description="ऊपर दिए विकल्पों से तुलना बनाइए।"/>}</>;
}
export function InstitutionProfile({record}){return <>{record.officeId&&<CurrentOfficeholder officeId={record.officeId}/>} {record.currentDataRef&&<CurrentItem id={record.currentDataRef}/>}<Facts rows={[["आधार",statusLabels[record.status]],['संरचना',record.composition],['नियुक्ति / निर्वाचन',record.selection],['कार्यकाल',record.tenure],['अधिकार-क्षेत्र',record.jurisdiction]]}/><ContentSection title="यह संस्था क्या करती है?"><ul>{record.functions.map(value=><li key={value}>{value}</li>)}</ul></ContentSection>{record.officialUrl&&<a className="politics-button" href={record.officialUrl} target="_blank" rel="noreferrer">संस्था का आधिकारिक स्रोत</a>}<RelatedContent items={record.relatedInstitutions.map(slug=>{const item=institutions.find(item=>item.slug===slug);return {title:item.nameHi,to:item.route};})}/></>;}
export function GovernmentDiagram(){
 const branches=[{id:'executive',name:'कार्यपालिका',note:'मंत्रिपरिषद विधानसभा के प्रति सामूहिक रूप से उत्तरदायी है।',ids:['governor','chief-minister','council-of-ministers']},{id:'legislature',name:'विधानमंडल',note:'विधानमंडल में राज्यपाल और दोनों सदन शामिल हैं; यह मंत्रिपरिषद का विभाग नहीं।',ids:['legislative-assembly','legislative-council','legislature-secretariat']},{id:'judiciary',name:'न्यायपालिका',note:'स्वतंत्र न्यायिक भूमिका; उच्च न्यायालय और अधीनस्थ न्यायालय।',ids:['patna-high-court']},{id:'local',name:'स्थानीय एवं स्वतंत्र संस्थाएँ',note:'चुनाव आयोग, पंचायत और नगर निकायों की भूमिकाएँ अलग कानूनी आधार पर हैं।',ids:['state-election-commission','panchayati-raj-department','urban-development-department']}];
 const [selected,setSelected]=useState('executive'),branch=branches.find(item=>item.id===selected);
 return <section className="politics-structure" aria-label="सरकारी संस्थाओं की अलग शाखाएँ"><h2>भारत का संविधान</h2><p>नीचे की शाखाएँ भूमिकाएँ दिखाती हैं, एक-दूसरे पर प्रशासनिक अधीनता नहीं।</p><div className="politics-branch-buttons">{branches.map(item=><button key={item.id} type="button" aria-pressed={item.id===selected} aria-controls="politics-branch-panel" onClick={()=>setSelected(item.id)}>{item.name}</button>)}</div><div id="politics-branch-panel"><h3>{branch.name}</h3><p>{branch.note}</p><RecordCards records={institutions.filter(item=>branch.ids.includes(item.slug))}/></div></section>;
}
export function ConstituencyDirectory({assemblyOnly=false}){
 const state=useDirectory();
 const records=constituencies.filter(item=>(!assemblyOnly||item.chamber==='assembly')&&matchesQuery(item,state.get('q'))&&(!state.get('district')||item.districtIds.includes(state.get('district')))&&(!state.get('division')||item.divisionNames.includes(state.get('division')))&&(!state.get('chamber')||item.chamber===state.get('chamber'))&&(!state.get('reservation')||item.reservation===state.get('reservation'))&&(!state.get('number')||String(item.number)===state.get('number')));
 return <><Note><p>सीमाएँ परिसीमन के बाद बदल सकती हैं। यह 2019 का मानचित्रण है; वर्तमान सीमा, आरक्षण या सदस्यता की पुष्टि नहीं। आधिकारिक English नाम के साथ हिंदी लिप्यंतरण संपादकीय है।</p></Note><Link to="/politics/electoral-geography" className="politics-button">जिला और निर्वाचन क्षेत्र का अंतर समझें</Link><div className="politics-filters" role="search" aria-label="निर्वाचन क्षेत्र खोज"><SearchField state={state}/><Filter label="जिला" name="district" state={state} options={districts.map(item=>[item.slug,item.nameHindi])}/><Filter label="प्रमंडल" name="division" state={state} options={[...new Set(districts.map(item=>item.division))].map(name=>[name,name])}/>{!assemblyOnly&&<Filter label="सदन" name="chamber" state={state} options={Object.entries(chamberLabels)}/>}<Filter label="अभिलेख का आरक्षण" name="reservation" state={state} options={Object.entries(reservationLabels)}/><label className="politics-field">निर्वाचन क्षेत्र क्रमांक<input type="number" min="1" max="243" value={state.get('number')} onChange={event=>state.set('number',event.target.value)}/></label><Clear state={state}/></div><Paged records={records} state={state} render={items=><div className="politics-grid">{items.map(item=><Card key={item.slug} as={Link} to={item.route} interactive><small>{chamberLabels[item.chamber]} · {item.number} · 2019</small><h3>{item.nameHi}</h3><span lang="en">{item.nameEn}</span><p>{item.districtIds.map(slug=>districts.find(d=>d.slug===slug).nameHindi).join(' · ')}</p><small>{reservationLabels[item.reservation]}</small></Card>)}</div>}/></>;
}
export function ConstituencyProfile({record}){
 const relationships=record.chamber==='assembly'?[constituencyBySlug(record.parliamentaryId)]:record.assemblyIds.map(constituencyBySlug);
 return <><Evidence type="historical"/><Note><p>{record.boundary.note}</p></Note><Facts rows={[["सदन",chamberLabels[record.chamber]],['क्रमांक',record.number],['आरक्षण · स्रोत snapshot',reservationLabels[record.reservation]],['डेटा-वर्ष',record.boundary.dataYear],['सीमा स्थिति',record.boundary.status],['कानूनी प्रभावी आरंभ',record.boundary.effectiveFrom||'इस dataset में संकलित नहीं'],['कानूनी प्रभावी समाप्ति',record.boundary.effectiveTo||'इस dataset में संकलित नहीं']]}/><ContentSection title="प्रशासनिक जिले"><div className="politics-link-list">{record.districtIds.map(slug=><Link key={slug} to={`/district/${slug}`}>{districts.find(d=>d.slug===slug).nameHindi} जिला</Link>)}</div></ContentSection><ContentSection title={record.chamber==='assembly'?'इस विधानसभा खंड का लोकसभा संबंध — 2019':'इस लोकसभा क्षेत्र के विधानसभा खंड — 2019'}><RecordCards records={relationships}/></ContentSection><ContentSection title="वर्तमान प्रतिनिधित्व"><CurrentItem id={record.currentDataRef}/><p>यह dataset सीमा-संबंध देता है। सत्यापित क्षेत्र-विशिष्ट सदस्य roster के बिना कोई वर्तमान नाम नहीं दिखाया जाता।</p></ContentSection><ContentSection title="चुनाव इतिहास और नाम परिवर्तन"><p>इस क्षेत्र की वर्षवार उम्मीदवार-परिणाम श्रृंखला और पुराने नाम-परिवर्तन अभी अलग रिकॉर्ड में संकलित नहीं हैं।</p><Link to="/politics/elections/history">चुनाव के आधिकारिक अभिलेख</Link></ContentSection></>;
}
export function ElectoralGeography(){const [selected,setSelected]=useState('patna'),district=districts.find(item=>item.slug===selected),areas=constituencies.filter(item=>item.chamber==='lokSabha'&&item.districtIds.includes(selected));return <ContentSection title="जिला चुनकर दोनों संबंध देखें"><label className="politics-field">प्रशासनिक जिला<select value={selected} onChange={event=>setSelected(event.target.value)}>{districts.map(item=><option key={item.slug} value={item.slug}>{item.nameHindi}</option>)}</select></label><div className="politics-geography"><Card><h3>प्रशासनिक संबंध</h3><p>बिहार → {district.division} प्रमंडल → {district.nameHindi} जिला</p><Link to={`/district/${selected}`}>जिले का मूल विवरण</Link></Card><Card><h3>निर्वाचन संबंध · 2019</h3><p>इस जिले के विधानसभा खंड इन लोकसभा क्षेत्रों से जुड़े हैं। कोई क्षेत्र दूसरे जिले में भी फैल सकता है।</p>{areas.map(item=><p key={item.id}><Link to={item.route}>{item.nameHi} लोकसभा</Link> · {item.districtIds.length} प्रशासनिक जिले</p>)}</Card></div><Link to={`/politics/constituencies?district=${selected}`}>इस जिले से जुड़े सभी निर्वाचन क्षेत्र देखें</Link></ContentSection>;}

export function ElectionResult({election,partySlug}){
 const rows=(election.results||[]).filter(row=>!partySlug||row.party===partySlug).sort((a,b)=>partyBySlug(a.party).nameHi.localeCompare(partyBySlug(b.party).nameHi,'hi'));
 return <div><h3>{election.nameHi}</h3><p>{election.coverage}</p>{rows.length?<ScrollTable label={`विधानसभा ${election.year} — घोषित जीती सीटें, वर्तमान सदस्यता नहीं`} headers={['दल','चुनाव वर्ष','सीटें','मत-प्रतिशत','स्रोत']} rows={rows.map(row=>[<Link to={partyBySlug(row.party).route}>{partyBySlug(row.party).nameHi}</Link>,row.year,row.seats,row.voteShare??unknown,<SourceNotes ids={row.sourceIds}/>])}/>:<p>पूर्ण दलवार परिणाम, मत-प्रतिशत और मतदान प्रतिशत इस संस्करण में संकलित नहीं।</p>}<SourceNotes ids={election.sourceIds}/></div>;
}
export function ElectionHistory(){const state=useDirectory(),records=[...elections].sort((a,b)=>b.year-a.year).filter(item=>matchesQuery(item,state.get('q'))&&(!state.get('type')||item.electionType===state.get('type'))&&(!state.get('year')||String(item.year)===state.get('year')));return <><Note><p>9 अभिलेख प्रविष्टियाँ हैं; इनमें केवल 2025 विधानसभा की पूरी दलवार जीती-सीट सारणी संकलित है। अन्य प्रविष्टियाँ स्रोत-मार्गदर्शक हैं, पूर्ण परिणाम नहीं।</p></Note><div className="politics-filters" role="search" aria-label="चुनाव इतिहास खोज"><SearchField state={state}/><Filter state={state} label="चुनाव प्रकार" name="type" options={Object.entries(electionTypes)}/><Filter state={state} label="वर्ष" name="year" options={[...new Set(elections.map(item=>item.year))].sort((a,b)=>b-a).map(year=>[String(year),String(year)])}/><Clear state={state}/></div><p role="status">{records.length} अभिलेख</p>{records.length?records.map(item=><ContentSection key={item.id} id={item.slug} title={`${item.year} · ${electionTypes[item.electionType]}`}><Evidence type="historical"/><p>{item.summary}</p><ElectionResult election={item}/></ContentSection>):<EmptyState action={<Clear state={state}/>}/>}</>;}
export function Timeline({records}){return <ol className="politics-timeline">{[...records].sort((a,b)=>(a.date||String(a.year)).localeCompare(b.date||String(b.year))).map(item=><li key={item.id} id={item.slug}><Evidence type={item.evidence}/><span className="politics-period">{item.date?dateLabel(item.date):item.period||item.year}</span><h3>{item.nameHi}</h3><p>{item.summary}</p>{item.partyIds&&<div className="politics-link-list">{item.partyIds.map(slug=><Link key={slug} to={partyBySlug(slug).route}>{partyBySlug(slug).nameHi}</Link>)}</div>}{item.partyListComplete===false&&<small>उल्लिखित दल; संपूर्ण गठबंधन-सूची नहीं।</small>}<SourceNotes ids={item.sourceIds}/></li>)}</ol>;}
export function HistoryOverview(){return <><Note><p>इतिहास के विस्तृत लेख अपने मूल मॉड्यूल में हैं। 2010 और 2020 के दशकों की हर गठबंधन/नीति घटना इस संक्षिप्त संग्रह में नहीं है। बाद की व्याख्या को मूल घटना या चुनाव परिणाम से अलग पढ़ें।</p></Note><RecordCards records={politicalHistory}/><ContentSection title="दिनांकित संस्थागत घटनाएँ"><Timeline records={historicalEvents}/></ContentSection><RelatedContent items={[{title:'मुख्यमंत्री कार्यकाल',to:'/politics/chief-ministers'},{title:'दल प्रणाली में बदलाव',to:'/politics/party-history'},{title:'गठबंधन संदर्भ',to:'/politics/alliances'}]}/></>;}
export function Movements(){return <><Note><p>मूल लेखों में स्थान, पृष्ठभूमि, घटनाएँ, परिणाम और स्रोत पढ़ें। भूमि सुधार एक कानूनी परिवर्तन भी है; उसे एक अकेला आंदोलन मानकर न पढ़ें।</p></Note><RecordCards records={movements}/></>;}
export function Governments({person}){
 const state=useDirectory(),records=governments.filter(item=>(!person||item.personId===person.slug)&&matchesQuery(item,state.get('q'))&&(!state.get('decade')||item.start.slice(0,3)===state.get('decade')));
 return <><Note><p>{governmentCoverage}</p><p>दस्तावेज में समान दिन सत्ता-हस्तांतरण हो सकता है। पंक्तियों की संख्या को कुल शपथ/वास्तविक मंत्रिमंडल-संख्या न कहें।</p></Note><div className="politics-filters" role="search" aria-label="कार्यकाल खोज"><SearchField state={state}/><Filter state={state} label="आरंभ का दशक" name="decade" options={[...new Set(governments.map(item=>item.start.slice(0,3)))].map(key=>[key,`${key}0 का दशक`])}/><Clear state={state}/></div><p role="status">{records.length} बंद कार्यकाल अभिलेख</p>{records.length?<ScrollTable label={person?`${person.nameHi} — दर्ज ऐतिहासिक अवधि`:'मुख्यमंत्री कार्यकाल — आरंभ की तारीख के क्रम में'} headers={['मुख्यमंत्री','आरंभ','समाप्ति','दल / गठबंधन','स्रोत']} rows={records.map(item=>[<Link id={item.slug} to={`/politics/people/${item.personId}`}>{chiefMinisters.find(person=>person.slug===item.personId).nameHi}</Link>,dateLabel(item.start),dateLabel(item.end),item.partyAtTime||'इस सूची में संकलित नहीं',<SourceNotes ids={item.sourceIds}/>])}/>:<EmptyState action={<Clear state={state}/>}/>}</>;
}
export function PersonProfile({record}){return <><Evidence type="historical"/><p>{record.historicalRoles?.join(' · ')}</p><Governments person={record}/><RelatedContent items={[{title:'समकालीन ऐतिहासिक संदर्भ',to:'/politics/history'},{title:'आधिकारिक वर्तमान पदाधिकारी',to:'/politics/current'}]}/></>;}
export function CurrentDashboard(){const records=currentDataRegistry.filter(record=>record.module==='politics'&&record.entityType!=='party');return <><CurrentDataNotice/><ContentSection title="राज्य कार्यपालिका"><div className="politics-grid"><CurrentOfficeholder officeId="governor"/><CurrentOfficeholder officeId="chief-minister"/></div></ContentSection><ContentSection title="सदन, सूची और अधिसूचनाएँ"><div className="politics-grid">{records.map(record=><CurrentItem key={record.id} id={record.id}/>)}</div></ContentSection><ContentSection title="दल की वर्तमान मान्यता"><p>हर दल के profile में मान्यता का अलग currentData record है। पुराने ECI वर्ग को आज का वर्ग नहीं बनाया गया है।</p><Link className="politics-button" to="/politics/parties">दल चुनें और सत्यापन स्थिति देखें</Link></ContentSection></>;}
export function DepartmentDirectory(){const state=useDirectory(),records=alpha(departmentDirectory).filter(item=>matchesQuery(item,state.get('q'))&&(!state.get('category')||item.category===state.get('category')));return <><Note><p>यह मौजूदा शासन संग्रह के 14 विभागों का खोजयोग्य विस्तार है, सभी वर्तमान विभागों का रजिस्टर नहीं। मूल कार्य-आवंटन तथा नाम बदल सकते हैं।</p></Note><div className="politics-filters" role="search" aria-label="विभाग खोज"><SearchField state={state}/><Filter state={state} label="कार्य का विषय" name="category" options={[...new Set(departmentDirectory.map(item=>item.category))].map(value=>[value,value])}/><Clear state={state}/></div><Paged records={records} state={state} render={items=><div className="politics-grid">{items.map(item=>{const current=currentRecordById(item.currentDataRef);return <Card key={item.id} id={item.slug}><h2>{item.nameHi}</h2><small>{item.nameEn}</small><p>{item.summary}</p><CurrentDataCard record={current} title="विभाग का दिनांकित लिंक">{isCurrent(current)&&<a href={current.value.url} target="_blank" rel="noreferrer">आधिकारिक पोर्टल</a>}</CurrentDataCard><Link to={item.relatedRoute}>संबंधित संस्थागत विषय</Link></Card>;})}</div>}/></>;}
export function ServiceEducation(){return <section className="politics-page politics-service-extension"><div className="politics-wrap"><ContentSection title="सेवा को समझें, फिर आधिकारिक प्रक्रिया जाँचें"><Note><p>यह शैक्षणिक निर्देशिका है। बदलते फॉर्म, पात्रता, शुल्क या समय-सीमा यहाँ प्रकाशित नहीं किए जाते। व्यक्तिगत पहचान-पत्र इस पोर्टल पर जमा न करें।</p></Note><div className="politics-grid">{serviceTopics.map(item=><Card key={item.id} id={item.slug}><h3>{item.nameHi}</h3><small>{item.nameEn}</small><p>{item.summary}</p><SourceNotes ids={item.sourceIds}/></Card>)}</div></ContentSection><Link className="politics-button" to="/governance/civic-knowledge">नागरिक अधिकार और पारदर्शिता समझें</Link></div></section>;}
