import {Link} from 'react-router-dom';
import {ArrowRight,BookOpen,Building2,GraduationCap,HeartPulse,Home,Landmark,MapPin,MoveRight,School,ShieldCheck,Stethoscope,TrendingUp,UsersRound} from 'lucide-react';
import {Breadcrumbs,ContentSection,PageHero,SEO,Sources,TagList} from '../Portal';
import {demographicConcepts,districtDemographicRefs,educationIndicatorConcepts,educationIndicators,educationLevels,healthIndicators,healthSystemLevels,humanDevelopmentDimensions,migrationConcepts,mortalityConcepts,populationStatistics,settlementTypes,societySections,societySources,urbanProfileRefs} from '../../data/society';

const sourceList=keys=>keys.map(k=>societySources[k]);
const statusLabel={'official-census':'Official Census','official-survey':'Official survey',projection:'Projection',estimate:'Estimate'};
const sectionIcons={population:UsersRound,urbanization:Building2,migration:MoveRight,education:GraduationCap,health:HeartPulse,'human-development':TrendingUp};
const formatValue=x=>typeof x==='number'&&x>=1000?x.toLocaleString('en-IN'):x;

export function DataStatusBadge({item}){return <span className={`society-status status-${item.status}`}><b>{statusLabel[item.status]}</b><span>{item.censusYear?`Census ${item.censusYear}`:item.academicYear?`AY ${item.academicYear}`:item.referencePeriod||item.year}</span></span>}
export function CensusDisciplineNote(){return <aside className="society-callout census-note"><ShieldCheck/><div><b>Census 2011 — historical baseline, current population नहीं</b><p>यहाँ Census count, survey estimate और projection अलग data types हैं। G6 में कोई statewide population projection प्रकाशित नहीं की गई है; इसलिए 2011 count को 2026 संख्या की तरह न पढ़ें।</p></div></aside>}
export function IndicatorCard({item}){return <article className="society-stat"><small>{item.metric}</small><strong>{formatValue(item.value)} <em>{item.unit}</em></strong><DataStatusBadge item={item}/><p>{item.notes}</p></article>}
export function IndicatorGrid({items}){return <div className="society-stat-grid">{items.map(x=><IndicatorCard item={x} key={x.id}/>)}</div>}

export function RuralUrbanChart(){const rural=populationStatistics.find(x=>x.id==='rural-share'),urban=populationStatistics.find(x=>x.id==='urban-share');return <figure className="settlement-chart"><figcaption><b>ग्रामीण–शहरी संरचना</b><span>Census 2011 · percentage of total population</span></figcaption><div className="settlement-bars" aria-hidden="true"><span style={{'--share':`${rural.value}%`}}>ग्रामीण · {rural.value}%</span><span style={{'--share':`${urban.value}%`}}>शहरी · {urban.value}%</span></div><table><caption className="sr-only">Bihar rural and urban population share, Census 2011</caption><thead><tr><th>Classification</th><th>Population</th><th>Share</th><th>Reference</th></tr></thead><tbody><tr><td>ग्रामीण</td><td>9,23,41,436</td><td>88.7%</td><td>Census 2011</td></tr><tr><td>शहरी</td><td>1,17,58,016</td><td>11.3%</td><td>Census 2011</td></tr></tbody></table></figure>}

function SocietyHero({eyebrow='Population · settlements · capabilities',title='बिहार का समाज और मानव भूगोल',description='जनसंख्या, बस्तियों, mobility, शिक्षा, स्वास्थ्य और मानव विकास को dated official data तथा स्पष्ट definitions के साथ समझें।'}){return <PageHero eyebrow={eyebrow} title={title} description={description}/>}
function CrossLinks(){return <nav className="society-crosslinks" aria-label="संबंधित मॉड्यूल"><Link to="/economy">अर्थव्यवस्था</Link><Link to="/geography/agriculture">कृषि और ग्रामीण landscape</Link><Link to="/languages">भाषाएँ</Link><Link to="/history/modern-bihar">आधुनिक इतिहास</Link><Link to="/geography">भूगोल</Link><Link to="/governance/local-government">स्थानीय शासन</Link></nav>}
function ConceptGrid({items=demographicConcepts}){return <div className="society-concept-grid">{items.map(x=><article key={x.id}><small>{x.nameEn}</small><h3>{x.nameHi}</h3><p>{x.definition}</p>{x.guardrail&&<em>{x.guardrail}</em>}</article>)}</div>}

export function SocietyLanding(){const snapshot=['population-total','population-density','literacy-total','urban-share'].map(id=>populationStatistics.find(x=>x.id===id));return <main className="society-page"><SEO title="बिहार का समाज — जनसंख्या, शिक्षा, स्वास्थ्य और मानव विकास" description="Bihar population, urbanization, migration, literacy, education, health and human development की Census-aware guide।" canonicalPath="/society"/><SocietyHero/><section className="society-wrap"><CensusDisciplineNote/><IndicatorGrid items={snapshot}/><ContentSection title="समाज को छह lenses से समझें"><div className="society-directory">{societySections.map(x=>{const Icon=sectionIcons[x.id];return <Link to={x.to} key={x.id}><Icon/><small>{x.nameEn}</small><h2>{x.nameHi}</h2><p>{x.summary}</p><b>विस्तार से जानें <ArrowRight/></b></Link>})}</div></ContentSection><ContentSection title="आँकड़ा ≠ पूरी कहानी"><p>एक state average district, gender, rural–urban या household differences नहीं दिखाता। हर statistic को year, unit, geography, definition और source के साथ पढ़ना चाहिए; किसी व्यक्ति के बारे में aggregate data से निष्कर्ष नहीं निकाला जा सकता।</p></ContentSection><ContentSection title="जिला उदाहरण — ranking नहीं"><div className="district-society-grid">{districtDemographicRefs.map(x=><Link to={x.to} key={x.id}><MapPin/><b>{x.nameHi}</b><span>{x.context}</span><small>{x.dataRule}</small></Link>)}</div></ContentSection><ContentSection title="दूसरे modules से संबंध"><CrossLinks/></ContentSection><Sources sources={sourceList(['census','bihar','udise','nfhs'])}/></section></main>}

export function PopulationPage(){return <main className="society-page"><SEO title="बिहार की जनसंख्या — Census 2011, घनत्व और साक्षरता" description="Final Census 2011 के साथ Bihar population, density, growth, sex ratio, literacy और rural–urban distribution।" canonicalPath="/society/population"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'जनसंख्या'}]}/><SocietyHero eyebrow="Count ≠ projection ≠ survey estimate" title="बिहार की जनसंख्या और जनांकिकी" description="Final Census 2011 baseline को current population बताए बिना population concepts और denominators समझें।"/><section className="society-wrap"><CensusDisciplineNote/><IndicatorGrid items={populationStatistics}/><ContentSection title="घनत्व कैसे बनता है"><div className="density-formula"><span>जनसंख्या</span><b>÷</b><span>क्षेत्रफल (वर्ग किमी)</span><b>=</b><strong>व्यक्ति प्रति वर्ग किमी</strong></div><p>State density अलग-अलग districts और settlements की असमान distribution को छिपा सकती है। सीमा या area basis बदले तो comparison भी बदल सकता है।</p></ContentSection><ContentSection title="जनांकिकी की मुख्य अवधारणाएँ"><ConceptGrid/></ContentSection><ContentSection title="जिला context"><div className="district-society-grid">{districtDemographicRefs.map(x=><Link to={x.to} key={x.id}><MapPin/><b>{x.nameHi}</b><span>{x.context}</span><small>District page: जनगणना 2011 badge</small></Link>)}</div></ContentSection><Sources sources={sourceList(['census','bihar','ruralUrban'])}/></section></main>}

export function UrbanizationPage(){return <main className="society-page"><SEO title="बिहार में शहरीकरण — ग्रामीण–शहरी संरचना और नगर" description="Census 2011 rural-urban share, settlement definitions और Bihar urban systems।" canonicalPath="/society/urbanization"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'शहरीकरण'}]}/><SocietyHero eyebrow="Administrative label ≠ settlement experience" title="बिहार में शहरीकरण और बस्तियाँ" description="Urban share को statutory status, Census classification, regional services और rural–urban linkages के साथ पढ़ें।"/><section className="society-wrap"><CensusDisciplineNote/><RuralUrbanChart/><ContentSection title="Settlement types"><div className="society-concept-grid">{settlementTypes.map(x=><article key={x.id}><small>{x.nameEn}</small><h3>{x.nameHi}</h3><p>{x.definition}</p></article>)}</div></ContentSection><ContentSection title="शहरी systems — G5 canonical profiles"><p>ये society-context references हैं; city की economic भूमिका का canonical record G5 economy module में है। Selection कोई official ranking नहीं है।</p><div className="urban-society-grid">{urbanProfileRefs.map(x=><article key={x.id}><Building2/><h3>{x.nameHi}</h3><p>{x.summary}</p><div><Link to={x.canonicalEconomyRef}>आर्थिक भूमिका</Link><Link to={x.districtRef}>जिला profile</Link></div></article>)}</div></ContentSection><ContentSection title="ग्रामीण–शहरी continuum"><p>काम, शिक्षा, स्वास्थ्य, trade, transport और seasonal mobility village तथा town को जोड़ते हैं। Census boundary या municipal upgrade में बदलाव को स्वतः population growth नहीं माना जा सकता।</p><CrossLinks/></ContentSection><Sources sources={sourceList(['census','ruralUrban'])}/></section></main>}

export function MigrationPage(){return <main className="society-page"><SEO title="बिहार में प्रवासन — migration concepts, sources और context" description="Bihar migration को in, out, seasonal, return और circular mobility के neutral framework में समझें।" canonicalPath="/society/migration"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'प्रवासन'}]}/><SocietyHero eyebrow="Mobility ≠ एक कारण या एक दिशा" title="प्रवासन, गतिशीलता और परिवार" description="काम, शिक्षा, विवाह, household strategy, networks और shocks—migration के multiple contexts हो सकते हैं।"/><section className="society-wrap"><aside className="society-callout"><MoveRight/><div><b>Census migration table का अर्थ</b><p>D-05 place of last residence, age, sex, reason और duration को Census 2011 frame में दर्ज करता है। यह live flow counter नहीं और हर short-term circular movement को पूरा capture नहीं करता।</p></div></aside><ContentSection title="प्रवासन के प्रकार"><ConceptGrid items={migrationConcepts}/></ContentSection><ContentSection title="कारण और सावधानियाँ"><div className="migration-path"><span>काम और wages</span><span>शिक्षा</span><span>परिवार/विवाह</span><span>seasonal cycle</span><span>आपदा और return</span></div><p>Out-migration को केवल failure या success narrative नहीं बनाया गया है। Aggregate district/state data किसी व्यक्ति की स्थिति, कौशल या identity नहीं बताता।</p></ContentSection><ContentSection title="Economy और mobility"><p>Labour-market concepts, employment definitions और urban economic nodes G5 में canonical हैं।</p><nav className="society-crosslinks"><Link to="/economy/migration">रोजगार और economic migration</Link><Link to="/economy/urban">Urban economic centres</Link><Link to="/geography/agriculture">Seasonal rural context</Link></nav></ContentSection><Sources sources={sourceList(['migration','census'])}/></section></main>}

export function EducationPage(){return <main className="society-page"><SEO title="बिहार में शिक्षा — literacy, school indicators और higher education" description="Census literacy, UDISE+ school indicators, AISHE higher education और definition-aware Bihar education guide।" canonicalPath="/society/education"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'शिक्षा'}]}/><SocietyHero eyebrow="Literacy ≠ enrolment ≠ learning" title="शिक्षा और सामाजिक capability" description="Census literacy, UDISE+ school data और AISHE higher-education records के अलग years और definitions को साथ रखें।"/><section className="society-wrap"><ContentSection title="शिक्षा की layers"><div className="education-levels">{educationLevels.map((x,i)=>{const Icon=[School,GraduationCap,Landmark,BookOpen][i];return <article key={x.id}><Icon/><small>{x.nameEn}</small><h3>{x.nameHi}</h3><p>{x.scope}</p></article>})}</div></ContentSection><ContentSection title="प्रकाशित संकेतक"><IndicatorGrid items={educationIndicators}/><aside className="society-callout"><ShieldCheck/><div><b>UDISE+ comparability note</b><p>2022–23 से student-level collection और methodology changes के कारण GER, NER, dropout जैसे indicators को older reports से strict trend की तरह compare नहीं करना चाहिए। हर value academic year और level के साथ है।</p></div></aside></ContentSection><ContentSection title="Indicator dictionary"><ConceptGrid items={educationIndicatorConcepts}/></ContentSection><ContentSection title="Higher education और knowledge heritage"><p>AISHE modern higher-education institutions का survey है। प्राचीन नालंदा महाविहार और आधुनिक Nalanda University अलग historical/institutional entities हैं; उन्हें एक continuous institution नहीं दिखाया गया।</p><nav className="society-crosslinks"><Link to="/history/nalanda-mahavihara">प्राचीन नालंदा</Link><Link to="/history/ancient-universities">प्राचीन universities</Link><Link to="/district/nalanda">नालंदा जिला</Link></nav></ContentSection><Sources sources={sourceList(['bihar','udise','aishe','census'])}/></section></main>}

export function HealthPage(){return <main className="society-page"><SEO title="बिहार में स्वास्थ्य — system hierarchy और survey indicators" description="Bihar health system levels, NFHS-5 indicators, IMR/MMR units और source-aware interpretation।" canonicalPath="/society/health"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'स्वास्थ्य'}]}/><SocietyHero eyebrow="Facility count ≠ staff, beds, access or quality" title="स्वास्थ्य, पोषण और सामाजिक अवसंरचना" description="Health-system hierarchy और household-survey outcomes को उनके year, denominator और reference period के साथ समझें।"/><section className="society-wrap"><ContentSection title="Public health-system hierarchy"><div className="health-ladder">{healthSystemLevels.map((x,i)=><article key={x.id}><span>{String(i+1).padStart(2,'0')}</span><Stethoscope/><div><h3>{x.name}</h3><p>{x.role}</p></div></article>)}</div><p className="boundary-note">किसी facility की गिनती staffing, functional beds, opening hours, service availability, distance या care quality का प्रमाण नहीं है। इसी कारण बिना current facility source के counts नहीं जोड़े गए।</p></ContentSection><ContentSection title="NFHS-5 Bihar snapshot"><IndicatorGrid items={healthIndicators}/><p>ये NFHS-5 (2019–20) household survey estimates हैं—current administrative totals नहीं। Rural/urban या survey-round comparison में denominator और footnotes साथ पढ़ें।</p></ContentSection><ContentSection title="Mortality units — denominator न बदलें"><div className="mortality-grid">{mortalityConcepts.map(x=><article key={x.id}><HeartPulse/><h3>{x.name}</h3><strong>{x.unit}</strong><p>{x.definition}</p><small>{x.referencePeriod}</small></article>)}</div><p>इस पृष्ठ पर IMR/MMR value प्रकाशित नहीं की गई है, क्योंकि year-specific SRS bulletin से exact Bihar value जोड़े बिना “latest” कहना उचित नहीं होगा।</p></ContentSection><Sources sources={sourceList(['nfhs','rhs','srs'])}/></section></main>}

export function HumanDevelopmentPage(){return <main className="society-page"><SEO title="बिहार में मानव विकास — health, education, income और inequality" description="Human development के health, education, income, infrastructure, gender और spatial dimensions की careful guide।" canonicalPath="/society/human-development"/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'मानव विकास'}]}/><SocietyHero eyebrow="एक score ≠ lived experience" title="मानव विकास और सामाजिक परिवर्तन" description="Capabilities को health, education, livelihoods, infrastructure और unequal access के संयुक्त frame में पढ़ें।"/><section className="society-wrap"><aside className="society-callout"><ShieldCheck/><div><b>कोई self-calculated Bihar HDI नहीं</b><p>इस portal ने अलग years या incompatible sources को मिलाकर अपना HDI/ranking नहीं बनाया। Composite score तभी दिखेगा जब official methodology, edition और reference period साथ उपलब्ध हों।</p></div></aside><ContentSection title="मानव विकास के आयाम"><div className="development-wheel">{humanDevelopmentDimensions.map(x=><article key={x.id}><span>{x.name}</span><p>{x.description}</p></article>)}</div></ContentSection><ContentSection title="सामाजिक परिवर्तन को कैसे पढ़ें"><p>Urbanization, migration, school participation, health access और livelihood shifts एक-दूसरे से जुड़े हैं, पर causal claim के लिए अधिक evidence चाहिए। State average को district ranking या किसी community/person की विशेषता नहीं माना गया।</p><CrossLinks/></ContentSection><ContentSection title="डेटा checklist"><ul className="society-checklist"><li>Year/reference period क्या है?</li><li>Geography state, district या settlement है?</li><li>Unit और denominator क्या हैं?</li><li>Census, survey, projection या estimate?</li><li>Methodology revisions comparability बदलती हैं?</li></ul></ContentSection><Sources sources={sourceList(['niti','nfhs','udise','census'])}/></section></main>}

export function DemographicConceptPage({item}){return <main className="society-page"><SEO title={item.seo.title} description={item.seo.description} type="article" canonicalPath={item.seo.canonical}/><Breadcrumbs items={[{label:'समाज',to:'/society'},{label:'जनसंख्या',to:'/society/population'},{label:item.nameHi}]}/><SocietyHero eyebrow={item.nameEn} title={item.nameHi} description={item.definition}/><section className="society-wrap"><ContentSection title="क्या मापा जाता है"><p>{item.definition}</p></ContentSection><ContentSection title="व्याख्या की सीमा"><p>{item.guardrail}</p></ContentSection><nav className="society-crosslinks"><Link to="/society/population">सभी population indicators</Link><Link to="/districts">जिला directory</Link></nav><Sources sources={[item.source]}/></section></main>}
