import {Link} from 'react-router-dom';import {ArrowRight,Bird,ExternalLink,Fish,Footprints,Leaf,Map,ShieldCheck,Trees,Waves} from 'lucide-react';import {Breadcrumbs,ContentSection,InfoGrid,PageHero,SEO,Sources,TagList} from '../Portal';import {ecologyGlossary,ecologySources,ecologyTopics,ecologyWetlands,ecosystems,protectedAreas,species} from '../../data/geography/ecology';
const schematic='सांकेतिक आरेख — वास्तविक भौगोलिक मानचित्र नहीं';
const linkFor=(kind,x)=>kind==='ecosystem'?x.seo.canonical:kind==='protected'?x.seo.canonical:kind==='species'?x.seo.canonical:x.seo.canonical;
export function EcologyHero(){return <PageHero eyebrow="Landscape → ecosystem → habitat → species" title="बिहार की पारिस्थितिकी" description="तराई, गंगा riverscape, floodplain wetlands, पठारी वन, representative wildlife और conservation का scientific, source-aware परिचय।"/>}
export function EcosystemCard({item}){return <Link className="eco-card" to={item.seo.canonical}><Leaf/><small>{item.ecosystemType}</small><h3>{item.nameHi}</h3><p>{item.summary}</p><span>पारिस्थितिकी पढ़ें <ArrowRight/></span></Link>}
export function ProtectedAreaCard({item}){return <Link className="eco-card pa-card" to={item.seo.canonical}><ShieldCheck/><small>{item.designationType}</small><h3>{item.nameHi}</h3><p>{item.landscapeType}</p><span>{item.districts.join(' · ')}</span></Link>}
export function SpeciesCard({item}){return <Link className="eco-card species-card" to={item.seo.canonical}><Footprints/><small>{item.group}</small><h3>{item.commonNameHi}</h3><i>{item.scientificName}</i><p>{item.BiharContext}</p></Link>}
export function BiodiversitySummary(){return <section className="biodiversity-summary"><h2>Species list से आगे</h2><div><article><Trees/><b>Habitat mosaic</b><p>Forest, grassland, river, sandbar और wetland अलग लेकिन connected habitats हैं।</p></article><article><Waves/><b>Ecological process</b><p>Flow, inundation, erosion, succession और migration biodiversity shape करते हैं।</p></article><article><Fish/><b>People and livelihoods</b><p>Fisheries, agriculture और forest dependence conservation landscape का हिस्सा हैं।</p></article></div></section>}
export function HabitatProfile({item}){return <div className="habitat-profile"><InfoGrid items={[[`Physical context`,item.physicalContext],['Hydrology',item.hydrology],['Vegetation',item.vegetation],['District associations',item.districts]]}/><ContentSection title="Ecological processes"><TagList items={item.ecologicalProcesses}/></ContentSection><ContentSection title="Ecosystem services"><TagList items={item.ecosystemServices}/></ContentSection></div>}
export function ThreatsSection({items=[]}){return <section className="threats-section"><h2>दबाव और conservation questions</h2><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><p>Threat का अर्थ हर location पर समान severity नहीं; dated monitoring आवश्यक है।</p></section>}
export function ConservationNote({children}){return <aside className="conservation-note"><ShieldCheck/><div><h2>संरक्षण संदर्भ</h2><p>{children}</p></div></aside>}
export function HabitatConnectivity(){return <section className="connectivity"><h2>आवास संपर्क और corridors</h2><p>{schematic}</p><div><span>Protected habitat</span><b>↔</b><span>forest/grassland matrix</span><b>↔</b><span>river/wetland corridor</span><b>↔</b><span>neighbouring landscape</span></div><p>Corridor broad ecological connectivity है—precise animal route, den, nest या tracking map नहीं।</p></section>}
export function MigrationContext({text}){return <section className="migration-context"><Bird/><div><h2>प्रवासी पक्षी</h2><p>{text}</p><p>Observation किसी species की permanent statewide distribution का प्रमाण नहीं। Breeding/congregation coordinates प्रकाशित नहीं हैं।</p></div></section>}
export function SourceQualityNote(){return <aside className="source-quality"><h2>डेटा कैसे पढ़ें</h2><p>Forest cover, recorded forest area और protected area अलग measures हैं। Species conservation status local abundance नहीं बताता; Ramsar designation हर wetland पर लागू नहीं होता। Current sightings, counts और closures इस stable module में नहीं हैं।</p></aside>}
export function EcologyMap({item}){const m=item.map;return <figure className="ecology-map" aria-label={m.accessibleDescription}><figcaption>{m.label}</figcaption><div>{m.legend.map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><p><Map/> Source layer: <a href={m.source.url} target="_blank" rel="noreferrer">{m.source.title}<ExternalLink/></a></p></figure>}
export function EcosystemProfile({item:x}){return <main className="geo-page ecology-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:'Ecosystems',to:'/geography/ecology/ecosystems'},{label:x.nameHi}]}/><PageHero eyebrow={x.ecosystemType} title={x.nameHi} description={x.summary}/><section className="geo-wrap"><p className="eco-lede">{x.description}</p><HabitatProfile item={x}/><EcologyMap item={x}/><ThreatsSection items={x.threats}/><ConservationNote>{x.conservationContext}</ConservationNote><RelatedEcology item={x}/><Sources sources={x.sources}/></section></main>}
export function ProtectedAreaProfile({item:x}){return <main className="geo-page ecology-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:'Protected areas',to:'/geography/ecology/protected-areas'},{label:x.nameHi}]}/><PageHero eyebrow={x.designationType} title={x.nameHi} description={x.conservationImportance}/><section className="geo-wrap"><InfoGrid items={[[`Official name`,x.officialName],['जिले',x.districts],['Area reference',`${x.area.value} ${x.area.unit} · ${x.area.dataYear}`],['Landscape',x.landscapeType]]}/><ContentSection title="Designation terminology"><p>{x.notificationContext}</p></ContentSection><ContentSection title="Habitats"><TagList items={x.habitats}/></ContentSection><ConservationNote>{x.conservationImportance}</ConservationNote><HabitatConnectivity/><p className="responsible-note">Responsible visit: दूरी रखें, wildlife को feed/call/playback से disturb न करें, litter न करें और current official rules मानें। {x.visitorContext}</p><RelatedProtected item={x}/><Sources sources={x.sources}/></section></main>}
export function SpeciesProfile({item:x}){return <main className="geo-page ecology-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:'Species',to:'/geography/ecology/species'},{label:x.commonNameHi}]}/><PageHero eyebrow={`${x.group} · ${x.scientificName}`} title={x.commonNameHi} description={x.BiharContext}/><section className="geo-wrap"><InfoGrid items={[[`Scientific name`,x.scientificName],['Habitat refs',x.habitats],['Bihar region',x.regions],['Conservation status',`${x.conservationStatus.label} · ${x.conservationStatus.system} · ${x.conservationStatus.assessmentYear}`]]}/><ContentSection title="Ecology"><p>{x.ecologySummary}</p></ContentSection><ThreatsSection items={x.threats}/><ConservationNote>Species presence किसी जिले की हर जगह permanent population नहीं बताती। कोई current count, sighting या precise habitat coordinate नहीं दिया गया।</ConservationNote><Sources sources={x.sources}/></section></main>}
export function WetlandEcologyProfile({item:x}){return <main className="geo-page ecology-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:'Wetlands',to:'/geography/ecology/wetlands'},{label:x.nameHi}]}/><PageHero eyebrow="Wetland ecology" title={x.nameHi} description={x.summary}/><section className="geo-wrap"><ContentSection title="Aquatic ecology"><TagList items={x.ecology}/><p>{x.livelihoods}</p></ContentSection><MigrationContext text={x.migrationContext}/>{x.recognition&&<InfoGrid items={[[`Official Ramsar name`,x.recognition.officialName],['Site number',x.recognition.siteNumber],['Designation date',x.recognition.designationDate]]}/>}<ThreatsSection items={x.pressures}/>{x.hydrologyRef&&<Link className="eco-crosslink" to={`/geography/wetlands/${x.hydrologyRef}`}>Hydrology layer देखें <ArrowRight/></Link>}<Sources sources={x.sources}/></section></main>}
export function ConservationPage(){const x=ecologyTopics.conservation;return <main className="geo-page ecology-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:x.nameHi}]}/><PageHero eyebrow="Habitat · species · people" title={x.nameHi} description={x.summary}/><section className="geo-wrap"><HabitatConnectivity/><div className="system-grid">{x.sections.map(([h,p])=><article key={h}><h2>{h}</h2><p>{p}</p></article>)}</div><SourceQualityNote/><Sources sources={x.sources}/></section></main>}
function RelatedEcology({item:x}){return <nav className="eco-related" aria-label="संबंधित पारिस्थितिकी">{x.relatedProtectedAreas.map(id=>{const p=protectedAreas.find(v=>v.id===id);return p&&<Link key={id} to={p.seo.canonical}>{p.nameHi}</Link>})}{x.relatedRivers.map(id=><Link key={id} to={`/geography/rivers/${id}`}>{id} river</Link>)}{x.relatedDistricts.map(id=><Link key={id} to={`/district/${id}`}>{id} district</Link>)}{x.relatedTourism.map(id=><Link key={id} to={`/tourism/${id}`}>{id} tourism</Link>)}</nav>}
function RelatedProtected({item:x}){return <nav className="eco-related">{x.ecosystemTypes.map(id=>{const e=ecosystems.find(v=>v.id===id);return e&&<Link key={id} to={e.seo.canonical}>{e.nameHi}</Link>})}{x.representativeSpecies.map(id=>{const s=species.find(v=>v.id===id);return s&&<Link key={id} to={s.seo.canonical}>{s.commonNameHi}</Link>})}{x.districts.map(id=><Link key={id} to={`/district/${id}`}>{id} जिला</Link>)}</nav>}
export function EcologyGlossary(){return <section className="eco-glossary"><h2>Ecology शब्दावली</h2><dl>{ecologyGlossary.map(([t,d])=><div key={t}><dt>{t}</dt><dd>{d}</dd></div>)}</dl></section>}
export function EcologyLanding(){return <main className="geo-page ecology-page"><SEO title="बिहार की पारिस्थितिकी — वन, आर्द्रभूमि, नदियाँ, वन्यजीव और संरक्षण" description="Bihar ecosystems, protected areas, river and wetland ecology, representative wildlife and conservation की source-aware guide।" canonicalPath="/geography/ecology"/><EcologyHero/><section className="geo-wrap"><BiodiversitySummary/><ContentSection title="बिहार के ecosystem landscapes"><div className="eco-grid">{ecosystems.map(x=><EcosystemCard key={x.id} item={x}/>)}</div></ContentSection><ContentSection title="Protected landscapes"><div className="eco-grid">{protectedAreas.slice(0,5).map(x=><ProtectedAreaCard key={x.id} item={x}/>)}</div><Link className="eco-more" to="/geography/ecology/protected-areas">सभी protected areas <ArrowRight/></Link></ContentSection><ContentSection title="Representative wildlife"><div className="eco-grid species-grid">{species.map(x=><SpeciesCard key={x.id} item={x}/>)}</div></ContentSection><ContentSection title="Wetland ecology और migration"><div className="eco-grid">{ecologyWetlands.map(x=><Link className="eco-card" key={x.id} to={x.seo.canonical}><Bird/><h3>{x.nameHi}</h3><p>{x.summary}</p></Link>)}</div></ContentSection><HabitatConnectivity/><Link className="eco-more" to="/geography/ecology/conservation">Conservation और environmental pressures <ArrowRight/></Link><SourceQualityNote/><EcologyGlossary/><Sources sources={[ecologySources.wii,ecologySources.fsi,ecologySources.ramsar,ecologySources.dolphin]}/></section></main>}
export function EcologyDirectory({kind}){const config=kind==='ecosystems'?['Ecosystem directory',ecosystems,EcosystemCard]:kind==='species'?['Representative species',species,SpeciesCard]:kind==='wetlands'?['Wetland ecology',ecologyWetlands,({item:x})=><Link className="eco-card" to={x.seo.canonical}><Bird/><h3>{x.nameHi}</h3><p>{x.summary}</p></Link>]:['Protected areas',protectedAreas,ProtectedAreaCard], [title,items,Card]=config;return <main className="geo-page ecology-page"><SEO title={`${title} — बिहार ecology`} description={`Bihar ${title} source-aware directory।`} canonicalPath={`/geography/ecology/${kind}`}/><Breadcrumbs items={[{label:'भूगोल',to:'/geography'},{label:'पारिस्थितिकी',to:'/geography/ecology'},{label:title}]}/><PageHero eyebrow="Source-aware directory" title={title} description="Administrative designation, ecosystem और tourism को अलग context में पढ़ें।"/><section className="eco-grid geo-wrap">{items.map(x=><Card key={x.id} item={x}/>)}</section></main>}
