import {useState} from 'react';
import {useParams,Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowDown,ArrowRight,ChevronLeft,ChevronRight,Landmark,BookOpen,Users,MapPin,Flag} from 'lucide-react';
import {historyPeriods,historyEras,eraById,historyBySlug,periodNavigation,historyPersonalities,historyPlaces,ancientPageBySlug} from '../data/history';
import AncientHistoryPage from '../components/history/HistoryDetailPage';
import {SEO,Breadcrumbs,PageHero,ContentSection,InfoGrid,TagList,RelatedContent,Sources,EmptyState} from '../components/Portal';

const typeLabels={era:'कालखंड',kingdom:'राज्य',dynasty:'राजवंश',event:'घटना',institution:'ज्ञान केंद्र',movement:'आंदोलन',transition:'संक्रमण'};
const overview=[['कालखंड','प्रारंभिक से आधुनिक बिहार तक',Landmark],['राज्य और राजवंश','मगध, मौर्य, गुप्त और पाल',Flag],['ज्ञान केंद्र','नालंदा, विक्रमशिला और ओदंतपुरी',BookOpen],['जन आंदोलन','1857, चंपारण और भारत छोड़ो',Users],['ऐतिहासिक नगर','राजगीर, वैशाली, पाटलिपुत्र और सासाराम',MapPin]];
const threads=[{title:'मगध से मौर्य तक',path:['मगध','नंद','मौर्य'],target:'magadh'},{title:'प्राचीन ज्ञान केंद्र',path:['नालंदा','विक्रमशिला','ओदंतपुरी'],target:'nalanda'},{title:'स्वतंत्रता की यात्रा',path:['1857','चंपारण','1942','1947'],target:'1857-bihar'},{title:'आधुनिक परिवर्तन',path:['स्वतंत्रता','जेपी आंदोलन','झारखंड गठन','21वीं सदी'],target:'independence'}];
const reveal={initial:{opacity:0,y:18},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.12},transition:{duration:.45}};

function PeriodCard({period,index}){const era=eraById(period.era);return <motion.article {...reveal} id={period.id} className="master-period"><div className="timeline-index" aria-hidden="true">{String(index+1).padStart(2,'0')}</div><div className="period-card"><div className="period-meta"><time>{period.displayPeriod}</time><span className={`type-badge ${period.type}`}>{typeLabels[period.type]}</span></div><small>{era?.fullLabelHindi}</small><h2>{period.titleHindi}</h2><p>{period.shortDescription}</p><div className="period-relations">{period.importantPeople.length>0&&<span><Users/> {period.importantPeople.map(id=>historyPersonalities.find(x=>x.id===id)?.name||id).join(' • ')}</span>}{period.importantPlaces.length>0&&<span><MapPin/> {period.importantPlaces.map(id=>historyPlaces.find(x=>x.id===id)?.name||id.replaceAll('-',' ')).join(' • ')}</span>}</div>{period.status==='available'?<Link to={period.route}>और जानें <ArrowRight/></Link>:<span className="planned">विस्तृत लेख आगामी चरण में</span>}</div></motion.article>}

export function History(){const [activeEra,setActiveEra]=useState('all');const shown=activeEra==='all'?historyPeriods:historyPeriods.filter(x=>x.era===activeEra);return <main><SEO title="बिहार का इतिहास | मगध, मौर्य, नालंदा से आधुनिक बिहार तक" description="प्रारंभिक बिहार, महाजनपद, मगध, मौर्य, नालंदा, मध्यकाल, स्वतंत्रता आंदोलन और आधुनिक बिहार की क्रमबद्ध हिंदी समयरेखा।"/><Breadcrumbs items={[{label:'इतिहास'}]}/><PageHero eyebrow="सभ्यता की यात्रा" title="बिहार की ऐतिहासिक यात्रा" description="प्राचीन सभ्यताओं और मगध से आधुनिक बिहार तक — हजारों वर्षों की एक जीवंत यात्रा।"><a className="btn primary history-cta" href="#master-timeline">समय यात्रा शुरू करें <ArrowDown/></a></PageHero><section className="history-overview" aria-label="इतिहास का संक्षिप्त परिचय">{overview.map(([title,text,Icon])=><article key={title}><Icon/><small>{title}</small><b>{text}</b></article>)}</section><section className="master-history" id="master-timeline"><div className="history-heading"><span>आरंभ से वर्तमान तक</span><h2>मास्टर समयरेखा</h2><p>कालखंड चुनें या क्रम से पढ़ते हुए देखें कि बिहार का एक ऐतिहासिक चरण अगले चरण से कैसे जुड़ता है।</p></div><div className="era-tabs" role="toolbar" aria-label="इतिहास कालखंड फ़िल्टर"><button aria-pressed={activeEra==='all'} className={activeEra==='all'?'active':''} onClick={()=>setActiveEra('all')}>सभी</button>{historyEras.map(era=><button aria-pressed={activeEra===era.id} className={activeEra===era.id?'active':''} onClick={()=>setActiveEra(era.id)} key={era.id}>{era.labelHindi}</button>)}</div><div className="master-timeline">{shown.map(period=><PeriodCard key={period.id} period={period} index={historyPeriods.indexOf(period)}/>)}</div></section><section className="history-threads"><div className="history-heading"><span>विषयगत मार्ग</span><h2>इतिहास को विषय के अनुसार समझें</h2></div><div>{threads.map(thread=><a href={`#${thread.target}`} key={thread.title}><h3>{thread.title}</h3><p>{thread.path.map((x,i)=><span key={x}>{x}{i<thread.path.length-1&&<ArrowRight/>}</span>)}</p></a>)}</div></section><section className="history-people"><div className="history-heading"><span>प्रमुख नाम</span><h2>इतिहास के व्यक्तित्व</h2></div><div>{historyPersonalities.map(p=><Link to={p.route} key={p.id}><div className="portrait-placeholder" aria-hidden="true">{p.name.charAt(0)}</div><small>चित्र उपलब्ध नहीं</small><h3>{p.name}</h3><p>{p.role}</p></Link>)}</div></section><section className="history-places"><div className="history-heading"><span>ऐतिहासिक भूगोल</span><h2>वे स्थान जहाँ इतिहास आज भी दिखाई देता है</h2></div><div>{historyPlaces.map(place=><Link to={place.route} key={place.id}><MapPin/><h3>{place.name}</h3><p>{place.importance}</p><span>स्थान देखें <ArrowRight/></span></Link>)}</div></section></main>}

export function HistoryDetail(){const {slug}=useParams(),ancientPage=ancientPageBySlug(slug);if(ancientPage)return <AncientHistoryPage page={ancientPage}/>;const x=historyBySlug(slug);if(!x||x.status!=='available')return <EmptyState title="यह विस्तृत इतिहास लेख अभी उपलब्ध नहीं है" text="इस कालखंड को मास्टर समयरेखा में पढ़ें; गहन सामग्री आगामी इतिहास चरण में जोड़ी जाएगी।"/>;const era=eraById(x.era),nav=periodNavigation(slug),people=x.importantPeople.map(id=>historyPersonalities.find(p=>p.id===id)?.name||id),places=x.importantPlaces.map(id=>historyPlaces.find(p=>p.id===id)?.name||id);return <main><SEO title={x.titleHindi} description={x.summary} type="article"/><Breadcrumbs items={[{label:'इतिहास',to:'/history'},{label:x.titleHindi}]}/><PageHero eyebrow={`${era?.fullLabelHindi} · ${x.displayPeriod}`} title={x.titleHindi} description={x.summary}/><div className="article-layout"><article><InfoGrid items={[[`काल`,x.displayPeriod],['प्रकार',typeLabels[x.type]],['प्रमुख व्यक्तित्व',people.length?people:'—'],['प्रमुख स्थान',places.length?places:'—']]}/><ContentSection title="ऐतिहासिक पृष्ठभूमि"><p>{x.summary}</p></ContentSection><ContentSection title="कालक्रम में स्थान"><p>यह चरण <b>{nav.previous?.titleHindi||'बिहार की आरंभिक ऐतिहासिक पृष्ठभूमि'}</b> के बाद और <b>{nav.next?.titleHindi||'समकालीन बिहार'}</b> से पहले समयरेखा में स्थित है। आगे के चरणों में इसके प्रमाण, बहस और उप-विषयों का विस्तृत अध्ययन जोड़ा जाएगा।</p></ContentSection>{people.length>0&&<ContentSection title="संबंधित व्यक्तित्व"><TagList items={people}/></ContentSection>}{places.length>0&&<ContentSection title="संबंधित स्थान"><TagList items={places}/></ContentSection>}<Sources sources={x.sources}/><nav className="period-nav" aria-label="आसपास के कालखंड">{nav.previous?<a href={`/history#${nav.previous.id}`}><ChevronLeft/><span><small>पिछला कालखंड</small>{nav.previous.titleHindi}</span></a>:<span/>}{nav.next?<a href={`/history#${nav.next.id}`}><span><small>अगला कालखंड</small>{nav.next.titleHindi}</span><ChevronRight/></a>:null}</nav></article><aside><h3>कालखंड</h3><p>{era?.fullLabelHindi}</p><span className={`type-badge ${x.type}`}>{typeLabels[x.type]}</span><Link className="aside-link" to="/history">पूरी समयरेखा →</Link></aside></div><RelatedContent items={[nav.previous,nav.next].filter(Boolean).map(y=>({title:y.titleHindi,to:`/history#${y.id}`,type:eraById(y.era)?.labelHindi}))}/></main>}
