import {Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowRight,MapPin,Compass,ChevronRight,Quote,CalendarDays} from 'lucide-react';
import {SectionTitle} from '../components/Layout';
import BiharDistrictMap from '../components/BiharDistrictMap';
import {stats,eras,destinations,culture,people} from '../data/content';
import {districts} from '../data/districts';
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.65}};
export default function Home(){return <main>
 <section className="hero"><div className="hero-bg"/><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><span className="kicker">भारत की प्राचीन ज्ञान-भूमि</span><h1><em>बिहार</em> — जहाँ इतिहास ने भारत को दिशा दी</h1><p>सभ्यताओं की जन्मभूमि, ज्ञान की प्राचीन ज्योति और लोकजीवन के अनगिनत रंगों से सजी एक जीवंत यात्रा।</p><div className="hero-actions"><a className="btn primary" href="#history">इतिहास देखें <ArrowRight/></a><a className="btn secondary" href="#tourism">यात्रा शुरू करें <Compass/></a></div></motion.div><div className="hero-note"><span>01</span><p><b>नालंदा</b><br/>विश्व की प्राचीनतम ज्ञान परंपराओं में से एक</p></div></section>
 <section className="stats">{stats.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section>
 <section id="about" className="intro"><motion.div {...reveal}><span className="chapter">01 · बिहार का परिचय</span><h2>एक प्रदेश, <em>अनेक संसार</em></h2></motion.div><motion.div {...reveal}><p className="lead">हिमालय की तराई से गंगा के मैदानों तक, बिहार केवल एक भौगोलिक प्रदेश नहीं—यह विचार, आस्था और जन-संस्कृति की अनवरत यात्रा है।</p><p>यहीं बुद्ध को ज्ञान मिला, महावीर ने अहिंसा का संदेश दिया और नालंदा ने संसार को सीखने की नई दृष्टि दी।</p><a className="text-link" href="#history">बिहार को विस्तार से जानें <ArrowRight/></a></motion.div></section>
 <section id="history" className="history"><SectionTitle dark eyebrow="कालखंड" title="बिहार की ऐतिहासिक यात्रा" desc="ढाई सहस्राब्दियों से भी अधिक समय में फैली सभ्यता की कुछ निर्णायक झलकियाँ।"/><div className="timeline">{eras.map((e,i)=><motion.article {...reveal} key={e.period}><div className="dot">{String(i+1).padStart(2,'0')}</div><div className="year">{e.year}</div><div><span>{e.period}</span><h3>{e.title}</h3><p>{e.text}</p></div></motion.article>)}</div><Link className="btn gold" to="/history">पूरी ऐतिहासिक यात्रा <ArrowRight/></Link></section>
 <section id="tourism" className="section"><SectionTitle eyebrow="अनुभव करें" title="बिहार की यात्रा" desc="आस्था, स्थापत्य और प्रकृति—हर पड़ाव अपने भीतर सदियों की कहानी समेटे है।"/><div className="destination-grid">{destinations.map((d,i)=><motion.article {...reveal} className="destination" key={d.name}><Link to={d.to||`/tourism/${d.slug}`} className="destination-link" aria-label={`${d.name} यात्रा गाइड देखें`}><img src={d.image} alt={d.alt||d.name} loading="lazy"/><div className="shade"/><span className="number">0{i+1}</span><div className="destination-info"><small>{d.tag}</small><h3>{d.name}</h3><p><MapPin size={15}/>{d.place}</p></div><span className="destination-btn" aria-hidden="true"><ArrowRight/></span></Link></motion.article>)}</div><div className="center"><Link to="/tourism" className="text-link green">सभी पर्यटन स्थल देखें <ArrowRight/></Link></div></section>
 <section id="culture" className="culture-wrap"><div className="pattern"/><SectionTitle eyebrow="लोक और परंपरा" title="बिहार की जीवंत संस्कृति" desc="रंगों, गीतों, पर्वों और लोककथाओं में बसी मिट्टी की आत्मा।"/><div className="culture-grid">{culture.map(({title,label,Icon,text,to})=><motion.article {...reveal} key={title}><Link to={to} className="culture-link" aria-label={`${title} के बारे में और जानें`}><div className="icon"><Icon/></div><small>{label}</small><h3>{title}</h3><p>{text}</p><span className="culture-cta">और जानें <ChevronRight/></span></Link></motion.article>)}</div></section>
 <section id="districts" className="districts"><div><SectionTitle eyebrow="जिला दर्शन" title="38 जिले, 38 विशिष्ट पहचान" desc="हर जिले की अपनी बोली, स्वाद, स्मृति और सांस्कृतिक धरोहर है।"/><div className="district-list">{districts.slice(0,12).map((d,i)=><Link to={`/district/${d.slug}`} key={d.slug}><span>{String(i+1).padStart(2,'0')}</span>{d.nameHindi}<ChevronRight/></Link>)}</div><Link to="/districts" className="btn secondary">सभी जिले देखें <ArrowRight/></Link></div><BiharDistrictMap/></section>
 <section id="people" className="people section"><SectionTitle eyebrow="प्रेरणास्रोत" title="महान व्यक्तित्व"/><div className="people-grid">{people.map(({name,role,Icon,to},i)=><motion.article {...reveal} key={name}><Link to={to} className="people-link" aria-label={`${name} का परिचय देखें`}><span>0{i+1}</span><Icon/><div><h3>{name}</h3><p>{role}</p></div><ArrowRight/></Link></motion.article>)}</div></section>
 <section id="stories" className="story"><Quote/><span>इतिहास में आज</span><h2>“बिहार की कहानी केवल अतीत नहीं,<br/>भारत के भविष्य की एक जीवंत भूमिका है।”</h2><div><CalendarDays/><p><b>ज्ञान का एक नया अध्याय</b><br/>बिहार की परंपराओं और बदलते वर्तमान को हर सप्ताह पढ़ें।</p><Link className="btn primary" to="/blog">नवीन आलेख पढ़ें</Link></div></section>
 </main>}
