import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ChevronDown,MapPin} from 'lucide-react';
import {SEO,Breadcrumbs,RelatedContent} from '../components/Portal';
import {ProfileImage,ProfileReferences} from '../components/personalities/ProfilePrimitives';
import {siteConfig} from '../siteConfig';
import {kunwarSingh as profile,kunwarMediaById as media,kunwarSchema} from '../data/personalities/kunwarSingh.js';
import {kunwarSources,kunwarSourceById as sources,evidenceTypes} from '../data/personalities/kunwarSources.js';
import '../personalities.css';
import '../kunwar-singh.css';

const References=({ids})=><ProfileReferences ids={ids} sources={sources}/>;
const Photograph=({id,hero=false})=><ProfileImage media={media[id]} hero={hero}/>;
function Evidence({type}){const e=evidenceTypes[type];return <span className="ks-evidence" data-evidence={type} title={e.note}>{e.label}<span lang="en">{e.english}</span></span>}
function Claim({item}){return <div className="p1-claim" data-claim={item.id}><Evidence type={item.evidence}/><p>{item.text}</p><References ids={item.sources}/></div>}
function Campaigns(){return <ol className="ks-campaigns" aria-label="अभियान के प्रमुख क्षेत्र और अनुमानित काल">{profile.campaigns.map(e=><li key={e.id}><span className="ks-campaign-date">{e.dateLabel}</span><h3>{e.place}</h3><Evidence type={e.evidence}/><p>{e.text}</p><p className="ks-significance">{e.significance}</p><References ids={e.sources}/></li>)}</ol>}
function Tradition(){return <div className="ks-tradition-grid">{profile.tradition.map(e=><article key={e.id}><h3>{e.title}</h3><Claim item={e}/></article>)}</div>}
function EventDate({event}){return event.date?<time dateTime={event.date}>{event.label}</time>:<span className="ks-event-date">{event.label}</span>}
const periods=[['all','सम्पूर्ण समयरेखा'],['early','प्रारंभिक संदर्भ'],['rebellion','1857'],['campaign','1858 का अभियान'],['legacy','बाद की विरासत']];
function Timeline(){const [period,setPeriod]=useState('all'),[open,setOpen]=useState('birth');const shown=profile.timeline.filter(e=>period==='all'||e.period===period),staticMode=typeof window==='undefined';return <section id="life-timeline" className="p1-section p1-timeline"><div className="p1-section-head"><span className="p1-kicker">जीवन और स्मरण</span><h2>समयरेखा: जगदीशपुर से सार्वजनिक स्मृति तक</h2><p>{staticMode?'सम्पूर्ण समयरेखा; जहाँ दिन या महीना स्थापित नहीं है वहाँ व्यापक अवधि दी गई है।':'कालखंड चुनें और पड़ाव खोलें। एक समय में एक विवरण खुलता है; Enter या Space से भी नियंत्रित करें।'}</p></div>{staticMode?<ol className="p1-milestones">{profile.timeline.map(e=><li key={e.id}><EventDate event={e}/><h3>{e.title}</h3><Claim item={e}/></li>)}</ol>:<><div className="p1-filters" role="group" aria-label="समयरेखा का कालखंड">{periods.map(([id,label])=><button key={id} type="button" aria-pressed={id===period} onClick={()=>{setPeriod(id);setOpen(null)}}>{label}</button>)}</div><p className="p1-count" role="status">{shown.length} पड़ाव दिखाए जा रहे हैं</p><ol className="p1-events">{shown.map(e=><li key={e.id}><h3><button type="button" id={'ks-event-'+e.id} aria-controls={'ks-panel-'+e.id} aria-expanded={open===e.id} onClick={()=>setOpen(open===e.id?null:e.id)}><EventDate event={e}/><span>{e.title}</span><ChevronDown aria-hidden="true"/></button></h3><div id={'ks-panel-'+e.id} hidden={open!==e.id} role="region" aria-labelledby={'ks-event-'+e.id}><Claim item={e}/></div></li>)}</ol></>}</section>}
const groups=[['government','सरकारी, संस्थागत और अभिलेख-संदर्भ','सरकारी परिचय और समकालीन मूल प्रमाण अलग चीजें हैं। अभिलेखागार के लिए नीचे सूची-विवरण की सीमा पढ़ें।'],['secondary','अकादमिक / द्वितीयक स्रोत','शोध और शिक्षण-सामग्री; इनके विश्लेषण को प्रत्यक्षदर्शी बयान न समझें।'],['tradition','मौखिक और सांस्कृतिक परंपरा','सरकारी वेबसाइट पर प्रकाशित लोककथा भी परंपरा की श्रेणी में रहती है।']];
function SourcePanel(){return <section id="sources" className="p1-section p1-sources"><div className="p1-section-head"><span className="p1-kicker">पढ़ें · तुलना करें · प्रमाण पहचानें</span><h2>स्रोत और ऐतिहासिक प्रमाण</h2><p>स्रोत-समीक्षा: <time dateTime={profile.reviewedOn}>1 अक्टूबर 2026</time>। प्रत्येक प्रमुख कथन के साथ प्रमाण-श्रेणी और संदर्भ दिए गए हैं।</p></div><div className="p1-limitations"><h3>संपादकीय सीमाएँ</h3><ul>{profile.limitations.map(s=><li key={s}>{s}</li>)}</ul><Link to="/editorial-policy">संपादकीय नीति पढ़ें</Link></div>{groups.map(([id,title,note])=><div className="ks-source-group" key={id}><h3>{title}</h3><p>{note}</p><ol className="p1-source-list">{kunwarSources.filter(s=>s.group===id).map(s=><li id={'source-'+s.id} key={s.id}><span>{s.publisher}</span><h4><a href={s.url}>{s.title} <ArrowUpRight aria-hidden="true"/></a></h4><p>{s.scope}</p></li>)}</ol></div>)}</section>}

export default function KunwarSinghProfilePage(){return <article className="p1-page ks-page" lang="hi" aria-labelledby="ks-title">
 <SEO title={profile.seo.title} exactTitle description={profile.seo.description} type="article" inferPerson={false} canonicalPath={profile.canonical} image={media['kunwar-engraving'].src} imageAlt={media['kunwar-engraving'].alt} keywords={profile.aliases.join(', ')} schema={kunwarSchema(siteConfig.url)}/>
 <div className="p1-shell"><Breadcrumbs items={[{label:'व्यक्तित्व',to:'/personalities'},{label:profile.nameHindi}]}/>
 <header className="p1-hero"><Photograph id="kunwar-engraving" hero/><div className="p1-hero-copy"><span className="p1-kicker">व्यक्तित्व · इतिहास · लोकस्मृति</span><p className="p1-life-dates">1857 — 1858 · विद्रोह का काल</p><h1 id="ks-title">{profile.nameHindi}</h1><p className="p1-english" lang="en">Veer Kunwar Singh</p><p className="p1-subtitle">{profile.subtitle}</p><p lang="en" className="ks-english-subtitle">A major Bihar-based leader of the 1857 uprising</p><p>{profile.introduction}</p><p className="ks-location"><MapPin aria-hidden="true"/> जगदीशपुर · भोजपुर · बिहार</p><References ids={['culture','tourism']}/><div className="p1-hero-actions"><a href="#early-life">जीवन परिचय देखें <ArrowUpRight aria-hidden="true"/></a><a href="#life-timeline">समयरेखा देखें</a><a href="#jagdishpur-fort">जगदीशपुर से जुड़ी विरासत</a><a href="#sources">स्रोत देखें</a></div></div></header>
 <section className="p1-facts" aria-labelledby="ks-facts-heading"><h2 id="ks-facts-heading">एक नज़र में</h2><dl>{profile.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd><dd><Evidence type={f.evidence}/><References ids={f.sources}/></dd></div>)}</dl></section>
 <details className="ks-evidence-key"><summary>प्रमाण-चिह्न कैसे पढ़ें?</summary><dl>{Object.entries(evidenceTypes).map(([id,e])=><div key={id}><dt><Evidence type={id}/></dt><dd>{e.note}</dd></div>)}</dl></details>
 <div className="p1-reading-layout"><aside className="p1-toc"><nav aria-label="कुँवर सिंह जीवन-परिचय की विषय-सूची"><span className="p1-kicker">इस परिचय में</span><ol>{profile.sections.map(s=><li key={s.id}><a href={'#'+s.id}>{s.title}</a></li>)}</ol><a href="#life-timeline">सम्पूर्ण समयरेखा</a><a href="#places">संबंधित स्थल</a><a href="#related-people">संबंधित व्यक्तित्व</a><a href="#sources">स्रोत और समीक्षा</a></nav></aside><div className="p1-body">{profile.sections.map((s,i)=><section id={s.id} key={s.id} className={'p1-section'+(s.image?' p1-illustrated':'')+(s.kind==='tradition'?' ks-tradition':'')}><div className="p1-section-head"><span className="p1-section-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h2>{s.title}</h2></div><div className="p1-section-content"><div>{s.paragraphs.map(p=><Claim key={p.id} item={p}/>)}</div>{s.image&&<Photograph id={s.image}/>}</div>{s.kind==='campaigns'&&<Campaigns/>}{s.kind==='tradition'&&<Tradition/>}{s.note&&<aside className="ks-disagreement" aria-label="स्रोतों का अंतर"><h3>{profile.evidenceNotes.find(n=>n.id===s.note).title}</h3><Claim item={profile.evidenceNotes.find(n=>n.id===s.note)}/></aside>}{s.links&&<nav className="p1-context-links" aria-label={s.title+' — आगे पढ़ें'}>{s.links.map(([label,to])=><Link key={to} to={to}>{label} <ArrowUpRight aria-hidden="true"/></Link>)}</nav>}{s.externalLinks?.map(([label,id])=><a key={id} className="p1-external-context" href={sources[id].url}>{label} · बाहरी स्रोत <ArrowUpRight aria-hidden="true"/></a>)}</section>)}</div></div>
 <Timeline/>
 <section id="places" className="p1-section"><div className="p1-section-head"><span className="p1-kicker">इतिहास का भूगोल</span><h2>संबंधित स्थल</h2><p>ऐतिहासिक आधार, अभियान और आधुनिक स्मारक अलग प्रकार के संबंध हैं। यहाँ युद्धस्थलों के अनुमानित निर्देशांक नहीं दिए गए हैं।</p></div><div className="p1-places">{profile.places.map(p=><article id={p.id} key={p.id}><div><MapPin aria-hidden="true"/><h3>{p.title}</h3><small>{p.location}</small><p>{p.text}</p><References ids={p.sources}/>{p.to?<Link to={p.to}>संबंधित परिचय पढ़ें <ArrowUpRight aria-hidden="true"/></Link>:<a href={p.mediaId?media[p.mediaId].source:sources[p.sourceId].url}>{p.mediaId?'चित्र और स्थान का मूल स्रोत':'स्थान का स्रोत-विवरण'} <ArrowUpRight aria-hidden="true"/></a>}</div></article>)}</div></section>
 <section id="related-people" className="p1-section"><div className="p1-section-head"><h2>सहयोगी, समकालीन और व्यापक संदर्भ</h2><p>एक ही विद्रोह में नाम आने का अर्थ प्रत्यक्ष सहयोग या अधीनता नहीं है। संबंध की प्रकृति हर कार्ड पर अलग दी गई है।</p></div><div className="p1-people">{profile.relatedPeople.map(p=><article key={p.id}><small>{p.relationship}</small><h3>{p.name}</h3><p>{p.text}</p><References ids={p.sources}/>{p.to?<Link to={p.to}>मौजूदा इतिहास संदर्भ</Link>:<a href={sources[p.sourceId].url}>प्रकाशित स्रोत पढ़ें</a>}</article>)}</div></section>
 <section id="bihar-1857" className="p1-section ks-context"><span className="p1-kicker">व्यक्ति से व्यापक इतिहास तक</span><h2>1857 का बिहार</h2><p>आरा, जगदीशपुर, पटना और दानापुर को साथ पढ़ें। विस्तृत बिहार-अध्याय यहाँ दोहराया नहीं गया है।</p><RelatedContent items={[{title:'1857 का बिहार: क्षेत्रीय प्रतिरोध',to:'/history/1857-bihar',type:'इतिहास'},{title:'कुँवर सिंह का ऐतिहासिक संदर्भ',to:'/history/veer-kunwar-singh',type:'इतिहास'},{title:'भोजपुर: इतिहास और स्थान',to:'/district/bhojpur',type:'जिला'}]}/></section>
 <SourcePanel/>
 <nav className="p1-bottom-nav" aria-label="जीवनी से आगे"><Link to="/personalities">सभी व्यक्तित्व</Link><Link to="/history">बिहार का इतिहास</Link><a href="#ks-title">ऊपर लौटें ↑</a></nav>
 </div></article>}
