import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,BookOpen,ChevronDown,MapPin} from 'lucide-react';
import {SEO,Breadcrumbs} from '../components/Portal';
import {siteConfig} from '../siteConfig';
import {rajendraPrasad as profile,personalitySources,personalitySourceById as sources,personalityMediaById as media,personalitySchema} from '../data/personalities/index.js';
import '../personalities.css';
import {ProfileReferences,ProfileImage} from '../components/personalities/ProfilePrimitives';

function References({ids}){return <ProfileReferences ids={ids} sources={sources}/>}
function Photograph({id,hero=false}){return <ProfileImage media={media[id]} hero={hero}/>}
function Paragraphs({items}){return items.map((p,i)=><div className="p1-claim" key={i}><p>{p.text}</p><References ids={p.sources}/></div>)}
function EventList({events}){return <ol className="p1-milestones">{events.map(e=><li key={e.id}><time dateTime={e.date}>{e.label}</time><h3>{e.title}</h3><p>{e.text}</p><References ids={e.sources}/></li>)}</ol>}
const periods=[['all','सभी पड़ाव'],['early','जीवन और शिक्षा'],['movement','स्वतंत्रता आंदोलन'],['constitution','संविधान सभा'],['presidency','गणराज्य और अंतिम वर्ष']];
function LifeTimeline(){const [period,setPeriod]=useState('all'),[open,setOpen]=useState('birth');const shown=profile.timeline.filter(e=>period==='all'||e.period===period);return <section id="life-timeline" className="p1-section p1-timeline"><div className="p1-section-head"><span className="p1-kicker">जीवन के पड़ाव</span><h2>एक जीवन, बदलता भारत</h2><p>कालखंड चुनें और किसी पड़ाव का विवरण खोलें। एक बार में एक विवरण खुलता है।</p></div><div className="p1-filters" role="group" aria-label="समयरेखा का कालखंड">{periods.map(([id,label])=><button key={id} type="button" aria-pressed={period===id} onClick={()=>{setPeriod(id);setOpen(null)}}>{label}</button>)}</div><p className="p1-count" role="status">{shown.length} पड़ाव दिखाए जा रहे हैं</p><ol className="p1-events">{shown.map(e=><li key={e.id}><h3><button type="button" id={'event-button-'+e.id} aria-expanded={open===e.id} aria-controls={'event-panel-'+e.id} onClick={()=>setOpen(open===e.id?null:e.id)}><time dateTime={e.date}>{e.label}</time><span>{e.title}</span><ChevronDown aria-hidden="true"/></button></h3><div id={'event-panel-'+e.id} role="region" aria-labelledby={'event-button-'+e.id} hidden={open!==e.id}><p>{e.text}</p><References ids={e.sources}/>{e.image&&<Photograph id={e.image}/>}</div></li>)}</ol></section>}
function Extras({kind}){if(kind==='education')return <ol className="p1-education">{profile.education.map(e=><li key={e.label}><strong>{e.label}</strong><p>{e.text}</p><References ids={e.sources}/></li>)}</ol>;
 if(kind==='constitution')return <EventList events={profile.constitutionTimeline}/>;
 if(kind==='terms')return <div className="p1-terms">{profile.terms.map(t=><div key={t.start}><span>{t.label}</span><h3>{t.title}</h3><p>{t.text}</p><References ids={t.sources}/></div>)}</div>;
 if(kind==='books')return <div className="p1-books">{profile.books.map(b=><article key={b.id}><BookOpen aria-hidden="true"/><small>{b.language} · {b.yearLabel}</small><h3>{b.title}</h3><strong>{b.subject}</strong><p>{b.text}</p><References ids={b.sources}/></article>)}</div>;
 if(kind==='award')return <a className="p1-document" href={sources.award.url}><span>मूल दस्तावेज़ · राजपत्र</span><strong>13 मई 1962 · 38-Pres./62</strong><span>भारत रत्न की अधिसूचना पढ़ें <ArrowUpRight aria-hidden="true"/></span></a>;
 if(kind==='presidency')return <div className="p1-photo-pair"><Photograph id="flag-day"/></div>;
 return null;
}
export default function PersonalityProfilePage(){return <article className="p1-page" lang="hi" aria-labelledby="p1-title">
 <SEO title={profile.seo.title} exactTitle description={profile.seo.description} type="article" inferPerson={false} canonicalPath={profile.canonical} image={media.portrait.src} imageAlt={media.portrait.alt} keywords={profile.aliases.join(', ')} schema={personalitySchema(profile,siteConfig.url)}/>
 <div className="p1-shell"><Breadcrumbs items={[{label:'व्यक्तित्व',to:'/personalities'},{label:profile.nameHindi}]}/>
 <header className="p1-hero"><Photograph id="portrait" hero/><div className="p1-hero-copy"><span className="p1-kicker">बिहार के महान व्यक्तित्व</span><p className="p1-life-dates">1884 — 1963</p><h1 id="p1-title">{profile.nameHindi}</h1><p lang="en" className="p1-english">{profile.nameEnglish}</p><p className="p1-subtitle">{profile.subtitle}</p><p>{profile.introduction}</p><dl className="p1-identity"><div><dt>जन्म</dt><dd>3 दिसंबर 1884 · जीरादेई, वर्तमान सीवान</dd></div><div><dt>निधन</dt><dd>28 फरवरी 1963</dd></div><div><dt>पद</dt><dd>भारत के प्रथम राष्ट्रपति · 26 जनवरी 1950 – 13 मई 1962</dd></div></dl><References ids={['president','district']}/><div className="p1-hero-actions"><a href="#life-timeline">जीवन-यात्रा देखें <ArrowUpRight aria-hidden="true"/></a><a href="#sources">स्रोत और अभिलेख</a></div></div></header>
 <section className="p1-facts" aria-labelledby="facts-heading"><h2 id="facts-heading" className="p1-kicker">एक नज़र में</h2><dl>{profile.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd><dd><References ids={f.sources}/></dd></div>)}</dl></section>
 <div className="p1-reading-layout"><aside className="p1-toc"><nav aria-label="जीवनी की विषय-सूची"><span className="p1-kicker">इस जीवन-परिचय में</span><ol>{profile.sections.map(s=><li key={s.id}><a href={'#'+s.id}>{s.title}</a></li>)}</ol><a href="#life-timeline">सम्पूर्ण समयरेखा</a><a href="#places">संबंधित स्थल</a><a href="#sources">स्रोत और समीक्षा</a></nav></aside><div className="p1-body">{profile.sections.map((s,i)=><section id={s.id} key={s.id} className={'p1-section'+(s.image?' p1-illustrated':'')}><div className="p1-section-head"><span className="p1-section-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h2>{s.title}</h2></div><div className="p1-section-content"><div><Paragraphs items={s.paragraphs}/></div>{s.image&&<Photograph id={s.image}/>}</div><Extras kind={s.kind}/>{s.links&&<nav className="p1-context-links" aria-label={s.title+' — आगे पढ़ें'}>{s.links.map(([label,to])=><Link key={to} to={to}>{label} <ArrowUpRight aria-hidden="true"/></Link>)}</nav>}{s.externalLinks?.map(([label,id])=><a className="p1-external-context" key={id} href={sources[id].url}>{label} · बाहरी सरकारी दस्तावेज़</a>)}</section>)}</div></div>
 {typeof window==='undefined'?<section id="life-timeline" className="p1-section"><h2>एक जीवन, बदलता भारत — सम्पूर्ण समयरेखा</h2><EventList events={profile.timeline}/></section>:<LifeTimeline/>}
 <section id="places" className="p1-section"><div className="p1-section-head"><span className="p1-kicker">बिहार से संबंध</span><h2>स्मृति के स्थल</h2><p>जन्मस्थान, कार्यक्षेत्र और संस्थाएँ — अलग प्रकार के संबंध, अलग स्थानीय इतिहास।</p></div><div className="p1-places">{profile.places.map(p=><article id={p.id} key={p.id}>{p.image&&<Photograph id={p.image}/>}<div><MapPin aria-hidden="true"/><h3>{p.title}</h3><p>{p.text}</p>{p.imageGap&&<p className="p1-note">{p.imageGap}</p>}<References ids={p.sources}/><Link to={p.to}>संबंधित परिचय पढ़ें <ArrowUpRight aria-hidden="true"/></Link></div></article>)}</div></section>
 <section id="related-people" className="p1-section"><div className="p1-section-head"><h2>सहयोगी और संस्थागत संबंध</h2><p>ये संबंधित संदर्भ हैं; इस चरण में इनके नए जीवन-परिचय नहीं बनाए गए हैं।</p></div><div className="p1-people">{profile.relatedPeople.map(p=><article key={p.id}><h3>{p.name}</h3><p>{p.relation}</p><References ids={p.sources}/>{p.to?<Link to={p.to}>मौजूदा इतिहास परिचय</Link>:<a href={sources[p.sourceId].url}>मूल संस्थागत संदर्भ</a>}</article>)}</div></section>
 <section id="sources" className="p1-section p1-sources"><div className="p1-section-head"><span className="p1-kicker">पढ़ें · परखें · आगे खोजें</span><h2>स्रोत, अभिलेख और संपादकीय सीमाएँ</h2><p>स्रोत-समीक्षा: <time dateTime={profile.reviewedOn}>30 सितंबर 2026</time>। तिथि-विशेष की कार्यवाही और राजपत्र को संक्षिप्त जीवनियों पर प्राथमिकता दी गई है।</p></div><div className="p1-limitations"><h3>कहाँ और सत्यापन आवश्यक है?</h3><ul>{profile.limitations.map(x=><li key={x}>{x}</li>)}</ul><Link to="/editorial-policy">संपादकीय नीति पढ़ें</Link></div><ol className="p1-source-list">{personalitySources.map(s=><li id={'source-'+s.id} key={s.id}><span>{s.type}</span><h3><a href={s.url}>{s.title} <ArrowUpRight aria-hidden="true"/></a></h3><p>{s.publisher}</p><p>{s.scope}</p></li>)}</ol></section>
 <nav className="p1-bottom-nav" aria-label="जीवनी से आगे"><Link to="/personalities">सभी व्यक्तित्व</Link><Link to="/history/rajendra-prasad">स्वतंत्रता आंदोलन का संदर्भ</Link><a href="#p1-title">ऊपर लौटें ↑</a></nav>
 </div></article>}
