import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {ArrowRight,BookOpen,MapPin,X,Expand,Search} from 'lucide-react';
import {SEO,Breadcrumbs} from '../components/Portal';
import {religionRecords,religionById,religionPageByPath,religionDirectories,faithIds,filterReligion,contentTypes,traditions,regions,claimKinds,claimLabels,sourceById,getClaims,getSourceIds,mediaById,geographyContexts,riverCoverageGaps,reviewedOn} from '../data/religion/index.js';
import {festivalBySlug} from '../data/festivals/index.js';
import {siteConfig} from '../siteConfig';
import '../religion.css';

const name=(x,lang)=>lang==='en'?x.nameEnglish:x.nameHindi;
const t=(value,lang)=>typeof value==='string'?value:value?.[lang]||value?.hi||'';
const local=(url,lang)=>url+(lang==='en'?'?lang=en':'');
function Photo({id,hero=false,onExpand}){const m=mediaById[id];if(!m)return null;return <figure className="c9-photo"><img src={m.src} srcSet={`${m.thumbnail} 640w, ${m.src} ${m.width}w`} sizes={hero?'(max-width: 768px) 92vw, 42vw':'(max-width: 500px) 86vw, 360px'} width={m.width} height={m.height} alt={m.alt} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/>{onExpand&&<button type="button" className="c9-expand" aria-label={`चित्र बड़ा करें / Enlarge: ${m.alt}`} onClick={event=>onExpand(id,event.currentTarget)}><Expand size={18}/></button>}<figcaption>{m.caption}<small><a href={m.source} target="_blank" rel="noreferrer">{m.credit} · Source</a> · <a href={m.licenseUrl} target="_blank" rel="noreferrer">{m.license}</a></small><small>WebP / resized · {m.changes}</small></figcaption></figure>}
function Gallery({ids,lang}){const dialog=useRef(null),trigger=useRef(null),[selected,setSelected]=useState(null);function open(id,button){setSelected(id);trigger.current=button;}useEffect(()=>{if(selected&&!dialog.current.open)dialog.current.showModal();},[selected]);const close=()=>{dialog.current?.close();setSelected(null);trigger.current?.focus();};if(!ids.length)return null;return <section id="gallery"><h2>{lang==='en'?'Documentary photographs':'स्थल-तस्वीरें'}</h2><p>{lang==='en'?'Photographs document what is visible, not the truth of a belief. Captions identify details and viewpoints.':'तस्वीर दृश्य का दस्तावेज है, धार्मिक विश्वास की सत्यता का प्रमाण नहीं। कैप्शन में चित्र का वास्तविक विषय दिया गया है।'}</p><div className="c9-gallery" tabIndex="0" role="region" aria-label={lang==='en'?'Scrollable photograph gallery':'स्क्रॉल करने योग्य चित्र-दीर्घा'}>{ids.map(id=><Photo id={id} key={id} onExpand={open}/>)}</div><dialog ref={dialog} className="c9-dialog" aria-label={lang==='en'?'Enlarged photograph':'बड़ा चित्र'} onCancel={event=>{event.preventDefault();close();}}><button autoFocus type="button" className="c9-dialog-close" onClick={close}><X/>{lang==='en'?'Close':'बंद करें'}</button>{selected&&<Photo id={selected}/>}</dialog></section>}
function Cards({records,lang}){return <div className="c9-grid">{records.map(x=><Link className="c9-card" to={local(x.seo.canonical,lang)} key={x.id}><small>{t(contentTypes[x.type],lang)}</small><h3>{name(x,lang)}</h3><p>{t(x.summary,lang)}</p><span>{lang==='en'?'Read with sources':'स्रोतों के साथ पढ़ें'} <ArrowRight size={18}/></span></Link>)}</div>}
function Claims({x,lang}){const claims=getClaims(x);return claims.length?<section id="evidence"><h2>{lang==='en'?'Meaning, history and evidence':'अर्थ, इतिहास और साक्ष्य'}</h2><div className="c9-claims">{claims.map(item=><article className="c9-claim" key={item.id}><span className="c9-label">{t(claimLabels[item.classification],lang)}</span><p>{t(item.text,lang)}</p><div>{item.sources.map(id=><a key={id} href={sourceById[id].url} target="_blank" rel="noreferrer">{sourceById[id].title} ↗</a>)}</div></article>)}</div></section>:null;}
function Methodology({lang}){return <section id="methodology" className="c9-method"><BookOpen aria-hidden="true"/><h2>{lang==='en'?'Sources and methodology':'स्रोत और पद्धति'}</h2><p>{lang==='en'?'This is a cultural reference, not religious instruction. Tradition, belief, texts, excavated remains and scholarly interpretation answer different questions. A government tourism account can document a tradition without proving a miracle. Archaeological and UNESCO claims use the relevant heritage sources.':'यह सांस्कृतिक परिचय है, धार्मिक निर्देश नहीं। परंपरा, आस्था, ग्रंथ, उत्खनन और शोध अलग प्रश्नों के उत्तर देते हैं। सरकारी पर्यटन-विवरण किसी कथा का प्रलेखन हो सकता है, चमत्कार का प्रमाण नहीं। पुरातत्त्व और यूनेस्को संबंधी दावों के लिए संबंधित विरासत-स्रोत दिए हैं।'}</p><div className="c9-tags">{claimKinds.map(kind=><span key={kind}>{t(claimLabels[kind],lang)}</span>)}</div><p>{lang==='en'?'No generated images. Missing photographs and incomplete documentation are disclosed. Automated checks validate structure and references, not historical truth. Review date records editorial checking, not live site conditions.':'कोई AI चित्र नहीं। अनुपलब्ध तस्वीर और सीमित प्रलेखन स्पष्ट किए गए हैं। स्वचालित जाँच संरचना और संदर्भ जाँचती है, ऐतिहासिक सत्य प्रमाणित नहीं करती। समीक्षा की तारीख वर्तमान स्थल-स्थिति की गारंटी नहीं है।'}</p><Link to="/editorial-policy">{lang==='en'?'Editorial policy':'संपादकीय नीति'}</Link></section>}
function Links({title,items}){return items.length?<section className="c9-links"><h2>{title}</h2><ul>{items.map(({to,label})=><li key={to}><Link to={to}>{label}<ArrowRight size={16}/></Link></li>)}</ul></section>:null;}
function Related({x,lang}){return <>
 <Links title={lang==='en'?'Festival context · C8':'पर्व-संदर्भ · C8'} items={x.festivals.map(festivalBySlug).filter(Boolean).map(f=>({to:f.seo.canonical,label:lang==='en'?f.nameEn:f.nameHi}))}/>
 <Links title={lang==='en'?'Travel and visitor information · Tourism':'यात्रा और आगंतुक जानकारी · पर्यटन'} items={x.tourism.map(id=>({to:`/tourism/${id}`,label:id.replaceAll('-',' ')}))}/>
 <Links title={lang==='en'?'Administrative districts (not sacred-region boundaries)':'प्रशासनिक जिले (धार्मिक क्षेत्र की सीमा नहीं)'} items={x.administrativeDistrict.map(id=>({to:`/district/${id}`,label:id.replaceAll('-',' ')}))}/>
 <Links title={lang==='en'?'History and physical geography':'इतिहास और भौतिक भूगोल'} items={[...x.history.map(to=>({to,label:to.split('/').at(-1).replaceAll('-',' ')})),...x.rivers.map(id=>({to:`/geography/rivers/${id}`,label:`${id} · ${lang==='en'?'hydrology':'जल-विज्ञान'}`}))]}/>
 </>;}
function SacredGeography({lang}){return <section id="sacred-geography"><h2>{lang==='en'?'Sacred geography':'पवित्र भूगोल'}</h2><p>{lang==='en'?'These overlapping religious and cultural settings are not district or division boundaries. Empty coverage means documentation is limited, not that a region has no religious life.':'ये एक-दूसरे से जुड़े धार्मिक और सांस्कृतिक संदर्भ हैं, जिले या प्रमंडल की सीमाएँ नहीं। खाली कवरेज का अर्थ सीमित प्रलेखन है, उस क्षेत्र में धार्मिक जीवन का अभाव नहीं।'}</p><div className="c9-contexts">{geographyContexts.map(x=><article key={x.id}><h3>{t(x.name,lang)}</h3><p>{t(x.note,lang)}</p><ul>{x.places.map(id=><li key={id}><Link to={local(religionById[id].seo.canonical,lang)}>{name(religionById[id],lang)}</Link></li>)}</ul>{x.id==='ang'&&<Link to={local('/religion/bihula-bishahari-tradition',lang)}>{lang==='en'?'Bihula–Bishahari tradition':'बिहुला–विषहरी परंपरा'}</Link>}</article>)}</div></section>}
function Directory({x,lang}){const [params,setParams]=useSearchParams(),query=params.get('q')||'',tradition=params.get('tradition')||'',type=x.filterType||params.get('type')||'',region=params.get('region')||'';const visible=filterReligion({query,tradition,type,region});function update(key,value){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true,preventScrollReset:true});}return <>
 {x.slug==='sacred-places'&&<SacredGeography lang={lang}/>}
 {x.slug==='history'&&<p className="c9-notice">{lang==='en'?'The sequence below is a reading aid. Periods overlap; undated traditions are not assigned invented years.':'नीचे का क्रम पढ़ने में सहायता के लिए है। कालखंड एक-दूसरे से मिलते हैं; अतिथिक परंपराओं के वर्ष नहीं गढ़े गए हैं।'}</p>}
 <section id="browse"><h2>{lang==='en'?'Explore the collection':'संग्रह में खोजें'}</h2><form className="c9-filters" role="search" onSubmit={event=>event.preventDefault()}>
 <label><span>{lang==='en'?'Name or alias':'नाम या अन्य नाम'}</span><span className="c9-input"><Search size={18} aria-hidden="true"/><input value={query} onChange={e=>update('q',e.target.value)} name="q" type="search" placeholder={lang==='en'?'Mahabodhi, Pawapuri…':'महाबोधि, पावापुरी…'}/></span></label>
 {[['tradition',tradition,traditions,lang==='en'?'Tradition':'धार्मिक परंपरा'],...(!x.filterType?[['type',type,contentTypes,lang==='en'?'Content type':'सामग्री का प्रकार']]:[]),['region',region,regions,lang==='en'?'Cultural region':'सांस्कृतिक क्षेत्र']].map(([key,value,options,label])=><label key={key}><span>{label}</span><select name={key} value={value} onChange={e=>update(key,e.target.value)}><option value="">{lang==='en'?'All':'सभी'}</option>{Object.entries(options).map(([id,text])=><option key={id} value={id}>{t(text,lang)}</option>)}</select></label>)}
 <button type="button" onClick={()=>setParams(lang==='en'?{lang:'en'}:{},{replace:true,preventScrollReset:true})}>{lang==='en'?'Reset filters':'फ़िल्टर हटाएँ'}</button></form>
 <p role="status" aria-live="polite" className="c9-results">{visible.length} {lang==='en'?'records':'परिचय'}</p>
 {visible.length?(x.slug==='history'?<ol className="c9-timeline">{visible.map(event=><li key={event.id}><span>{t(event.period,lang)}</span><h3><Link to={local(event.seo.canonical,lang)}>{name(event,lang)}</Link></h3><p>{t(event.summary,lang)}</p></li>)}</ol>:<Cards records={visible} lang={lang}/>):<div className="c9-empty"><h3>{lang==='en'?'No matching records':'इस खोज में कोई परिचय नहीं'}</h3><p>{lang==='en'?'Try another name or reset the filters. Some regions still need documented profiles.':'दूसरा नाम खोजें या फ़िल्टर हटाएँ। कुछ क्षेत्रों के प्रलेखित परिचय अभी तैयार नहीं हैं।'}</p></div>}
 </section>
 {x.slug==='sacred-rivers'&&<section><h2>{lang==='en'?'Further documentation needed':'आगे प्रलेखन आवश्यक'}</h2><p>{lang==='en'?'We have not added unsupported religious profiles for the following rivers. Their physical geography remains available.':'इन नदियों के लिए अप्रमाणित धार्मिक परिचय नहीं जोड़े गए हैं। इनका भौतिक भूगोल उपलब्ध है।'}</p><div className="c9-contexts">{riverCoverageGaps.map(r=><article key={r.slug}><h3>{t(r.name,lang)}</h3><p>{t(r.note,lang)}</p><Link to={`/geography/rivers/${r.slug}`}>{lang==='en'?'Read Geography':'भूगोल पढ़ें'}</Link></article>)}</div></section>}
 <Methodology lang={lang}/>
 </>;}
function Landing({lang}){const dirs=id=>religionDirectories.find(x=>x.slug===id);return <>
 <nav className="c9-section-nav" aria-label={lang==='en'?'Module sections':'मॉड्यूल के खंड'}>{religionDirectories.slice(1).map(x=><Link key={x.slug} to={local(x.seo.canonical,lang)}>{name(x,lang)}</Link>)}</nav>
 <SacredGeography lang={lang}/>
 <section><h2>{lang==='en'?'Major pilgrimage centres':'प्रमुख तीर्थ-केंद्र'}</h2><Cards lang={lang} records={['mahabodhi-temple','vishnupad-temple','pawapuri-jal-mandir','takht-patna-sahib','maner-sharif','padri-ki-haveli'].map(id=>religionById[id])}/></section>
 {faithIds.map(id=>{const f=religionById[id];return <section className="c9-tradition-preview" id={id} key={id}><small>{lang==='en'?'A Bihar-specific reading':'बिहार-विशिष्ट परिचय'}</small><h2><Link to={local(f.seo.canonical,lang)}>{name(f,lang)} <ArrowRight/></Link></h2><p>{t(f.summary,lang)}</p><div className="c9-inline-links">{f.relatedPlaces.slice(0,3).map(place=><Link key={place} to={local(religionById[place].seo.canonical,lang)}>{name(religionById[place],lang)}</Link>)}</div></section>;})}
 {['sacred-rivers','architecture'].map(id=><section key={id}><h2><Link to={local(dirs(id).seo.canonical,lang)}>{name(dirs(id),lang)} <ArrowRight/></Link></h2><p>{t(dirs(id).summary,lang)}</p></section>)}
 <section><h2>{lang==='en'?'Religious festivals · C8':'धार्मिक पर्व · C8'}</h2><p>{lang==='en'?'Festival histories, ritual sequences, calendars and galleries stay in the canonical festival collection.':'पर्व का इतिहास, अनुष्ठान-क्रम, कैलेंडर और चित्र-दीर्घा मूल पर्व-संग्रह में ही हैं।'}</p><Link to="/festivals/religious">{lang==='en'?'Explore festivals':'पर्व और मेले देखें'} <ArrowRight/></Link></section>
 {['pilgrimage','history'].map(id=><section key={id}><h2><Link to={local(dirs(id).seo.canonical,lang)}>{name(dirs(id),lang)} <ArrowRight/></Link></h2><p>{t(dirs(id).summary,lang)}</p></section>)}
 <Gallery ids={['vaishali-pillar','takht-patna-sahib','maner-chhoti-dargah','padri-ki-haveli','pawapuri-jal-mandir','vishnupad-gaya']} lang={lang}/><Methodology lang={lang}/>
 </>;}
function Detail({x,lang}){const related=[...new Set([...x.relatedPlaces,...x.relatedRecords,...(x.architecture||[])])].map(id=>religionById[id]);return <>
 <dl className="c9-facts"><div><dt>{lang==='en'?'Tradition':'परंपरा'}</dt><dd>{x.tradition.map(id=>t(traditions[id],lang)).join(' · ')}</dd></div><div><dt>{lang==='en'?'Religious setting':'धार्मिक क्षेत्र'}</dt><dd>{t(x.religiousRegion,lang)}</dd></div><div><dt>{lang==='en'?'Cultural setting (not a division)':'सांस्कृतिक क्षेत्र (प्रमंडल नहीं)'}</dt><dd>{x.regions.map(id=>t(regions[id],lang)).join(' · ')||'—'}</dd></div><div><dt>{lang==='en'?'Source review':'स्रोत-समीक्षा'}</dt><dd><time dateTime={x.lastVerified}>{x.lastVerified}</time></dd></div></dl>
 {x.communityContext&&<aside className="c9-notice"><b>{lang==='en'?'Documented community / context':'प्रलेखित समुदाय / संदर्भ'}</b><p>{t(x.communityContext,lang)}</p></aside>}
 <nav className="c9-section-nav" aria-label={lang==='en'?'On this page':'इस पृष्ठ पर'}>{getClaims(x).length>0&&<a href="#evidence">{lang==='en'?'Evidence':'प्रमाण'}</a>}{related.length>0&&<a href="#related">{lang==='en'?'Related places and meanings':'स्थल और अर्थ'}</a>}{x.images.length>0&&<a href="#gallery">{lang==='en'?'Photographs':'चित्र'}</a>}<a href="#sources">{lang==='en'?'Sources':'स्रोत'}</a></nav>
 {x.places&&<section><h2>{lang==='en'?'Approximate reading sequence':'सांकेतिक अध्ययन-क्रम'}</h2><p className="c9-notice">{t(x.sequenceNotice,lang)}</p><ol className="c9-timeline">{x.places.map(id=><li key={id}><h3><Link to={local(religionById[id].seo.canonical,lang)}>{name(religionById[id],lang)}</Link></h3><p>{t(religionById[id].summary,lang)}</p></li>)}</ol></section>}
 <div className="c9-reading"><div><Claims x={x} lang={lang}/>{x.type==='place'&&!x.archaeologicalEvidence.length&&<section><h2>{lang==='en'?'Archaeological evidence':'पुरातात्त्विक साक्ष्य'}</h2><p>{lang==='en'?'Documentation is limited. No independently supported archaeological claim is published for this profile. A tourism description alone is not an excavation report.':'प्रलेखन सीमित है। इस परिचय में स्वतंत्र रूप से समर्थित पुरातात्त्विक दावा प्रकाशित नहीं है। केवल पर्यटन-विवरण उत्खनन-रिपोर्ट नहीं है।'}</p></section>}{x.limitations.length>0&&<aside className="c9-notice"><h2>{lang==='en'?'Limits and differing accounts':'सीमाएँ और अलग विवरण'}</h2>{x.limitations.map((note,i)=><p key={i}>{t(note,lang)}</p>)}</aside>}{!x.images.length&&<p className="c9-notice">{lang==='en'?'A site-matched photograph with verified reuse rights is not available in this edition. No substitute image is presented as this place.':'इस संस्करण में सही स्थल की सत्यापित उपयोग-अधिकार वाली तस्वीर उपलब्ध नहीं है। किसी दूसरे स्थल का चित्र इसके नाम से नहीं दिखाया गया है।'}</p>}</div><aside className="c9-related-panel"><Related x={x} lang={lang}/></aside></div>
 {related.length>0&&<section id="related"><h2>{lang==='en'?'Related places and religious context':'संबंधित स्थल और धार्मिक संदर्भ'}</h2><Cards records={related} lang={lang}/></section>}
 <Gallery ids={x.images} lang={lang}/>
 <section id="sources" className="c9-sources"><h2>{lang==='en'?'Sources and attribution':'स्रोत और श्रेय'}</h2><ul>{getSourceIds(x).map(id=><li key={id}><a href={sourceById[id].url} target="_blank" rel="noreferrer">{sourceById[id].title} ↗</a><small>{sourceById[id].type} · {sourceById[id].reviewedOn}</small></li>)}</ul><p>{lang==='en'?'Source review is not a guarantee of current access, services or ritual schedules.':'स्रोत-समीक्षा वर्तमान प्रवेश, सेवाओं या अनुष्ठान की समय-सारणी की गारंटी नहीं है।'}</p></section><Methodology lang={lang}/>
 </>;}
export default function ReligionPage(){const location=useLocation(),[params,setParams]=useSearchParams(),lang=params.get('lang')==='en'?'en':'hi',path=location.pathname.replace(/\/$/,''),x=religionPageByPath(path);if(!x)return <div className="c9-page"><SEO title="धार्मिक परिचय उपलब्ध नहीं" description="इस पते पर कोई प्रकाशित धार्मिक परिचय नहीं है।" canonicalPath={path} noIndex/><h1>यह परिचय उपलब्ध नहीं है</h1><p>No published religion record exists at this address.</p><Link to="/religion">धार्मिक विरासत संग्रह देखें</Link></div>;
 const isLanding=path==='/religion',directory=x.type==='directory',heroId=isLanding?'vaishali-pillar':x.images?.[0],hero=mediaById[heroId],title=t(x.seo.title,lang),description=t(x.seo.description,lang);
 const schema={'@type':directory?'CollectionPage':'Article',name:name(x,lang),headline:directory?undefined:name(x,lang),inLanguage:lang,about:directory?undefined:{'@type':'Thing',name:x.nameEnglish,alternateName:[x.nameHindi,...x.aliases]},citation:directory?undefined:getSourceIds(x).map(id=>sourceById[id].url),dateModified:reviewedOn,url:siteConfig.url+x.seo.canonical};
 return <div className="c9-page" lang={lang}>
 <SEO title={title} description={description} canonicalPath={x.seo.canonical} image={hero?.src||'/assets/bihar-districts-heritage.svg'} type={directory?'website':'article'} schema={schema} lang={lang} noIndex={['q','tradition','type','region'].some(key=>params.has(key))}/>
 <div className="c9-top"><Breadcrumbs lang={lang} items={isLanding?[{label:lang==='en'?'Religious heritage':'धार्मिक विरासत'}]:[{label:lang==='en'?'Religious heritage':'धार्मिक विरासत',to:local('/religion',lang)},{label:name(x,lang)}]}/><fieldset className="c9-language"><legend>{lang==='en'?'Language':'भाषा'}</legend>{[['hi','हिंदी'],['en','English']].map(([id,label])=><button key={id} type="button" lang={id} aria-pressed={lang===id} onClick={()=>{const next=new URLSearchParams(params);id==='en'?next.set('lang','en'):next.delete('lang');setParams(next,{replace:true,preventScrollReset:true});}}>{label}</button>)}</fieldset></div>
 <header className={`c9-hero${hero?' has-photo':''}`}><div><span className="c9-eyebrow">{lang==='en'?'SACRED BIHAR · CONTEXT & EVIDENCE':'आस्था का बिहार · संदर्भ और साक्ष्य'}</span><h1>{name(x,lang)}</h1><p className="c9-other-name" lang={lang==='hi'?'en':'hi'}>{name(x,lang==='hi'?'en':'hi')}</p><p>{t(x.summary,lang)}</p><span className="c9-review"><MapPin size={16}/>{lang==='en'?'Bihar · source-aware cultural reference':'बिहार · स्रोत-सचेत सांस्कृतिक परिचय'}</span></div>{hero&&<Photo id={heroId} hero/>}</header>
 {isLanding?<Landing lang={lang}/>:directory?<Directory key={x.slug} x={x} lang={lang}/>:<Detail key={x.id} x={x} lang={lang}/>}
 </div>;
}
