import {Link} from 'react-router-dom';
import {ArrowRight,BriefcaseBusiness,Building2,ChartNoAxesCombined,Factory,Landmark,MapPin,Plane,Route,Ship,TrainFront,TrendingUp,UsersRound,Warehouse,Zap} from 'lucide-react';
import {Breadcrumbs,ContentSection,InfoGrid,PageHero,SEO,Sources,TagList} from '../Portal';
import {developmentIndicators,districtEconomyRefs,economicConcepts,economicSources,economicStatistics,economicTimeline,economyOverview,employmentConcepts,energyNodes,industrialAreas,industrialClusters,industries,infrastructure,migrationProfile,sectors,urbanEconomies} from '../../data/economy';
import {CurrentOperationalStatus,CurrentProjectStatus,CurrentStatistic} from '../current/CurrentData';

const infraIcons={road:Route,rail:TrainFront,airport:Plane,waterway:Ship,bridge:Landmark,energy:Zap,logistics:Warehouse};

export function DataYearBadge({year,status,source}){return <span className="econ-year">{year}{status&&` · ${status}`}{source&&` · ${source}`}</span>}
export function ProjectStatusBadge({projectId,currentDataRef}){return <CurrentProjectStatus projectId={projectId} recordId={currentDataRef}/>}
export function EconomicDataNote(){return <aside className="econ-note"><ChartNoAxesCombined/><div><b>आँकड़ा पढ़ने से पहले</b><p>Year, unit, price basis और estimate status साथ पढ़ें। Current prices और constant prices अलग questions answer करते हैं; estimate बाद में revise हो सकता है।</p></div></aside>}
export function SourceQualityNote(){return <aside className="econ-note source-quality"><Landmark/><div><b>Source policy</b><p>Official survey, authority या operator source प्राथमिक है। Current projects में status और last-verified date अनिवार्य हैं; news-only claim canonical record नहीं बनता।</p></div></aside>}

export function EconomyHero(){return <PageHero eyebrow="Geography → production → connectivity → development" title="बिहार की अर्थव्यवस्था और विकास भूगोल" description="Agriculture, industry, services, transport, urban centres, employment और development indicators को year-aware, non-partisan framework में समझें।"/>}
export function EconomicSnapshot(){const ids=['gsdp-current-2023-24','pcgsdp-current-2023-24','share-tertiary-2023-24'];return <section className="econ-snapshot" aria-label="Economic snapshot">{ids.map(id=>{const x=economicStatistics.find(v=>v.id===id);return <article key={id}><small>{x.metric}</small><strong>{x.value.toLocaleString('en-IN')} {x.unit}</strong><DataYearBadge year={x.year} status={x.estimateStatus}/></article>})}<CurrentStatistic statisticId="gsdp-current-2023-24"/></section>}
export function SectorCard({item:x}){return <Link className="econ-card" to={x.seo.canonical}><TrendingUp/><small>{x.nameEn}</small><h3>{x.nameHi}</h3><p>{x.summary}</p><TagList items={x.components}/><b>समझें <ArrowRight/></b></Link>}
export function IndustryCard({item:x}){return <Link className="econ-card" to={x.seo.canonical}><Factory/><small>{x.industryType}</small><h3>{x.nameHi}</h3><p>{x.summary}</p><TagList items={x.districts}/><b>Value chain देखें <ArrowRight/></b></Link>}
export function IndustrialClusterCard({item:x}){return <Link className="econ-card cluster-card" to={x.seo.canonical}><MapPin/><small>{x.type}</small><h3>{x.nameHi}</h3><p>{x.summary}</p><p className="boundary-note">{x.boundary}</p></Link>}
export function InfrastructureCard({item:x}){const Icon=infraIcons[x.category]||Building2;return <Link className="econ-card infra-card" to={x.seo.canonical}><Icon/><small>{x.category}</small><h3>{x.nameHi}</h3><p>{x.summary}</p>{x.currentDataRef&&<CurrentOperationalStatus infrastructureId={x.id} recordId={x.currentDataRef}/>}</Link>}
export function UrbanEconomyCard({item:x}){return <article className="urban-card"><Building2/><small>{x.district} district</small><h3>{x.nameHi}</h3><p>{x.summary}</p><TagList items={x.roles}/><p className="boundary-note">{x.boundary}</p><Link to={`/district/${x.district}`}>जिला देखें <ArrowRight/></Link></article>}
export function DevelopmentIndicator({item:x}){return <article className="indicator-card"><h3>{x.metric}</h3><p>{x.interpretation}</p><small><b>सीमा:</b> {x.limitations}</small></article>}

export function SectorShareChart(){const rows=economicStatistics.filter(x=>x.id.startsWith('share-'));return <figure className="sector-chart"><figcaption><b>GSVA sector composition</b><DataYearBadge year="2023–24" status="Quick Estimate" source="constant prices, 2011–12 base"/></figcaption><div aria-hidden="true">{rows.map(x=><span key={x.id} style={{'--share':`${x.value}%`}}><i/>{x.metric.replace('-sector share in GSVA','')} · {x.value}%</span>)}</div><table><caption className="sr-only">Sector share chart data</caption><thead><tr><th>Sector</th><th>Share</th><th>Year</th><th>Price basis</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.metric}</td><td>{x.value} {x.unit}</td><td>{x.year}</td><td>{x.priceBasis}</td></tr>)}</tbody></table><small>Source: {economicSources.survey.title}</small></figure>}
export function EconomicTimeline(){return <ol className="econ-timeline">{economicTimeline.map(x=><li key={x.id}><time>{x.period}</time><div><h3>{x.title}</h3><p>{x.summary}</p></div></li>)}</ol>}

export function EconomicConcepts(){return <main className="economy-page"><SEO title="बिहार की आर्थिक संरचना — GSDP, sectors और price basis" description="GSDP, NSDP, per-capita income, current/constant prices और primary-secondary-tertiary sectors की सरल guide।" canonicalPath="/economy/sectors"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'आर्थिक संरचना'}]}/><PageHero eyebrow="Output measure ≠ household income" title="बिहार की अर्थव्यवस्था की संरचना" description="Economic accounting के basic terms और तीन broad sectors को बिना exam-prep overload के समझें।"/><section className="econ-wrap"><div className="concept-grid">{economicConcepts.map(x=><article key={x.id}><h2>{x.nameHi}</h2><small>{x.nameEn}</small><p>{x.definition}</p><p><b>यह नहीं है:</b> {x.notEquivalent.join(' · ')}</p><em>{x.notes}</em></article>)}</div><EconomicDataNote/><SectorShareChart/><ContentSection title="तीन broad sectors"><div className="econ-grid">{sectors.map(x=><SectorCard key={x.id} item={x}/>)}</div></ContentSection><Sources sources={[economicSources.survey]}/></section></main>}

export function SectorProfile({item:x}){return <main className="economy-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'Sectors',to:'/economy/sectors'},{label:x.nameHi}]}/><PageHero eyebrow={x.nameEn} title={x.nameHi} description={x.summary}/><section className="econ-wrap"><ContentSection title="Bihar context"><p className="econ-lede">{x.biharContext}</p><TagList items={x.components}/></ContentSection><nav className="econ-links">{x.related.map(to=><Link key={to} to={to}>{to.replaceAll('/',' › ')}</Link>)}</nav><Sources sources={x.sources}/></section></main>}

export function IndustryDirectory(){return <main className="economy-page"><SEO title="बिहार के उद्योग — खाद्य प्रसंस्करण, विनिर्माण और औद्योगिक क्षेत्र" description="Bihar food processing, sugar, dairy, textiles, petroleum and local-enterprise geography।" canonicalPath="/economy/industry"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'उद्योग'}]}/><PageHero eyebrow="Industry ≠ one large factory" title="उद्योग, processing और स्थानीय enterprise" description="Factory nodes, small enterprise, construction और agricultural value chains अलग scales पर काम करते हैं।"/><section className="econ-wrap"><div className="econ-grid">{industries.map(x=><IndustryCard key={x.id} item={x}/>)}</div><ContentSection title="MSME और स्थानीय उद्यम"><p>Micro, Small और Medium Enterprises official investment/turnover classification से परिभाषित होते हैं; thresholds समय के साथ बदल सकते हैं, इसलिए यहाँ undated legal limits नहीं दोहराए गए। Food processing, repair, textile, crafts, small manufacturing और services इसके diverse examples हो सकते हैं। Informal work का अर्थ illegal work नहीं है।</p></ContentSection><ContentSection title="Industrial areas — city नहीं"><p>BIADA listing से verified names दिए गए हैं। Industrial area एक managed site/estate है; वह अपने district या city की पूरी economy नहीं है।</p><div className="district-econ-grid">{industrialAreas.map(x=><Link key={x.id} to={`/district/${x.district}`}><b>{x.nameHi}</b><span>{x.location} · {x.dataYear}</span></Link>)}</div></ContentSection><ContentSection title="Industrial geography"><div className="econ-grid">{industrialClusters.map(x=><IndustrialClusterCard key={x.id} item={x}/>)}</div></ContentSection><SourceQualityNote/><Sources sources={[economicSources.industries,economicSources.biada,economicSources.msme]}/></section></main>}

export function IndustryProfile({item:x}){return <main className="economy-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'उद्योग',to:'/economy/industry'},{label:x.nameHi}]}/><PageHero eyebrow={x.industryType} title={x.nameHi} description={x.summary}/><section className="econ-wrap"><InfoGrid items={[[`जिले`,x.districts],['Raw material',x.rawMaterialConnections],['Infrastructure',x.infrastructureConnections],['Economic role',x.economicRole]]}/><ContentSection title="Value chain और geography"><p>{x.currentContext}</p><p>{x.historicalContext}</p></ContentSection>{x.projects.length>0&&<ContentSection title="Dated project status"><div className="energy-grid">{x.projects.map(p=><article key={p.id}><h3>{p.name}</h3><ProjectStatusBadge projectId={p.id} currentDataRef={p.currentDataRef}/><p>{p.summary}</p></article>)}</div></ContentSection>}{x.relatedAgriculture.length>0&&<ContentSection title="Agriculture → processing"><nav className="econ-links">{x.relatedAgriculture.map(id=><Link key={id} to={`/geography/agriculture/${id}`}>{id}</Link>)}</nav></ContentSection>}<ContentSection title="District connections"><nav className="econ-links">{x.relatedDistricts.map(id=><Link key={id} to={`/district/${id}`}>{id}</Link>)}</nav></ContentSection><p className="boundary-note">Food culture अपनी culinary pages में और craft tradition Culture module में canonical रहती है। <Link to="/culture">Culture module देखें</Link></p><Sources sources={x.sources}/></section></main>}

export function ClusterProfile({item:x}){return <main className="economy-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'उद्योग',to:'/economy/industry'},{label:x.nameHi}]}/><PageHero eyebrow={x.type} title={x.nameHi} description={x.summary}/><section className="econ-wrap"><p className="boundary-note">{x.boundary}</p><ContentSection title="Industry relationships"><div className="econ-grid">{x.industryRefs.map(id=>{const item=industries.find(v=>v.id===id);return item&&<IndustryCard key={id} item={item}/>})}</div></ContentSection><nav className="econ-links">{x.districts.map(id=><Link key={id} to={`/district/${id}`}>{id} जिला</Link>)}</nav><Sources sources={x.sources}/></section></main>}

export function TransportNetwork(){const records=infrastructure.filter(x=>['road','rail','airport','waterway','bridge','logistics'].includes(x.category));return <main className="economy-page"><SEO title="बिहार का परिवहन भूगोल — सड़क, रेल, हवाई संपर्क और जलमार्ग" description="Bihar transport networks और economic connectivity की status-aware guide।" canonicalPath="/economy/transport"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'परिवहन'}]}/><PageHero eyebrow="No live traffic, train or flight tracking" title="परिवहन, connectivity और बाजार" description="Road + rail + waterway + airport networks labour mobility, freight और regional markets को जोड़ते हैं—लेकिन infrastructure अकेले development नहीं बनाता।"/><section className="econ-wrap"><div className="econ-grid">{records.map(x=><InfrastructureCard key={x.id} item={x}/>)}</div><ContentSection title="Transport → economy"><div className="network-flow"><span>उत्पादन</span><ArrowRight/><span>भंडारण</span><ArrowRight/><span>Transport</span><ArrowRight/><span>Market / urban centre</span></div><p>Distance के साथ reliability, cost, terminal access, last-mile roads और seasonality भी matter करते हैं।</p></ContentSection><SourceQualityNote/><Sources sources={[economicSources.ecr,economicSources.aai,economicSources.iwai,economicSources.survey]}/></section></main>}

export function InfrastructureDirectory(){return <main className="economy-page"><SEO title="बिहार का बुनियादी ढाँचा — सड़क, रेल, हवाई अड्डे, जलमार्ग और ऊर्जा" description="Source-aware transport, energy and logistics infrastructure guide।" canonicalPath="/economy/infrastructure"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'बुनियादी ढाँचा'}]}/><PageHero eyebrow="Infrastructure is an enabling factor" title="बुनियादी ढाँचा और आर्थिक भूगोल" description="स्थिर infrastructure context और source-backed current status को अलग रखा गया है।"/><section className="econ-wrap"><div className="econ-grid">{infrastructure.map(x=><InfrastructureCard key={x.id} item={x}/>)}</div><ContentSection title="ऊर्जा nodes"><div className="energy-grid">{energyNodes.map(x=><article key={x.id}><Zap/><h3>{x.nameHi}</h3><p>{x.summary}</p><Link to={`/district/${x.district}`}>{x.district} जिला</Link></article>)}</div></ContentSection><p className="boundary-note">More infrastructure ≠ automatically inclusive development. Access, affordability, maintenance, reliability और distribution भी outcomes shape करते हैं।</p><Sources sources={[economicSources.survey,economicSources.ecr,economicSources.aai,economicSources.iwai,economicSources.ntpc]}/></section></main>}

export function InfrastructureProfile({item:x}){const Icon=infraIcons[x.category]||Building2;return <main className="economy-page"><SEO title={x.seo.title} description={x.seo.description} type="article" canonicalPath={x.seo.canonical}/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'Infrastructure',to:'/economy/infrastructure'},{label:x.nameHi}]}/><PageHero eyebrow={x.category} title={x.nameHi} description={x.summary}/><section className="econ-wrap"><div className="infra-profile"><Icon/>{x.currentDataRef&&<CurrentOperationalStatus infrastructureId={x.id} recordId={x.currentDataRef}/>}<p>{x.economicRole}</p><p className="boundary-note">{x.statusNote}</p></div><nav className="econ-links">{x.districts.map(id=><Link key={id} to={`/district/${id}`}>{id} जिला</Link>)}</nav><Sources sources={x.sources}/></section></main>}

export function UrbanEconomy(){return <main className="economy-page"><SEO title="बिहार के शहरी आर्थिक केंद्र — पटना से क्षेत्रीय शहरों तक" description="Patna, Gaya, Muzaffarpur, Bhagalpur, Darbhanga, Bihar Sharif, Purnia और Begusarai की distinct economic roles।" canonicalPath="/economy/urban"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'शहरी अर्थव्यवस्था'}]}/><PageHero eyebrow="Selection ≠ official ranking" title="शहरी आर्थिक केंद्र" description="Administration, services, markets, industry, transport, education और health अलग cities को अलग regional roles देते हैं।"/><section className="econ-wrap"><div className="urban-grid">{urbanEconomies.map(x=><UrbanEconomyCard key={x.id} item={x}/>)}</div><ContentSection title="Urbanization को कैसे पढ़ें"><p>Urban population, urbanization rate, statutory towns और census towns related लेकिन अलग concepts हैं। जहाँ Census 2011 latest full official census reference है, उसे 2026 population नहीं माना गया। Current city populations invent नहीं किए गए।</p><Link className="econ-more" to="/society/urbanization">Census-based urbanization और settlement types देखें <ArrowRight/></Link></ContentSection><Sources sources={[economicSources.census,economicSources.survey]}/></section></main>}

export function EmploymentMigration(){return <main className="economy-page"><SEO title={migrationProfile.seo.title} description={migrationProfile.seo.description} type="article" canonicalPath={migrationProfile.seo.canonical}/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'रोजगार और प्रवासन'}]}/><PageHero eyebrow="Mobility strategy ≠ one failure narrative" title={migrationProfile.nameHi} description={migrationProfile.summary}/><section className="econ-wrap"><div className="concept-grid">{employmentConcepts.map(x=><article key={x.id}><h2>{x.nameHi}</h2><small>{x.nameEn}</small><p>{x.definition}</p><em>{x.limitations}</em></article>)}</div>{migrationProfile.sections.map(([h,p])=><ContentSection key={h} title={h}><p>{p}</p></ContentSection>)}<Link className="econ-more" to="/society/migration">Migration types और Census D-05 context देखें <ArrowRight/></Link><Sources sources={migrationProfile.sources}/></section></main>}

export function DevelopmentPage(){return <main className="economy-page"><SEO title="बिहार का विकास भूगोल — आय, रोजगार, शिक्षा, स्वास्थ्य और connectivity" description="Economic growth, human development और equal distribution के distinctions की indicator guide।" canonicalPath="/economy/development"/><Breadcrumbs items={[{label:'अर्थव्यवस्था',to:'/economy'},{label:'विकास'}]}/><PageHero eyebrow="Growth ≠ human development ≠ equal distribution" title="विकास को कई dimensions में समझें" description="Income useful है, पर education, health, work, infrastructure, access और distribution के बिना development picture अधूरी रहती है।"/><section className="econ-wrap"><div className="indicator-grid">{developmentIndicators.map(x=><DevelopmentIndicator key={x.id} item={x}/>)}</div><ContentSection title="District comparison की सीमा"><p>Different districts को तभी compare किया जा सकता है जब metric, year, source और methodology समान हों। इस module में “best/worst district” ranking नहीं है।</p></ContentSection><ContentSection title="आठ illustrative district economies"><div className="district-econ-grid">{districtEconomyRefs.map(x=><Link key={x.id} to={`/district/${x.district}`}><b>{x.district}</b><span>{x.economicCharacter.replaceAll('-',' · ')}</span></Link>)}</div></ContentSection><Sources sources={[economicSources.survey,economicSources.plfs,economicSources.census]}/></section></main>}

export function EconomyLanding(){return <main className="economy-page"><SEO title="बिहार की अर्थव्यवस्था — कृषि, उद्योग, सेवाएँ और विकास" description="Bihar economy, industry, infrastructure, urban centres, employment, migration and development geography की source-aware guide।" canonicalPath="/economy"/><EconomyHero/><section className="econ-wrap"><p className="econ-lede">{economyOverview.summary}</p><p className="boundary-note">{economyOverview.boundary}</p><EconomicSnapshot/><EconomicDataNote/><ContentSection title="Economic structure"><div className="econ-grid">{sectors.map(x=><SectorCard key={x.id} item={x}/>)}</div><Link className="econ-more" to="/economy/sectors">GSDP, NSDP और price basis समझें <ArrowRight/></Link></ContentSection><ContentSection title="Agriculture → value chain"><p>Farm output raw material बनता है; cleaning, milling, cooling, processing, storage, transport और markets value chain जोड़ते हैं। Crop geography G4 में canonical रहती है।</p><nav className="econ-links"><Link to="/geography/agriculture">कृषि भूगोल</Link><Link to="/economy/food-processing">खाद्य प्रसंस्करण</Link><Link to="/food">Food culture</Link></nav></ContentSection><ContentSection title="Industry और local enterprise"><div className="econ-grid">{industries.slice(0,4).map(x=><IndustryCard key={x.id} item={x}/>)}</div><Link className="econ-more" to="/economy/industry">सभी industries और clusters देखें <ArrowRight/></Link></ContentSection><ContentSection title="Connectivity और infrastructure"><div className="econ-hubs"><Link to="/economy/transport"><TrainFront/>Road, rail, airport, waterway</Link><Link to="/economy/infrastructure"><Zap/>Energy और infrastructure</Link><Link to="/economy/urban"><Building2/>Urban economic centres</Link><Link to="/economy/migration"><UsersRound/>Employment और migration</Link></div></ContentSection><ContentSection title="Tourism, culture, history और ecology"><p>Tourism services, craft livelihoods, industrial history और environmental costs economy से जुड़े हैं, लेकिन उनके canonical narratives अपने modules में रहते हैं।</p><nav className="econ-links"><Link to="/tourism">Tourism</Link><Link to="/culture">Culture and crafts</Link><Link to="/history/modern-bihar">Economic history</Link><Link to="/geography/ecology">Ecology</Link></nav></ContentSection><ContentSection title="Development indicators"><p>Economic output, income, employment, education, health, connectivity और inclusion related dimensions हैं; कोई एक metric complete score नहीं है।</p><Link className="econ-more" to="/economy/development">Development framework देखें <ArrowRight/></Link></ContentSection><ContentSection title="Economic timeline"><EconomicTimeline/></ContentSection><Sources sources={[economicSources.survey,economicSources.industries,economicSources.ecr,economicSources.iwai]}/></section></main>}
