import {Link} from 'react-router-dom';
import {MapPin,ExternalLink,AlertCircle,ArrowRight} from 'lucide-react';
import {SEO,Breadcrumbs,ContentSection,RelatedContent,Sources} from '../Portal';
import {categoryLabels} from '../../data/tourism/index.js';
import {ContinueJourney} from './CircuitDiscovery';

const Grid=({items=[],className=''})=>items.length?<div className={`tourism-grid ${className}`}>{items.map((x,i)=><article key={x.title||x.name||i}><h3>{x.title||x.name}</h3>{x.text&&<p>{x.text}</p>}{x.to&&<Link to={x.to}>और जानें <ArrowRight/></Link>}</article>)}</div>:null;
const Section=({title,children})=>children?<ContentSection title={title}>{children}</ContentSection>:null;
export default function TourismDetailPage({destination:x}){const image=x.hero?.src||'/assets/bihar-hero.png',schemaType=x.categories.includes('museum')?'Museum':x.categories.some(c=>['historical','archaeological','fort','heritage-city'].includes(c))?'TouristAttraction':'Place';const schema={'@type':schemaType,name:x.nameEn||x.nameHi,alternateName:[x.nameHi,...(x.aliases||[])],address:{'@type':'PostalAddress',addressLocality:x.district,addressRegion:'Bihar',addressCountry:'IN'},geo:x.map?.lat?{'@type':'GeoCoordinates',latitude:x.map.lat,longitude:x.map.lng}:undefined};return <main className="tourism-detail">
 <SEO title={x.seo?.title||x.nameHi} description={x.seo?.description||x.summary} type="place" canonicalPath={`/tourism/${x.slug}`} image={image} schema={schema}/><Breadcrumbs items={[{label:'पर्यटन',to:'/tourism'},{label:x.nameHi}]}/>
 <section className={`tourism-hero${x.hero?' has-photo':' fallback'}`} style={x.hero?{'--tourism-image':`url(${x.hero.src})`}:null}><div><div className="tourism-kicker">{x.categories.map(c=><span key={c}>{categoryLabels[c]}</span>)}</div><h1>{x.nameHi}</h1><p>{x.intro}</p><small><MapPin/> {x.district} जिला{x.division?` · ${x.division} प्रमंडल`:''}</small></div></section>
 {x.hero&&<p className="tourism-credit">चित्र: <a href={x.hero.sourceUrl} target="_blank" rel="noreferrer">{x.hero.credit}</a> · {x.hero.license}</p>}
 <div className="tourism-shell"><article><div className="tourism-quick">{x.quickInfo.map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div>
 {x.contentStatus==='basic'&&<div className="tourism-notice"><AlertCircle/><p><b>संक्षिप्त गंतव्य परिचय</b><br/>इस पृष्ठ का गहन शोधित संस्करण आगामी tourism phase में जोड़ा जाएगा। यात्रा से पहले आधिकारिक स्रोत से सत्यापन करें।</p></div>}
 <Section title="एक नज़र में"><p className="tourism-lede">{x.summary}</p>{x.overview?.map((p,i)=><p key={i}>{p}</p>)}</Section><Section title="क्यों जाएँ"><ul className="tourism-checks">{x.whyVisit?.map(v=><li key={v}>{v}</li>)}</ul></Section>{x.faithHistory&&<Section title="आस्था, परंपरा और इतिहास"><div className="faith-history"><article><small>धार्मिक परंपरा</small><p>{x.faithHistory.tradition}</p></article><article><small>ऐतिहासिक / पुरातात्त्विक संदर्भ</small><p>{x.faithHistory.evidence}</p></article></div></Section>}{x.sacredSignificance?.length>0&&<Section title="पवित्र महत्व"><ul>{x.sacredSignificance.map(v=><li key={v}>{v}</li>)}</ul></Section>}{x.sacredGeography&&<Section title="पवित्र भूगोल"><p>{x.sacredGeography.intro}</p><Grid items={x.sacredGeography.items}/></Section>}{x.festivalContext&&<Section title={x.festivalContext.title}><div className="festival-context"><p>{x.festivalContext.text}</p>{x.festivalContext.to&&<Link to={x.festivalContext.to}>Festival module में पढ़ें <ArrowRight/></Link>}</div></Section>}
 <Section title="इतिहास और विरासत">{x.history?.note&&<p className="research-note">{x.history.note}</p>}{x.history?.paragraphs?.map((p,i)=><p key={i}>{p}</p>)}{x.history?.links?.map(l=><Link className="text-link" key={l.to} to={l.to}>{l.label} →</Link>)}</Section><Grid items={x.features}/>{x.monumentInterpretation&&<Section title="स्मारक को कैसे पढ़ें"><dl className="monument-interpretation">{[['कालखंड',x.monumentInterpretation.period],['शैली / प्रकार',x.monumentInterpretation.style],['सामग्री',x.monumentInterpretation.material],['ऐतिहासिक कार्य',x.monumentInterpretation.purpose],['आज क्या बचा है',x.monumentInterpretation.survives],['व्याख्या / पुनर्निर्माण',x.monumentInterpretation.reconstructed]].filter(v=>v[1]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Section>}<Section title="मुख्य आकर्षण"><Grid items={x.highlights}/></Section><Section title="यहाँ क्या अनुभव करें"><ul>{x.experiences?.map(v=><li key={v}>{v}</li>)}</ul></Section>
 {x.monasteries&&<Section title="अंतरराष्ट्रीय मठ"><p>{x.monasteries.intro}</p><div className="tourism-tags">{x.monasteries.items.map(v=><span key={v}>{v}</span>)}</div></Section>}<Section title="कब जाएँ"><Grid items={x.seasons}/>{x.eventContext&&<p className="event-note">{x.eventContext}</p>}</Section><Section title="कैसे पहुँचें"><Grid items={x.connectivity}/>{x.locationNote&&<p className="location-note"><MapPin/>{x.locationNote}</p>}</Section>
 <Section title="स्थानीय संस्कृति और व्यवहार">{x.culture?.map((p,i)=><p key={i}>{p}</p>)}</Section><Section title="स्थानीय स्वाद"><div className="tourism-tags">{x.food?.map(v=>v.to?<Link key={v.name} to={v.to}>{v.name}</Link>:<span key={v.name}>{v.name}</span>)}</div></Section><Section title="आसपास के स्थल"><Grid items={x.nearby}/></Section>
 {x.circuit&&<Section title={x.circuit.name}><div className="circuit-path">{x.circuit.sequence.map((v,i)=><div key={v.name}>{v.to?<Link to={v.to}>{v.name}</Link>:<span>{v.name}</span>}{i<x.circuit.sequence.length-1&&<ArrowRight/>}</div>)}</div></Section>}
 <Section title="जिम्मेदार यात्रा सुझाव"><ul>{x.tips?.map(v=><li key={v}>{v}</li>)}</ul>{x.currentData?.notice&&<p className="tourism-notice inline"><AlertCircle/>{x.currentData.notice}{x.currentData.checkedAt&&<small> जानकारी जाँच: {x.currentData.checkedAt}</small>}</p>}</Section>{x.visitorEtiquette?.length>0&&<Section title="यात्री शिष्टाचार"><ul className="visitor-etiquette">{x.visitorEtiquette.map(v=><li key={v}>{v}</li>)}</ul></Section>}
 {x.gallery?.length>0&&<Section title="चित्र दीर्घा"><div className="tourism-gallery">{x.gallery.map((v,i)=><figure key={i}><img src={v.src} alt={v.alt} loading="lazy"/><figcaption>{v.caption}<small>{v.credit} · {v.license}</small></figcaption></figure>)}</div></Section>}{x.map&&<Section title="मानचित्र"><div className="tourism-map"><MapPin/><div><b>{x.map.label}</b>{x.map.lat&&<small>{x.map.lat}, {x.map.lng}</small>}</div><a href={x.map.externalUrl} target="_blank" rel="noreferrer">OpenStreetMap पर खोलें <ExternalLink/></a></div></Section>}<Sources sources={x.sources}/>
 </article><aside><span>यात्रा सार</span><h2>{x.nameHi}</h2><p>{x.summary}</p>{x.districtSlug&&<Link to={`/district/${x.districtSlug}`}>{x.district} जिला देखें <ArrowRight/></Link>}</aside></div><ContinueJourney destination={x}/><RelatedContent title="इस यात्रा से जुड़ी सामग्री" items={x.related}/></main>}
