const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..'),errors=[],warnings=[];
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),text=read('src/data/economy/index.js');
const data=new Function(`${text.replace(/export const /g,'const ')}\nreturn {economicSources,economicConcepts,sectors,economicStatistics,industries,industrialClusters,industrialAreas,infrastructure,energyNodes,urbanEconomies,districtEconomyRefs,employmentConcepts,migrationProfile,developmentIndicators,economicTimeline,economySearchRecords};`)();
const {economicConcepts,sectors,economicStatistics,industries,industrialClusters,industrialAreas,infrastructure,energyNodes,urbanEconomies,districtEconomyRefs,employmentConcepts,migrationProfile,developmentIndicators,economySearchRecords}=data;
const unique=(xs,label)=>{const seen=new Set();for(const x of xs){if(seen.has(x))errors.push(`duplicate ${label}: ${x}`);seen.add(x)}};
const all=[...sectors,...industries,...industrialClusters,...infrastructure,...urbanEconomies];
unique(all.map(x=>x.id),'global economy id');unique(all.map(x=>x.slug),'global economy slug');unique(economicStatistics.map(x=>x.id),'statistic id');unique(energyNodes.map(x=>x.id),'energy-node id');unique(developmentIndicators.map(x=>x.id),'indicator id');unique(economySearchRecords.map(x=>x.id),'search id');
unique(industrialAreas.map(x=>x.id),'industrial-area id');unique(industrialAreas.map(x=>x.slug),'industrial-area slug');
const sectorIds=new Set(sectors.map(x=>x.id)),industryIds=new Set(industries.map(x=>x.id)),infraIds=new Set(infrastructure.map(x=>x.id));
const districtText=read('src/data/districts/index.js')+read('src/data/districts.js')+fs.readdirSync(path.join(root,'src/data/districts')).filter(x=>x.endsWith('.js')).map(x=>read(`src/data/districts/${x}`)).join('\n');
const districtIds=new Set([...districtText.matchAll(/(?:id|slug):\s*['"]([^'"]+)['"]/g)].map(x=>x[1]));
const agricultureText=read('src/data/geography/agriculture.js'),agricultureIds=new Set([...agricultureText.matchAll(/crop\(\{id:'([^']+)'/g)].map(x=>x[1]));
const validDistrict=(id,owner)=>{if(!districtIds.has(id))errors.push(`${owner}: invalid district ${id}`)};
const validSource=(s,owner)=>{if(!s?.title||!/^https:\/\//.test(s.url||''))errors.push(`${owner}: invalid source`)};
const validSeo=x=>{if(!x.seo?.canonical||!x.seo?.title||!x.seo?.description)errors.push(`${x.id}: missing SEO`)};
for(const x of sectors){if(!x.summary||!x.components?.length)errors.push(`${x.id}: incomplete sector`);if(!x.sources?.length)errors.push(`${x.id}: missing sources`);else x.sources.forEach(s=>validSource(s,x.id));validSeo(x)}
const allowedIndustry=new Set(['food-processing','sugar','dairy','textile','silk','handloom','leather','engineering','chemicals','petroleum','energy','construction-material','pharmaceutical','other-manufacturing']);
for(const x of industries){if(!allowedIndustry.has(x.industryType))errors.push(`${x.id}: invalid industry category ${x.industryType}`);for(const id of x.districts||[])validDistrict(id,x.id);for(const id of x.relatedDistricts||[])validDistrict(id,x.id);for(const id of x.relatedAgriculture||[])if(!agricultureIds.has(id))errors.push(`${x.id}: invalid agriculture ref ${id}`);if(!x.sources?.length)errors.push(`${x.id}: missing sources`);else x.sources.forEach(s=>validSource(s,x.id));validSeo(x);for(const p of x.projects||[])validateProject(p,x.id)}
for(const x of industrialClusters){for(const id of x.industryRefs||[])if(!industryIds.has(id))errors.push(`${x.id}: invalid industry ref ${id}`);for(const id of x.transportRefs||[])if(!infraIds.has(id))errors.push(`${x.id}: invalid infrastructure ref ${id}`);for(const id of x.districts||[])validDistrict(id,x.id);if(!x.sources?.length)errors.push(`${x.id}: missing sources`);else x.sources.forEach(s=>validSource(s,x.id));validSeo(x)}
for(const x of industrialAreas){validDistrict(x.district,x.id);if(!x.dataYear||!x.status)errors.push(`${x.id}: industrial-area status/year missing`);validSource(x.source,x.id)}
for(const x of infrastructure){if(x.currentDataRef&&!/^operational-status-/.test(x.currentDataRef))errors.push(`${x.id}: invalid current-data reference`);for(const id of x.districts||[])validDistrict(id,x.id);if(!x.sources?.length)errors.push(`${x.id}: missing sources`);else x.sources.forEach(s=>validSource(s,x.id));validSeo(x)}
for(const x of energyNodes){validDistrict(x.district,x.id);validSource(x.source,x.id)}
for(const x of urbanEconomies){validDistrict(x.district,x.id);if(!x.sources?.length)errors.push(`${x.id}: missing sources`);else x.sources.forEach(s=>validSource(s,x.id));validSeo(x)}
for(const x of districtEconomyRefs){validDistrict(x.district,x.id);for(const id of x.industryRefs)if(!industryIds.has(id))errors.push(`${x.id}: invalid industry ref ${id}`);validSource(x.source,x.id)}
for(const x of economicStatistics){for(const k of ['metric','value','unit','year','period','geographyLevel','source','sourceUrl'])if(x[k]===undefined||x[k]===null||x[k]==='')errors.push(`${x.id}: statistic missing ${k}`);if(typeof x.value!=='number'||!Number.isFinite(x.value))errors.push(`${x.id}: invalid numeric value`);if(/GSDP|GSVA|per-capita/i.test(x.metric)&&(!x.priceBasis||!x.estimateStatus))errors.push(`${x.id}: missing price basis/estimate status`);if(!/^https:\/\//.test(x.sourceUrl||''))errors.push(`${x.id}: invalid statistic source URL`)}
const shares=economicStatistics.filter(x=>x.id.startsWith('share-'));if(Math.abs(shares.reduce((n,x)=>n+x.value,0)-100)>.01)errors.push('sector shares do not total 100');
function validateProject(p,owner){if(!p.currentDataRef||!/^project-status-/.test(p.currentDataRef))errors.push(`${owner}/${p.id}: missing current-data project reference`)}
const aliasOwners=new Map();for(const x of all)for(const alias of [x.nameEn,...(x.aliases||[])].filter(Boolean)){const key=alias.toLocaleLowerCase('hi').replace(/[^a-z0-9\u0900-\u097f]+/g,'-').replace(/^-|-$/g,'');if(aliasOwners.has(key)&&aliasOwners.get(key)!==x.id)errors.push(`ambiguous economy alias ${alias}`);aliasOwners.set(key,x.id)}
for(const token of ['Economy','अर्थव्यवस्था','Industry','उद्योग','Barauni','बरौनी','Bhagalpur Silk','भागलपुर सिल्क','Food Processing','खाद्य प्रसंस्करण','MSME','Railway','रेल','Airport','National Waterway','राष्ट्रीय जलमार्ग','Migration','प्रवासन','GSDP'])if(!text.includes(token))errors.push(`search regression alias missing: ${token}`);
for(const re of [/fastest growing/i,/poorest/i,/richest/i,/largest/i,/biggest/i,/number one/i,/economic capital/i,/future hub/i,/game changer/i,/world class/i,/revolutionary/i,/सबसे तेज/i,/सबसे गरीब/i,/सबसे अमीर/i,/सबसे बड़ा/i,/आर्थिक राजधानी/i])if(re.test(text))warnings.push(`rank/claim review ${re}`);
for(const re of [/millions migrate/i,/most people migrate/i,/migration is increasing/i,/remittances? (?:are|is) [₹\d]/i,/लाखों लोग प्रवास/i,/सबसे अधिक प्रवासन/i])if(re.test(text))warnings.push(`migration claim review ${re}`);
const ui=read('src/components/economy/EconomyModule.jsx'),routes=read('src/App.jsx'),search=read('src/pages/SearchPage.jsx'),agUi=read('src/components/geography/AgricultureModule.jsx'),districtUi=read('src/components/district/DistrictDetailPage.jsx');
for(const name of ['EconomyHero','EconomicSnapshot','SectorCard','SectorShareChart','IndustryCard','IndustryProfile','IndustrialClusterCard','InfrastructureCard','TransportNetwork','EconomicTimeline','UrbanEconomyCard','DevelopmentIndicator','EconomicDataNote','DataYearBadge','ProjectStatusBadge','SourceQualityNote'])if(!ui.includes(`function ${name}`))errors.push(`missing component ${name}`);
for(const route of ['/economy','/economy/sectors','/economy/industry','/economy/infrastructure','/economy/transport','/economy/urban','/economy/development','/economy/migration','/economy/:slug'])if(!routes.includes(route))errors.push(`missing route ${route}`);
for(const route of ['/geography/agriculture','/food','/culture','/tourism','/history/modern-bihar','/geography/ecology','/district/'])if(!ui.includes(route))errors.push(`missing cross-module link ${route}`);
if(!search.includes('economySearchRecords'))errors.push('global search missing economy index');if(!ui.includes('CurrentProjectStatus')||!ui.includes('CurrentOperationalStatus'))errors.push('Economy UI must render current status through central components');if(!agUi.includes('/economy/food-processing')||!agUi.includes('/economy/sugar-industry'))errors.push('agriculture reciprocal processing links missing');if(!districtUi.includes('to="/economy"'))errors.push('district reciprocal economy link missing');
const media=[...text.matchAll(/media:\s*({[^}]+})/g)];for(const [,m] of media)for(const k of ['src','alt','caption','credit','source','type'])if(!m.includes(k))errors.push(`media metadata missing ${k}`);
if(errors.length){console.error([...new Set(errors)].join('\n'));process.exit(1)}for(const w of [...new Set(warnings)])console.warn(`Warning: ${w}`);
console.log('Economy G5 audit passed');console.log(`Sector profiles: ${sectors.length}`);console.log(`Industry profiles: ${industries.length}`);console.log(`Industrial nodes/clusters: ${industrialClusters.length}`);console.log(`Industrial-area records: ${industrialAreas.length}`);console.log(`Infrastructure records: ${infrastructure.length}`);console.log(`Energy nodes: ${energyNodes.length}`);console.log(`Urban economic profiles: ${urbanEconomies.length}`);console.log(`Development indicators: ${developmentIndicators.length}`);console.log(`District economy refs: ${districtEconomyRefs.length}`);console.log(`Economic statistics: ${economicStatistics.length}`);console.log(`Employment concepts: ${employmentConcepts.length}`);console.log('Duplicate IDs/slugs: 0');console.log('Broken refs: 0');console.log('Missing sources/SEO: 0');console.log('Missing data years/units: 0');console.log('Estimate warnings: 0');console.log('Project-status warnings: 0');console.log(`Ranking warnings: ${warnings.filter(x=>x.startsWith('rank')).length}`);console.log(`Migration warnings: ${warnings.filter(x=>x.startsWith('migration')).length}`);console.log(`Media warnings: ${media.length?0:0}`);
