const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..'),errors=[],warnings=[];
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),text=read('src/data/society/index.js');
const data=new Function(`${text.replace(/export const /g,'const ')}\nreturn {societySources,populationStatistics,demographicConcepts,settlementTypes,urbanProfileRefs,migrationConcepts,educationLevels,educationIndicators,educationIndicatorConcepts,healthSystemLevels,healthIndicators,mortalityConcepts,humanDevelopmentDimensions,districtDemographicRefs,societySections,societySearchRecords};`)();
const {societySources,populationStatistics,demographicConcepts,settlementTypes,urbanProfileRefs,migrationConcepts,educationLevels,educationIndicators,educationIndicatorConcepts,healthSystemLevels,healthIndicators,mortalityConcepts,humanDevelopmentDimensions,districtDemographicRefs,societySections,societySearchRecords}=data;
const unique=(xs,label)=>{const seen=new Set();for(const x of xs){if(seen.has(x))errors.push(`duplicate ${label}: ${x}`);seen.add(x)}};
unique(populationStatistics.map(x=>x.id),'population statistic id');unique(demographicConcepts.map(x=>x.id),'demographic concept id');unique(settlementTypes.map(x=>x.id),'settlement id');unique(urbanProfileRefs.map(x=>x.id),'urban reference id');unique(migrationConcepts.map(x=>x.id),'migration concept id');unique(educationIndicators.map(x=>x.id),'education indicator id');unique(healthIndicators.map(x=>x.id),'health indicator id');unique(societySearchRecords.map(x=>x.id),'search id');
const allowedStatus=new Set(['official-census','official-survey','projection','estimate']);
const validateStat=(x,kind)=>{for(const k of ['metric','value','unit','year','geographyLevel','geographyId','source','sourceUrl','status','notes'])if(x[k]===undefined||x[k]===null||x[k]==='')errors.push(`${kind}/${x.id}: missing ${k}`);if(typeof x.value!=='number'||!Number.isFinite(x.value))errors.push(`${kind}/${x.id}: invalid numeric value`);if(!allowedStatus.has(x.status))errors.push(`${kind}/${x.id}: invalid status ${x.status}`);if(!/^https:\/\//.test(x.sourceUrl||''))errors.push(`${kind}/${x.id}: invalid source URL`);if(x.status==='official-census'&&x.censusYear!==2011)errors.push(`${kind}/${x.id}: Census record missing censusYear 2011`);if(x.status==='projection'&&(!x.projectionYear||!x.methodology))errors.push(`${kind}/${x.id}: projection missing year/methodology`)};
populationStatistics.forEach(x=>validateStat(x,'population'));
for(const x of educationIndicators){validateStat(x,'education');for(const k of ['academicYear','level','definition'])if(!x[k])errors.push(`education/${x.id}: missing ${k}`)}
for(const x of healthIndicators){validateStat(x,'health');if(!x.referencePeriod||!x.definition)errors.push(`health/${x.id}: missing reference period/definition`)}
for(const x of mortalityConcepts){if(!x.unit||!x.referencePeriod||!x.definition)errors.push(`${x.id}: mortality metadata incomplete`)}
if(mortalityConcepts.find(x=>x.id==='imr')?.unit!=='प्रति 1,000 जीवित जन्म')errors.push('IMR unit regression');if(mortalityConcepts.find(x=>x.id==='mmr')?.unit!=='प्रति 100,000 जीवित जन्म')errors.push('MMR unit regression');
for(const [k,s] of Object.entries(societySources)){for(const f of ['title','publisher','url','reportName','edition','referencePeriod','publicationYear'])if(!s[f])errors.push(`source/${k}: missing ${f}`);if(!/^https:\/\//.test(s.url||''))errors.push(`source/${k}: invalid URL`)}
const projections=populationStatistics.filter(x=>x.status==='projection');for(const x of projections)if(!x.projectionYear||!/projection/i.test(`${x.notes} ${x.methodology||''}`))warnings.push(`projection context review ${x.id}`);
const districtFiles=fs.readdirSync(path.join(root,'src/data/districts')).filter(x=>x.endsWith('.js')).map(x=>read(`src/data/districts/${x}`)).join('\n')+read('src/data/districts.js');
for(const x of districtDemographicRefs)if(!districtFiles.includes(`'${x.slug}'`)&&!districtFiles.includes(`slug:"${x.slug}"`))errors.push(`${x.id}: invalid district reference ${x.slug}`);
for(const x of urbanProfileRefs)if(!x.canonicalEconomyRef.startsWith('/economy/urban#'))errors.push(`${x.id}: duplicates/misses G5 urban canonical ref`);
const allProse=`${text} ${read('src/components/society/SocietyModule.jsx')}`;
for(const re of [/current population\s*[:=]\s*[\d,]+/i,/2026 population\s*[:=]\s*[\d,]+/i,/today'?s population\s*[:=]/i])if(re.test(allProse))errors.push(`present-day population claim: ${re}`);
for(const re of [/fastest growing/i,/most developed/i,/least developed/i,/best district/i,/worst district/i,/migration capital/i,/सबसे विकसित/i,/सबसे पिछड़ा/i,/सर्वश्रेष्ठ जिला/i])if(re.test(allProse))warnings.push(`ranking/claim review ${re}`);
for(const re of [/caste-wise profile/i,/religion-wise profile/i,/community intelligence/i,/individual.*(?:caste|religion)/i])if(re.test(allProse))errors.push(`sensitive profiling guard: ${re}`);
for(const re of [/facility count (?:proves|means) quality/i,/schools? count (?:proves|means) quality/i])if(re.test(allProse))errors.push(`infrastructure-quality claim: ${re}`);
for(const token of ['Population','जनसंख्या','density','घनत्व','urbanization','शहरीकरण','literacy','साक्षरता','sex ratio','लिंग अनुपात','migration','प्रवासन','education','शिक्षा','health','स्वास्थ्य','human development','मानव विकास','Census 2011','जनगणना 2011'])if(!text.toLocaleLowerCase('hi').includes(token.toLocaleLowerCase('hi')))errors.push(`search alias missing: ${token}`);
const ui=read('src/components/society/SocietyModule.jsx'),routes=read('src/App.jsx'),search=read('src/pages/SearchPage.jsx'),economyUi=read('src/components/economy/EconomyModule.jsx'),districtUi=read('src/components/district/DistrictDetailPage.jsx');
for(const name of ['DataStatusBadge','CensusDisciplineNote','IndicatorCard','IndicatorGrid','RuralUrbanChart','SocietyLanding','PopulationPage','UrbanizationPage','MigrationPage','EducationPage','HealthPage','HumanDevelopmentPage','DemographicConceptPage'])if(!ui.includes(`function ${name}`))errors.push(`missing component ${name}`);
for(const route of ['/society','/society/population','/society/urbanization','/society/migration','/society/education','/society/health','/society/human-development','/society/:slug'])if(!routes.includes(route))errors.push(`missing route ${route}`);
for(const route of ['/economy','/geography/agriculture','/languages','/history/modern-bihar','/geography','/district/'])if(!ui.includes(route))errors.push(`missing cross-module link ${route}`);
if(!search.includes('societySearchRecords'))errors.push('global search missing society index');if(!economyUi.includes('/society/migration')||!economyUi.includes('/society/urbanization'))errors.push('economy reciprocal society links missing');if(!districtUi.includes('/society/population'))errors.push('district reciprocal population link missing');
const populationDistrictFiles=fs.readdirSync(path.join(root,'src/data/districts')).filter(x=>x.endsWith('.js')).map(x=>({name:x,body:read(`src/data/districts/${x}`)})).filter(x=>/population:/.test(x.body));for(const f of populationDistrictFiles)if(!f.body.includes('जनगणना 2011'))errors.push(`${f.name}: population records lack Census 2011 label`);if(!districtFiles.includes("label:'जनसंख्या',value:")||!districtFiles.includes("dataYear:'जनगणना 2011'"))errors.push('direct district population badge missing');
if(errors.length){console.error([...new Set(errors)].join('\n'));process.exit(1)}for(const w of [...new Set(warnings)])console.warn(`Warning: ${w}`);
console.log('Society G6 audit passed');console.log(`Demographic concepts: ${demographicConcepts.length}`);console.log(`Population statistics: ${populationStatistics.length}`);console.log(`Settlement types: ${settlementTypes.length}`);console.log(`Urban society profiles: ${urbanProfileRefs.length}`);console.log(`Migration concepts: ${migrationConcepts.length}`);console.log(`Education indicators: ${educationIndicators.length}`);console.log(`Education indicator definitions: ${educationIndicatorConcepts.length}`);console.log(`Health indicators: ${healthIndicators.length}`);console.log(`Mortality indicator definitions: ${mortalityConcepts.length}`);console.log(`Human-development dimensions: ${humanDevelopmentDimensions.length}`);console.log(`District society refs: ${districtDemographicRefs.length}`);console.log(`Search records: ${societySearchRecords.length}`);console.log('Duplicate IDs: 0');console.log('Broken references: 0');console.log('Missing statistic metadata: 0');console.log(`Projection warnings: ${projections.length?warnings.filter(x=>x.startsWith('projection')).length:0} (projection records: ${projections.length})`);console.log(`Claim/sensitive-data warnings: ${warnings.filter(x=>!x.startsWith('projection')&&!x.startsWith('district')).length}`);console.log(`District audit warnings: ${warnings.filter(x=>x.startsWith('district')).length}`);
