const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..'),errors=[],warnings=[];
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),text=read('src/data/geography/ecology.js');
const data=new Function(`${text.replace(/export const /g,'const ')}\nreturn {ecosystems,protectedAreas,species,ecologyWetlands,ecologyTopics,ecologySearchRecords};`)();
const {ecosystems,protectedAreas,species,ecologyWetlands}=data,all=[...ecosystems,...protectedAreas,...species,...ecologyWetlands];
const unique=(xs,label)=>{const s=new Set();for(const x of xs){if(s.has(x))errors.push(`duplicate ${label}: ${x}`);s.add(x)}};unique(all.map(x=>x.id),'global ecology id');unique(all.map(x=>x.slug),'global ecology slug');
const ecosystemIds=new Set(ecosystems.map(x=>x.id)),paIds=new Set(protectedAreas.map(x=>x.id)),speciesIds=new Set(species.map(x=>x.id)),wetlandIds=new Set(ecologyWetlands.map(x=>x.id));
const riverText=read('src/data/geography/index.js'),riverIds=new Set([...riverText.matchAll(/(?:deep\(|\[')(?:'|")?([a-z][a-z0-9-]+)(?:'|")/g)].map(x=>x[1]));
const districtText=read('src/data/districts/index.js')+read('src/data/districts.js'),districtIds=new Set([...districtText.matchAll(/slug:\s*['"]([^'"]+)['"]/g)].map(x=>x[1]));
const tourismText=['src/data/tourism.js',...fs.readdirSync(path.join(root,'src/data/tourism')).filter(x=>x.endsWith('.js')).map(x=>`src/data/tourism/${x}`)].map(read).join('\n');
for(const x of ecosystems){for(const id of x.relatedProtectedAreas)if(!paIds.has(id))errors.push(`${x.id}: invalid PA ${id}`);for(const id of x.representativeSpecies)if(!speciesIds.has(id))errors.push(`${x.id}: invalid species ${id}`);for(const id of x.relatedWetlands)if(!wetlandIds.has(id))errors.push(`${x.id}: invalid wetland ${id}`);for(const id of x.relatedRivers)if(!riverText.includes(`'${id}'`))errors.push(`${x.id}: invalid river ${id}`);for(const id of x.relatedTourism)if(!tourismText.includes(`'${id}'`))errors.push(`${x.id}: invalid tourism ${id}`);if(!x.sources?.length||!x.seo?.canonical)errors.push(`${x.id}: missing source/SEO`);validateMap(x.map,x.id)}
for(const x of protectedAreas){if(!x.officialName||!x.designationType)errors.push(`${x.id}: official name/designation missing`);for(const id of x.ecosystemTypes)if(!ecosystemIds.has(id))errors.push(`${x.id}: invalid ecosystem ${id}`);for(const id of x.representativeSpecies)if(!speciesIds.has(id))errors.push(`${x.id}: invalid species ${id}`);for(const id of x.wetlands)if(!wetlandIds.has(id))errors.push(`${x.id}: invalid wetland ${id}`);for(const id of x.districts)if(!districtIds.has(id)&&!districtText.includes(`'${id}'`))errors.push(`${x.id}: invalid district ${id}`);if(!x.area?.unit||!x.area?.source||!x.area?.dataYear)errors.push(`${x.id}: area lacks unit/source/year`);if(!x.sources?.length||!x.seo?.canonical)errors.push(`${x.id}: missing source/SEO`)}
for(const x of species){if(!x.scientificName||!x.group)errors.push(`${x.id}: scientific name/group missing`);for(const id of x.habitats)if(!ecosystemIds.has(id))errors.push(`${x.id}: invalid habitat ${id}`);for(const id of x.protectedAreas)if(!paIds.has(id))errors.push(`${x.id}: invalid PA ${id}`);if(!x.conservationStatus?.source||!x.conservationStatus?.system)errors.push(`${x.id}: conservation status source missing`);if(!x.BiharContext||!x.sources?.length)errors.push(`${x.id}: Bihar evidence/source missing`);if('population' in x||'count' in x){const p=x.population||x.count;if(!p?.year||!p?.source||!p?.surveyContext)errors.push(`${x.id}: population lacks year/source/survey context`)}}
for(const x of ecologyWetlands){if(!ecosystemIds.has(x.ecosystem))errors.push(`${x.id}: invalid ecosystem`);if(x.protectedAreaRef&&!paIds.has(x.protectedAreaRef))errors.push(`${x.id}: invalid PA`);if(!x.sources?.length||!x.seo?.canonical)errors.push(`${x.id}: source/SEO missing`);if(x.recognition&&(!x.recognition.siteNumber||!x.recognition.designationDate||!x.recognition.source?.url.includes('ramsar.org')))errors.push(`${x.id}: invalid Ramsar metadata`)}
const owners=new Map();for(const [kind,list] of [['ecosystem',ecosystems],['pa',protectedAreas],['species',species],['wetland',ecologyWetlands]])for(const x of list)for(const a of x.aliases||[]){const k=`${kind}:${a.toLocaleLowerCase('hi').replace(/[^a-z0-9\u0900-\u097f]+/g,'-')}`;if(owners.has(k)&&owners.get(k)!==x.id)errors.push(`ambiguous alias ${k}`);owners.set(k,x.id)}
for(const key of ['nestCoordinates','denLocation','patrolRoute','cameraTrapCoordinate','breedingCoordinates','poachingHotspot'])if(text.includes(key))errors.push(`sensitive field present: ${key}`);
for(const re of [/largest sanctuary/i,/richest biodiversity/i,/most important wetland/i,/highest tiger density/i,/untouched forest/i,/pristine/i,/hundreds of species/i,/सबसे बड़ा अभयारण्य/i])if(re.test(text))warnings.push(`claim review ${re}`);
const ui=read('src/components/geography/EcologyModule.jsx'),routes=read('src/App.jsx'),search=read('src/pages/SearchPage.jsx');for(const name of ['EcologyHero','EcosystemCard','EcosystemProfile','ProtectedAreaCard','ProtectedAreaProfile','SpeciesCard','SpeciesProfile','HabitatProfile','ConservationNote','EcologyMap','BiodiversitySummary','ThreatsSection','HabitatConnectivity','MigrationContext','SourceQualityNote'])if(!ui.includes(`function ${name}`))errors.push(`missing component ${name}`);
for(const route of ['/geography/ecology','/geography/ecology/ecosystems/:slug','/geography/ecology/protected-areas/:slug','/geography/ecology/species/:slug','/geography/ecology/wetlands/:slug'])if(!routes.includes(route))errors.push(`missing route ${route}`);if(!search.includes('ecologySearchRecords'))errors.push('global search missing ecology index');
for(const token of ['VTR','Gangetic Dolphin','Ganga Dolphin','Kanwar Lake','Kaimur Sanctuary','Terai','Wetland','वाल्मीकि','गंगा डॉल्फिन','आर्द्रभूमि'])if(!text.includes(token))errors.push(`search regression alias missing: ${token}`);
const media=[...text.matchAll(/media:\s*({[^}]+})/g)];for(const [,m] of media)for(const k of ['src','alt','caption','credit','source','type'])if(!m.includes(k))errors.push(`media metadata missing ${k}`);
function validateMap(m,id){if(!m?.mapType||!m?.legend?.length||!m?.accessibleDescription||!m?.source)errors.push(`${id}: invalid map metadata`);if(m?.mapType==='schematic'&&!/सांकेतिक/.test(m.label))errors.push(`${id}: missing schematic label`)}
if(errors.length){console.error([...new Set(errors)].join('\n'));process.exit(1)}for(const w of [...new Set(warnings)])console.warn(`Warning: ${w}`);
console.log('Ecology G3 audit passed');console.log(`Ecosystems: ${ecosystems.length}`);console.log(`Protected areas: ${protectedAreas.length}`);console.log(`Species profiles: ${species.length}`);console.log(`Wetland ecology records: ${ecologyWetlands.length}`);console.log('Duplicate IDs/slugs: 0');console.log('Broken refs: 0');console.log('Species warnings: 0');console.log('Ramsar warnings: 0');console.log('Population-data warnings: 0');console.log('Sensitive-data warnings: 0');console.log(`Media warnings: ${media.length?0:0}`);console.log('Source warnings: 0');console.log('SEO warnings: 0');console.log(`Claim warnings: ${warnings.length}`);
