import {lazy,Suspense,useEffect} from 'react';import {Routes,Route,useLocation} from 'react-router-dom';import {Navbar,Footer} from './components/Layout';
function AnalyticsTracker(){const location=useLocation();useEffect(()=>{if(typeof window.gtag==='function'){window.gtag('event','page_view',{page_path:location.pathname+location.search,page_title:document.title,page_location:window.location.href});}},[location]);return null;}
import './tourism.css';import './culture.css';import './geography.css';
import './economy.css';
import './society.css';
import './society-responsive.css';
import './governance.css';
import './current-data.css';
const Home=lazy(()=>import('./pages/Home'));const SearchPage=lazy(()=>import('./pages/SearchPage'));
const History=lazy(()=>import('./pages/HistoryPages').then(m=>({default:m.History})));const HistoryDetail=lazy(()=>import('./pages/HistoryPages').then(m=>({default:m.HistoryDetail})));const DistrictDirectory=lazy(()=>import('./pages/DistrictPages').then(m=>({default:m.DistrictDirectory})));const DistrictDetail=lazy(()=>import('./pages/DistrictPages').then(m=>({default:m.DistrictDetail})));
const Tourism=lazy(()=>import('./pages/TourismPages').then(m=>({default:m.Tourism})));const TourismDetail=lazy(()=>import('./pages/TourismPages').then(m=>({default:m.TourismDetail})));const TourismCircuit=lazy(()=>import('./pages/TourismPages').then(m=>({default:m.TourismCircuit})));
const Culture=lazy(()=>import('./pages/CulturePages').then(m=>({default:m.Culture})));const CultureDetail=lazy(()=>import('./pages/CulturePages').then(m=>({default:m.CultureDetail})));const Languages=lazy(()=>import('./pages/LanguagePages').then(m=>({default:m.Languages})));const LanguageDetail=lazy(()=>import('./pages/LanguagePages').then(m=>({default:m.LanguageDetail})));const Food=lazy(()=>import('./pages/FoodPages').then(m=>({default:m.Food})));const FoodDetail=lazy(()=>import('./pages/FoodPages').then(m=>({default:m.FoodDetail})));
const Geography=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.Geography})));const Rivers=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.Rivers})));const RiverDetail=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.RiverDetail})));const GeographySystem=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.GeographySystem})));const NaturalRegions=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.NaturalRegions})));const NaturalRegionDetail=lazy(()=>import('./pages/GeographyPages').then(m=>({default:m.NaturalRegionDetail})));
const WaterSystems=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.WaterSystems})));const Groundwater=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.Groundwater})));const Irrigation=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.Irrigation})));const Floodplains=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.Floodplains})));const BasinDetail=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.BasinDetail})));const WetlandDetail=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.WetlandDetail})));const TraditionalDetail=lazy(()=>import('./pages/WaterPages').then(m=>({default:m.TraditionalDetail})));
const Ecology=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.Ecology})));const Ecosystems=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.Ecosystems})));const EcosystemDetail=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.EcosystemDetail})));const ProtectedAreas=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.ProtectedAreas})));const ProtectedAreaDetail=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.ProtectedAreaDetail})));const Species=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.Species})));const SpeciesDetail=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.SpeciesDetail})));const EcologyWetlands=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.EcologyWetlands})));const EcologyWetlandDetail=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.EcologyWetlandDetail})));const Conservation=lazy(()=>import('./pages/EcologyPages').then(m=>({default:m.Conservation})));
const Agriculture=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.Agriculture})));const Crops=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.Crops})));const AgricultureRegions=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.AgricultureRegions})));const AgricultureRegionDetail=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.AgricultureRegionDetail})));const LandUse=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.LandUse})));const CropDetail=lazy(()=>import('./pages/AgriculturePages').then(m=>({default:m.CropDetail})));
const Economy=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.Economy})));const EconomySectors=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomySectors})));const EconomyIndustry=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyIndustry})));const EconomyInfrastructure=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyInfrastructure})));const EconomyTransport=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyTransport})));const EconomyUrban=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyUrban})));const EconomyDevelopment=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyDevelopment})));const EconomyMigration=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyMigration})));const EconomyDetail=lazy(()=>import('./pages/EconomyPages').then(m=>({default:m.EconomyDetail})));
const Society=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.Society})));const SocietyPopulation=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyPopulation})));const SocietyUrbanization=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyUrbanization})));const SocietyMigration=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyMigration})));const SocietyEducation=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyEducation})));const SocietyHealth=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyHealth})));const SocietyHumanDevelopment=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyHumanDevelopment})));const SocietyDetail=lazy(()=>import('./pages/SocietyPages').then(m=>({default:m.SocietyDetail})));
const Governance=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.Governance})));const GovernanceAdministration=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceAdministration})));const GovernanceStateGovernment=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceStateGovernment})));const GovernanceLegislature=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceLegislature})));const GovernanceExecutive=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceExecutive})));const GovernanceJudiciary=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceJudiciary})));const GovernanceLocalGovernment=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceLocalGovernment})));const GovernancePanchayatiRaj=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernancePanchayatiRaj})));const GovernanceUrbanLocalBodies=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceUrbanLocalBodies})));const GovernancePublicServices=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernancePublicServices})));const GovernanceDistrictAdministration=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceDistrictAdministration})));const GovernanceDetail=lazy(()=>import('./pages/GovernancePages').then(m=>({default:m.GovernanceDetail})));
const DataFreshness=lazy(()=>import('./pages/DataFreshnessPage'));
import {Catalog,CatalogDetail} from './pages/CatalogPages';import {Festivals,FestivalDetail} from './pages/FestivalPages';import {TopicPage,Blog,BlogPost} from './pages/InfoPages';
function NotFound(){return <main className="notfound"><b>404</b><h1>यह पृष्ठ उपलब्ध नहीं है</h1><p>संभव है पता बदल गया हो या सामग्री अभी प्रकाशित न हुई हो।</p><a href="/">मुखपृष्ठ पर लौटें</a></main>}
export default function App(){return <><AnalyticsTracker/><Navbar/><div id="main-content"><Suspense fallback={<div className="loading" aria-live="polite">सामग्री खुल रही है…</div>}><Routes>
<Route path="/" element={<Home/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/districts" element={<DistrictDirectory/>}/><Route path="/district/:slug" element={<DistrictDetail/>}/><Route path="/districts/:slug" element={<DistrictDetail/>}/><Route path="/history" element={<History/>}/><Route path="/history/:slug" element={<HistoryDetail/>}/><Route path="/tourism" element={<Tourism/>}/><Route path="/tourism/circuits/:slug" element={<TourismCircuit/>}/><Route path="/tourism/:slug" element={<TourismDetail/>}/>
<Route path="/culture" element={<Culture/>}/><Route path="/culture/festivals" element={<Festivals/>}/><Route path="/culture/festivals/:slug" element={<FestivalDetail/>}/><Route path="/culture/:slug" element={<CultureDetail/>}/><Route path="/food" element={<Food/>}/><Route path="/food/:slug" element={<FoodDetail/>}/><Route path="/languages" element={<Languages/>}/><Route path="/languages/:slug" element={<LanguageDetail/>}/><Route path="/personalities" element={<Catalog type="personalities"/>}/><Route path="/personalities/:slug" element={<CatalogDetail type="personalities"/>}/>
<Route path="/geography" element={<Geography/>}/><Route path="/geography/rivers" element={<Rivers/>}/><Route path="/geography/rivers/:slug" element={<RiverDetail/>}/><Route path="/geography/natural-regions" element={<NaturalRegions/>}/><Route path="/geography/natural-regions/:slug" element={<NaturalRegionDetail/>}/><Route path="/geography/basins" element={<WaterSystems/>}/><Route path="/geography/basins/:slug" element={<BasinDetail/>}/><Route path="/geography/wetlands/:slug" element={<WetlandDetail/>}/><Route path="/geography/water-systems" element={<WaterSystems/>}/><Route path="/geography/water-systems/:slug" element={<TraditionalDetail/>}/><Route path="/geography/groundwater" element={<Groundwater/>}/><Route path="/geography/irrigation" element={<Irrigation/>}/><Route path="/geography/floodplains" element={<Floodplains/>}/>
<Route path="/geography/ecology" element={<Ecology/>}/><Route path="/geography/ecology/ecosystems" element={<Ecosystems/>}/><Route path="/geography/ecology/ecosystems/:slug" element={<EcosystemDetail/>}/><Route path="/geography/ecology/protected-areas" element={<ProtectedAreas/>}/><Route path="/geography/ecology/protected-areas/:slug" element={<ProtectedAreaDetail/>}/><Route path="/geography/ecology/species" element={<Species/>}/><Route path="/geography/ecology/species/:slug" element={<SpeciesDetail/>}/><Route path="/geography/ecology/wetlands" element={<EcologyWetlands/>}/><Route path="/geography/ecology/wetlands/:slug" element={<EcologyWetlandDetail/>}/><Route path="/geography/ecology/conservation" element={<Conservation/>}/>
<Route path="/geography/agriculture" element={<Agriculture/>}/><Route path="/geography/agriculture/crops" element={<Crops/>}/><Route path="/geography/agriculture/regions" element={<AgricultureRegions/>}/><Route path="/geography/agriculture/regions/:slug" element={<AgricultureRegionDetail/>}/><Route path="/geography/agriculture/land-use" element={<LandUse/>}/><Route path="/geography/agriculture/:slug" element={<CropDetail/>}/><Route path="/geography/:slug" element={<GeographySystem/>}/>
<Route path="/education" element={<TopicPage topic="education"/>}/><Route path="/economy" element={<Economy/>}/><Route path="/economy/sectors" element={<EconomySectors/>}/><Route path="/economy/industry" element={<EconomyIndustry/>}/><Route path="/economy/infrastructure" element={<EconomyInfrastructure/>}/><Route path="/economy/transport" element={<EconomyTransport/>}/><Route path="/economy/urban" element={<EconomyUrban/>}/><Route path="/economy/development" element={<EconomyDevelopment/>}/><Route path="/economy/migration" element={<EconomyMigration/>}/><Route path="/economy/:slug" element={<EconomyDetail/>}/><Route path="/society" element={<Society/>}/><Route path="/society/population" element={<SocietyPopulation/>}/><Route path="/society/urbanization" element={<SocietyUrbanization/>}/><Route path="/society/migration" element={<SocietyMigration/>}/><Route path="/society/education" element={<SocietyEducation/>}/><Route path="/society/health" element={<SocietyHealth/>}/><Route path="/society/human-development" element={<SocietyHumanDevelopment/>}/><Route path="/society/:slug" element={<SocietyDetail/>}/>
<Route path="/governance" element={<Governance/>}/><Route path="/governance/administration" element={<GovernanceAdministration/>}/><Route path="/governance/state-government" element={<GovernanceStateGovernment/>}/><Route path="/governance/legislature" element={<GovernanceLegislature/>}/><Route path="/governance/executive" element={<GovernanceExecutive/>}/><Route path="/governance/judiciary" element={<GovernanceJudiciary/>}/><Route path="/governance/local-government" element={<GovernanceLocalGovernment/>}/><Route path="/governance/panchayati-raj" element={<GovernancePanchayatiRaj/>}/><Route path="/governance/urban-local-bodies" element={<GovernanceUrbanLocalBodies/>}/><Route path="/governance/public-services" element={<GovernancePublicServices/>}/><Route path="/governance/district-administration" element={<GovernanceDistrictAdministration/>}/><Route path="/governance/:slug" element={<GovernanceDetail/>}/>
<Route path="/about/data-freshness" element={<DataFreshness/>}/>
<Route path="/politics" element={<TopicPage topic="politics"/>}/><Route path="/blog" element={<Blog/>}/><Route path="/blog/:slug" element={<BlogPost/>}/><Route path="*" element={<NotFound/>}/>
</Routes></Suspense></div><Footer/></>}
