import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import App from './App';
import './styles.css';
import './performance-culture.css';
import './festival.css';
import './language.css';
import './food.css';
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
