import {AlertTriangle,CalendarDays,CheckCircle2,Clock3,ExternalLink,FileWarning,Info,Landmark,ShieldAlert} from 'lucide-react';
import {Link} from 'react-router-dom';
import {currentDataMethodology,currentRecordById,currentRecordsForEntity,getFreshnessState,policyFor} from '../../data/current';

const labels={verified:'सत्यापित', 'due-soon':'सत्यापन शीघ्र आवश्यक',stale:'पुनः सत्यापन आवश्यक',expired:'अवधि समाप्त',scheduled:'निर्धारित',archived:'अभिलेखित',unverified:'सत्यापनाधीन'};
const stateIcon={verified:CheckCircle2,'due-soon':Clock3,stale:AlertTriangle,expired:FileWarning,scheduled:CalendarDays,archived:Info,unverified:ShieldAlert};
const hindiDate=value=>{if(!value)return null;const date=new Date(`${value}T00:00:00Z`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(date)};
const recordFor=(recordId,entityType,entityId,dataType)=>recordId?currentRecordById(recordId):currentRecordsForEntity(entityType,entityId).find(x=>!dataType||x.dataType===dataType);

export function FreshnessBadge({record,referenceDate}){const state=getFreshnessState(record,referenceDate),Icon=stateIcon[state]||Info;return <span className={`freshness-badge freshness-${state}`}><Icon size={14}/>{labels[state]}</span>}
export function LastVerified({record}){return record?.lastVerified?<small className="current-last-verified">अंतिम सत्यापन: {hindiDate(record.lastVerified)}</small>:null}
export function CurrentSource({record}){const source=record?.source;if(!source?.url)return null;return <a className="current-source" href={source.url} target="_blank" rel="noreferrer">स्रोत: {source.title}<ExternalLink size={13}/></a>}

export function CurrentDataCard({record,title,children,referenceDate,showWhenUnavailable=false}){if(!record)return showWhenUnavailable?<CurrentDataNotice compact/>:null;const state=getFreshnessState(record,referenceDate),policy=policyFor(record);if(state==='stale'&&policy?.staleBehavior==='hide')return null;return <aside className={`current-data-card current-state-${state}`} aria-live="polite"><div className="current-data-top"><div><small>वर्तमान जानकारी</small><h3>{title||'सत्यापित स्थिति'}</h3></div><FreshnessBadge record={record} referenceDate={referenceDate}/></div>{children}{state==='stale'&&<p className="current-warning">यह जानकारी पुरानी है; इसे live स्थिति न मानें और आधिकारिक स्रोत से पुनः जाँचें।</p>}{state==='unverified'&&<p className="current-warning">{record.notes||currentDataMethodology.unavailableMessage}</p>}<div className="current-data-meta"><LastVerified record={record}/><CurrentSource record={record}/></div></aside>}

export function CurrentDataNotice({compact=false}){return <aside className={`current-data-notice${compact?' compact':''}`}><Info/><div><b>स्थिर ज्ञान और वर्तमान जानकारी अलग हैं</b><p>पद, समय-सारणी, operational status और administrative counts बदल सकते हैं। केवल स्रोत, अंतिम-सत्यापन और freshness state वाले records को current माना जाता है।</p>{!compact&&<Link to="/about/data-freshness">डेटा freshness नीति देखें <ExternalLink size={13}/></Link>}</div></aside>}
export function StaleDataNotice(){return <aside className="current-data-notice stale"><AlertTriangle/><div><b>पुनः सत्यापन आवश्यक</b><p>दिया गया record अपनी freshness window पार कर चुका है। इसे संदर्भ के रूप में रखें, आज की स्थिति के रूप में नहीं।</p></div></aside>}

export function CurrentOfficeholder({officeId,recordId,referenceDate}){const record=recordFor(recordId,'office',officeId,'officeholder');if(!record)return null;if(getFreshnessState(record,referenceDate)==='unverified')return <CurrentDataCard record={record} title="वर्तमान पदाधिकारी" referenceDate={referenceDate}><p>वर्तमान पदाधिकारी का नाम उपलब्ध नहीं कराया गया है क्योंकि official sources में असंगति है।</p></CurrentDataCard>;return <CurrentDataCard record={record} title="वर्तमान पदाधिकारी" referenceDate={referenceDate}><strong className="current-value">{record.value?.personName}</strong>{record.value?.roleHi&&<p>{record.value.roleHi}</p>}</CurrentDataCard>}
export function CurrentProjectStatus({projectId,recordId,referenceDate}){const record=recordFor(recordId,'project',projectId,'project-status');if(!record)return null;return <CurrentDataCard record={record} title="परियोजना की वर्तमान स्थिति" referenceDate={referenceDate}><strong className="current-value">{record.value?.label||record.value?.status}</strong>{record.value?.milestone&&<p>{record.value.milestone}</p>}</CurrentDataCard>}
export function CurrentEventOccurrence({eventId,recordId,referenceDate}){const record=recordFor(recordId,'event',eventId,'event-date');if(!record)return <CurrentDataCard showWhenUnavailable title="इस वर्ष की तिथि"/>;return <CurrentDataCard record={record} title="आधिकारिक calendar सूचना" referenceDate={referenceDate}><strong className="current-value">{record.value?.label}</strong>{record.value?.startDate&&<p>{hindiDate(record.value.startDate)}{record.value?.endDate&&` – ${hindiDate(record.value.endDate)}`}</p>}<p>{record.notes}</p></CurrentDataCard>}
export function CurrentAdministrativeCount({entityId,recordId,referenceDate}){const record=recordFor(recordId,'administration',entityId,'administrative-count');if(!record)return null;return <CurrentDataCard record={record} title="वर्तमान प्रशासनिक गणना" referenceDate={referenceDate}><strong className="current-value">{record.value?.count} {record.value?.label}</strong></CurrentDataCard>}
export function CurrentStatistic({statisticId,recordId,referenceDate}){const record=recordFor(recordId,'statistic',statisticId,'statistic');if(!record)return null;return <CurrentDataCard record={record} title="नवीनतम उपलब्ध आँकड़ा" referenceDate={referenceDate}><strong className="current-value">{record.value?.value?.toLocaleString?.('en-IN')} {record.value?.unit}</strong><p>{record.value?.label} · {record.value?.period} · {record.value?.estimateStatus}</p></CurrentDataCard>}
export function CurrentOperationalStatus({infrastructureId,recordId,referenceDate}){const record=recordFor(recordId,'infrastructure',infrastructureId,'operational-status');if(!record)return null;return <CurrentDataCard record={record} title="संचालन स्थिति" referenceDate={referenceDate}><strong className="current-value">{record.value?.label||record.value?.status}</strong><p>{record.notes}</p></CurrentDataCard>}
