import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen,Languages as LanguagesIcon,MapPin,ScrollText} from 'lucide-react';
import {SEO,Breadcrumbs,PageHero,ContentSection,InfoGrid,TagList,RelatedContent,Sources} from '../Portal';
import {languageDirectory} from '../../data/languages';

const Cards=({items=[]})=><div className="language-card-grid">{items.map(x=><article key={x.title||x.name}><h3>{x.title||x.name}</h3><p>{x.text||x.role||x.description}</p>{x.to&&<Link to={x.to}>विस्तार से जानें</Link>}</article>)}</div>;
export function LanguageClassificationNote({topic}){return <aside className="classification-note"><LanguagesIcon aria-hidden="true"/><div><h2>भाषिक संदर्भ</h2><p>{topic.linguisticContext}</p><p><b>वर्गीकरण:</b> {topic.subgroup}</p></div></aside>}
export function WriterCard({person}){const body=<><h3>{person.name}</h3><p>{person.role}</p></>;return person.to?<Link className="writer-card" to={person.to}>{body}<span>व्यक्तित्व परिचय →</span></Link>:<article className="writer-card">{body}<small>साहित्यिक संदर्भ; जीवनी नहीं</small></article>}
export function LiteraryTradition({items=[],works=[]}){return <><div className="language-card-grid">{items.map((x,i)=><article key={`${x.genre}-${i}`}><small>{x.period}</small><h3>{x.genre}</h3><p>{x.description}</p>{x.notablePeople?.length>0&&<p><b>रचनाकार:</b> {x.notablePeople.join(' · ')}</p>}</article>)}</div>{works.length>0&&<div className="work-list">{works.map(x=><article key={x.title}><BookOpen/><div><h3>{x.title}</h3><p>{x.author} · {x.language}{x.year?` · ${x.year}`:''} · {x.genre}</p><small>{x.significance}</small></div></article>)}</div>}</>}
export function OralLiteratureSection({items=[]}){return <ContentSection title="लोक साहित्य और मौखिक परंपरा"><p className="boundary-note">मौखिक रचना प्रदर्शन, स्मृति और समुदाय के साथ बदलती है; उसे किसी एक स्थिर मुद्रित पाठ के समान नहीं माना गया है।</p><Cards items={items}/></ContentSection>}
export function RelatedCulture({topic}){const items=[...(topic.relatedMusic||[]),...(topic.relatedTheatre||[]),...(topic.relatedFestivals||[]),...(topic.relatedCulture||[]),...(topic.relatedDistricts||[]),...(topic.relatedHistory||[])];return <RelatedContent title="भाषा से संस्कृति तक" items={items}/>}
export function LanguageProfile({topic}){return <main className="language-page"><SEO title={topic.seo.title} description={topic.seo.description} type="article" canonicalPath={topic.seo.canonical}/><Breadcrumbs items={[{label:'भाषाएँ और साहित्य',to:'/languages'},{label:topic.nameHi}]}/><PageHero eyebrow="भाषा · साहित्य · सांस्कृतिक भूगोल" title={topic.nameHi} description={topic.summary}><div className="language-native" lang={topic.slug==='urdu-bihar'?'ur':'hi'} dir={topic.slug==='urdu-bihar'?'rtl':undefined}>{topic.nativeName}</div></PageHero><div className="language-shell"><article><InfoGrid items={[[`भाषा परिवार`,topic.languageFamily],['सांस्कृतिक क्षेत्र',topic.culturalRegions],['वर्तमान लिपि',topic.currentScripts],['सामग्री स्थिति',topic.contentStatus==='basic'?'प्रारंभिक':'गहन']]}/><p className="map-caution"><MapPin/> भाषा-क्षेत्र सांस्कृतिक भूगोल हैं—आधुनिक जिला सीमाएँ कठोर भाषिक सीमाएँ नहीं।</p><ContentSection title="परिचय और भूगोल">{topic.overview.map(x=><p key={x}>{x}</p>)}<p>{topic.geographicDistribution}</p><TagList items={topic.districtNames}/></ContentSection><LanguageClassificationNote topic={topic}/><ContentSection title="ऐतिहासिक विकास और लिपियाँ">{topic.historicalDevelopment.map(x=><p key={x}>{x}</p>)}<Cards items={topic.scripts}/></ContentSection><OralLiteratureSection items={topic.oralTraditions}/><ContentSection title="लिखित साहित्य"><LiteraryTradition items={topic.literaryTraditions} works={topic.notableWorks}/></ContentSection>{topic.notablePeople.length>0&&<ContentSection title="प्रमुख रचनाकार"><div className="writer-grid">{topic.notablePeople.map(x=><WriterCard key={x.name} person={x}/>)}</div></ContentSection>}<ContentSection title="स्थिति और सावधानियाँ"><p>{topic.statusNotes}</p><p>{topic.constitutionalStatus}</p></ContentSection><Sources sources={topic.sources}/></article><aside className="language-index"><h2>इस पृष्ठ पर</h2><p>भूगोल → वर्गीकरण → लिपि → मौखिक परंपरा → साहित्य → रचनाकार</p><h3>प्रमुख विधाएँ</h3><TagList items={topic.majorGenres}/></aside></div><RelatedCulture topic={topic}/></main>}
export function ScriptProfile({topic}){return <main className="language-page"><SEO title={topic.seo.title} description={topic.seo.description} type="article" canonicalPath={topic.seo.canonical}/><Breadcrumbs items={[{label:'भाषाएँ और साहित्य',to:'/languages'},{label:topic.nameHi}]}/><PageHero eyebrow="ऐतिहासिक लिपि" title={topic.nameHi} description={topic.summary}/><div className="language-shell"><article><InfoGrid items={[[`लेखन दिशा`,topic.writingDirection],['लिपि प्रकार',topic.characterType],['ऐतिहासिक काल',topic.historicalPeriod]]}/><ContentSection title="लिपि, भाषा नहीं"><p>यह एक लेखन प्रणाली है; इसे इससे जुड़ी किसी भाषा का पर्याय नहीं समझना चाहिए। एक लिपि कई भाषाओं के लिए और एक भाषा कई लिपियों में प्रयुक्त हो सकती है।</p><Cards items={topic.associatedLanguages}/></ContentSection><ContentSection title="ऐतिहासिक उपयोग"><p>{topic.historicalUse}</p><p>{topic.manuscriptContext}</p></ContentSection><ContentSection title="संक्रमण और आधुनिक उपयोग"><p>{topic.declineOrTransition}</p><p>{topic.modernUse}</p></ContentSection><Sources sources={topic.sources}/></article><aside className="language-index"><ScrollText/><h2>लिपि संदर्भ</h2><TagList items={topic.relatedRegions}/></aside></div></main>}
export function LanguageDetailPage({topic}){return topic.category==='script'?<ScriptProfile topic={topic}/>:<LanguageProfile topic={topic}/>}
export function LanguageDirectory(){const [query,setQuery]=useState(''),[kind,setKind]=useState('all');const shown=useMemo(()=>languageDirectory.filter(x=>(kind==='all'||x.category===kind)&&`${x.nameHi} ${x.nameEn} ${x.nativeName||''} ${x.summary}`.toLowerCase().includes(query.toLowerCase())),[query,kind]);return <main className="language-directory"><SEO title="बिहार की भाषाएँ, लिपियाँ और साहित्य" description="मैथिली, भोजपुरी, मगही, अंगिका, बज्जिका, सुरजापुरी, उर्दू, हिंदी साहित्य, तिरहुता और कैथी की स्रोत-आधारित निर्देशिका।" canonicalPath="/languages"/><PageHero eyebrow="बहुभाषी बिहार" title="भाषाएँ, लिपियाँ और साहित्य" description="भाषा से सांस्कृतिक क्षेत्र, मौखिक परंपरा, लिपि और साहित्य तक—बिना जिला सीमा, धर्म और भाषिक पहचान को आपस में मिलाए।"/><section className="language-controls" aria-label="भाषा निर्देशिका फ़िल्टर"><label>खोजें<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="मैथिली, कैथी, अज़ीमाबाद…"/></label><div>{[['all','सभी'],['language','भाषाएँ व साहित्य'],['script','लिपियाँ']].map(([v,l])=><button key={v} className={kind===v?'active':''} onClick={()=>setKind(v)}>{l}</button>)}</div></section><p className="map-caution"><MapPin/> यह सांस्कृतिक-भाषिक मार्गदर्शिका है, कठोर भाषा-सीमा मानचित्र नहीं। पड़ोसी क्षेत्रों में बहुभाषिकता सामान्य है।</p><section className="language-directory-grid">{shown.map(x=><Link key={x.slug} to={`/languages/${x.slug}`}><small>{x.category==='script'?'ऐतिहासिक लिपि':x.contentStatus==='basic'?'प्रारंभिक परिचय':'गहन भाषा परिचय'}</small><h2>{x.nameHi}</h2><span>{x.nameEn}{x.nativeName&&x.nativeName!==x.nameHi?` · ${x.nativeName}`:''}</span><p>{x.summary}</p><em>{x.regions.join(' · ')}</em></Link>)}</section>{!shown.length&&<p className="boundary-note">इस खोज से कोई विषय नहीं मिला।</p>}</main>}
export function LanguageLandingPreview(){return <section className="language-preview"><div><small>भाषा और साहित्य</small><h2>बिहार की बहुभाषी दुनिया</h2><p>मैथिली से भोजपुरी, मगही से अंगिका—भाषा, लिपि और साहित्य को उनके सांस्कृतिक भूगोल में समझें।</p></div><Link to="/languages">भाषा निर्देशिका देखें →</Link></section>}
