import {Link} from 'react-router-dom';
import {ArrowDown,ArrowRight,Building2,CheckCircle2,ExternalLink,FileCheck2,Gavel,Landmark,MapPin,Network,Scale,ShieldCheck,UsersRound} from 'lucide-react';
import {Breadcrumbs,ContentSection,PageHero,SEO,Sources} from '../Portal';
import {administrativeLevels,departments,divisions,executiveRecords,governanceComparisons,governanceGlossary,governanceSections,governanceSources,judiciaryRecords,legislatureRecords,offices,publicInstitutions,publicServices,ruralLocalGovernment,urbanLocalGovernment} from '../../data/governance';
import {districts} from '../../data/districts';
import {CurrentAdministrativeCount,CurrentDataNotice as DataFreshnessNotice,CurrentOfficeholder} from '../current/CurrentData';

const sourceValues=keys=>keys.map(key=>governanceSources[key]);
const officeById=id=>offices.find(item=>item.id===id);
const govCrumbs=label=>[{label:'शासन',to:'/governance'},{label}];
const scopeLabel={state:'राज्य',division:'प्रमंडल',district:'जिला',subdivision:'अनुमंडल',block:'प्रखंड','revenue-circle':'अंचल','gram-panchayat':'ग्राम पंचायत','municipal-corporation':'नगर निगम','state-constituency':'विधानसभा क्षेत्र'};

function GovernanceHero({eyebrow='संविधान · संस्थाएँ · प्रशासन',title='बिहार में शासन और सार्वजनिक संस्थाएँ',description='स्थायी कार्यालयों, निर्वाचित संस्थाओं, प्रशासनिक स्तरों और नागरिक सेवाओं की निष्पक्ष, स्रोत-आधारित guide।'}){
 return <PageHero eyebrow={eyebrow} title={title} description={description}/>;
}

export function CurrentDataNotice(){return <DataFreshnessNotice/>}

function CrossModuleLinks(){return <nav className="governance-crosslinks" aria-label="संबंधित ज्ञान मॉड्यूल"><Link to="/districts">38 जिले</Link><Link to="/society/urbanization">समाज और शहरीकरण</Link><Link to="/economy/development">विकास भूगोल</Link><Link to="/geography">भूगोल</Link><Link to="/history/modern-bihar">आधुनिक इतिहास</Link></nav>}

function SectionDirectory(){const icons={administration:Network,'state-government':Landmark,legislature:Building2,executive:UsersRound,judiciary:Scale,'local-government':MapPin,'panchayati-raj':UsersRound,'urban-local-bodies':Building2,'district-administration':FileCheck2,'public-services':CheckCircle2};return <div className="governance-directory">{governanceSections.map(item=>{const Icon=icons[item.id];return <Link to={item.to} key={item.id}><Icon/><small>{item.nameEn}</small><h2>{item.nameHi}</h2><span>समझें <ArrowRight/></span></Link>})}</div>}

export function AdministrativeHierarchy({compact=false}){const trunk=[['राज्य','State'],['प्रमंडल','Division'],['जिला','District']];return <figure className={`governance-hierarchy ${compact?'is-compact':''}`}><figcaption><b>प्रशासन और स्थानीय शासन—एक ही सीधी सीढ़ी नहीं</b><span>जिला स्तर के बाद rural और urban contexts अलग पढ़ें</span></figcaption><div className="hierarchy-trunk">{trunk.map((item,index)=><div key={item[1]}><article><small>{item[1]}</small><strong>{item[0]}</strong></article>{index<trunk.length-1&&<ArrowDown aria-hidden="true"/>}</div>)}</div><div className="hierarchy-branches"><article><small>जिला प्रशासन · ग्रामीण context</small><b>अनुमंडल → प्रखंड → ग्राम पंचायत → गाँव</b><p>अंचल/सर्किल revenue branch है; वह प्रखंड का दूसरा नाम नहीं।</p></article><article><small>शहरी स्थानीय शासन</small><b>नगर निकाय → नगरपालिका वार्ड</b><p>नगर निकाय जिला प्रशासन के भीतर दिख सकता है, पर निर्वाचित municipal institution की अपनी legal identity है।</p></article></div><p className="hierarchy-alt">पाठ रूप: बिहार राज्य में 9 प्रमंडल और 38 जिले हैं। जिले के नीचे अनुमंडल आता है। ग्रामीण प्रशासन में प्रखंड, अंचल, ग्राम पंचायत और गाँव के अलग अर्थ हैं; शहरी स्थानीय शासन नगर निकाय और ward में संगठित होता है।</p></figure>}

function ComparisonGrid({ids}){const shown=ids?governanceComparisons.filter(item=>ids.includes(item.id)):governanceComparisons;return <div className="governance-comparisons">{shown.map(item=><article key={item.id}><h3>{item.title}</h3><p>{item.explanation}</p></article>)}</div>}

function OfficeCards({ids}){const shown=ids.map(officeById).filter(Boolean);return <div className="governance-office-grid">{shown.map(item=><article key={item.id}><div><small>{item.nameEn}</small><span>{scopeLabel[item.level]||item.level}</span></div><h3>{item.nameHi}</h3><p>{item.description}</p>{['governor','chief-minister'].includes(item.id)&&<CurrentOfficeholder officeId={item.id}/>}<ul>{item.coreFunctions.map(fn=><li key={fn}>{fn}</li>)}</ul><Link to={item.seo.canonical}>स्थायी office profile <ArrowRight/></Link></article>)}</div>}

function BranchCards(){return <div className="governance-branches"><article><Landmark/><small>LAWMAKING</small><h2>विधायिका</h2><p>विधान सभा और विधान परिषद से बना द्विसदनीय विधानमंडल। यह कार्यपालिका या न्यायपालिका का विभाग नहीं।</p><Link to="/governance/legislature">दोनों सदन समझें</Link></article><article><UsersRound/><small>ADMINISTRATION</small><h2>कार्यपालिका</h2><p>Political executive और permanent civil administration की अलग भूमिकाएँ, constitutional framework के भीतर।</p><Link to="/governance/executive">संरचना समझें</Link></article><article><Scale/><small>JUSTICE</small><h2>न्यायपालिका</h2><p>पटना उच्च न्यायालय और district judiciary—संस्थागत रूप से स्वतंत्र judicial branch।</p><Link to="/governance/judiciary">न्यायिक संरचना समझें</Link></article></div>}

function InstitutionCards(){return <div className="institution-grid">{publicInstitutions.map(item=><article key={item.id}><small>{item.institutionType.replaceAll('-',' ')}</small><h3>{item.nameHi}</h3><p>{item.mandate}</p><a href={item.sources[0].url} target="_blank" rel="noreferrer">आधिकारिक वेबसाइट <ExternalLink/></a></article>)}</div>}

export function GovernanceLanding(){return <main className="governance-page"><SEO title="बिहार शासन और प्रशासन" description="Bihar governance, administrative hierarchy, Legislature, Executive, Judiciary, local government and public institutions की non-partisan guide।" canonicalPath="/governance"/><GovernanceHero/><section className="governance-wrap"><CurrentDataNotice/><ContentSection title="प्रशासनिक संरचना"><AdministrativeHierarchy compact/><div className="governance-counts"><span><strong>9</strong> प्रमंडल</span><span><strong>38</strong> जिले</span><small>स्थिर canonical geography · बदलती counts अलग data layer में</small></div><div className="governance-current-counts"><CurrentAdministrativeCount entityId="subdivisions"/><CurrentAdministrativeCount entityId="blocks"/></div></ContentSection><ContentSection title="शासन की तीन संस्थागत शाखाएँ"><BranchCards/></ContentSection><ContentSection title="विषय directory"><SectionDirectory/></ContentSection><ContentSection title="स्वतंत्र और वैधानिक सार्वजनिक संस्थाएँ"><InstitutionCards/></ContentSection><ContentSection title="शब्दकोश"><div className="governance-glossary">{governanceGlossary.map(item=><span key={item.id}><b>{item.nameHi}</b><small>{item.nameEn}</small></span>)}</div></ContentSection><ContentSection title="दूसरे modules से संबंध"><CrossModuleLinks/></ContentSection><Sources sources={sourceValues(['constitution','administration','assembly','council','highCourt','panchayatAct','municipalAct'])}/></section></main>}

export function AdministrationPage(){return <main className="governance-page"><SEO title="बिहार की प्रशासनिक संरचना — 9 प्रमंडल और 38 जिले" description="State, division, district, subdivision, block, circle, Panchayat and urban local body की स्पष्ट hierarchy।" canonicalPath="/governance/administration"/><Breadcrumbs items={govCrumbs('प्रशासनिक संरचना')}/><GovernanceHero eyebrow="9 प्रमंडल · 38 जिले · verified structure" title="बिहार की प्रशासनिक संरचना" description="कौन-सा स्तर किसके ऊपर या नीचे है—और किन समान दिखने वाले शब्दों को अलग रखना चाहिए।"/><section className="governance-wrap"><AdministrativeHierarchy/><ContentSection title="हर प्रशासनिक स्तर का अर्थ"><div className="administration-level-grid">{administrativeLevels.map(item=><article key={item.id}><small>{item.nameEn}</small><h3>{item.nameHi}</h3><p>{item.description}</p><b>{item.principalAdministrativeRole}</b><Link to={item.seo.canonical}>विस्तृत परिभाषा</Link></article>)}</div></ContentSection><ContentSection title="नौ प्रमंडल और उनके 38 जिले"><p className="governance-boundary">यह सूची canonical district registry से बनती है—district names governance module में duplicate नहीं किए गए। प्रमंडल मुख्यालय शहर, प्रमंडल स्वयं और उसी नाम का जिला तीन अलग entities हो सकते हैं।</p><div className="division-grid">{divisions.map(item=><article key={item.id}><header><span>{item.nameEn}</span><h3>{item.nameHi}</h3><small>मुख्यालय: {item.headquarters}</small></header><nav aria-label={`${item.nameHi} के जिले`}>{item.districtIds.map(id=>{const d=districts.find(x=>x.slug===id);return <Link key={id} to={`/district/${id}`}>{d?.nameHindi||id}</Link>})}</nav></article>)}</div></ContentSection><ContentSection title="जरूरी अंतर"><ComparisonGrid ids={['division-subdivision','district-headquarters','block-circle','village-panchayat','region-division']}/></ContentSection><Sources sources={sourceValues(['administration','gad','revenue','panchayat','urban'])}/></section></main>}

export function StateGovernmentPage(){return <main className="governance-page"><SEO title="बिहार राज्य सरकार — संवैधानिक और प्रशासनिक ढाँचा" description="Governor, Chief Minister, Council of Ministers, Chief Secretary, Secretariat and department directory without current officeholder names।" canonicalPath="/governance/state-government"/><Breadcrumbs items={govCrumbs('राज्य सरकार')}/><GovernanceHero eyebrow="Office ≠ officeholder" title="बिहार राज्य सरकार" description="संवैधानिक offices, political executive और permanent administrative machinery को व्यक्ति या दल से अलग समझें।"/><section className="governance-wrap"><CurrentDataNotice/><ContentSection title="प्रमुख स्थायी offices"><OfficeCards ids={['governor','chief-minister','chief-secretary']}/></ContentSection><ContentSection title="Council of Ministers और Secretariat"><div className="governance-duo"><article><h3>मंत्रिपरिषद</h3><p>मुख्यमंत्री के नेतृत्व में political executive; वर्तमान मंत्रियों की सूची, party composition और portfolio changes G8 के stable dataset में शामिल नहीं हैं।</p></article><article><h3>राज्य सचिवालय</h3><p>Departments के policy support, coordination और administration का institutional system; यह विधानमंडल सचिवालय या न्यायालय नहीं है।</p></article></div></ContentSection><ContentSection title="विभाग directory"><p className="governance-boundary">विभागों के नाम और allocation बदल सकते हैं। नीचे titles 13 सितंबर 2026 को official portals से सत्यापित हैं; mandate का exact current version official site पर देखें।</p><div className="department-grid">{departments.map(item=><a key={item.id} href={item.officialUrl} target="_blank" rel="noreferrer"><small>{item.category}</small><b>{item.nameHi}</b><span>{item.nameEn}</span><em>सत्यापित {item.lastVerified} <ExternalLink/></em></a>)}</div></ContentSection><Sources sources={sourceValues(['constitution','gad'])}/></section></main>}

export function LegislaturePage(){return <main className="governance-page"><SEO title="बिहार विधानमंडल — विधान सभा और विधान परिषद" description="Bihar bicameral Legislature, Assembly, Council, MLA and MLC roles की neutral institutional guide।" canonicalPath="/governance/legislature"/><Breadcrumbs items={govCrumbs('विधानमंडल')}/><GovernanceHero eyebrow="Bicameral Legislature" title="विधान सभा और विधान परिषद" description="दो सदन, अलग composition और term structures—दलगत या वर्तमान सदस्य सूची के बिना।"/><section className="governance-wrap"><div className="legislature-grid">{legislatureRecords.slice(1).map(item=><article id={item.id==='legislative-assembly'?'assembly':'council'} key={item.id}><small>{item.houseType}</small><h2>{item.nameHi}</h2><strong>{item.stableSeatCount} स्थान</strong><span>{item.countAsOf}</span><dl><div><dt>चयन</dt><dd>{item.directElection}</dd></div><div><dt>संरचना</dt><dd>{item.compositionConcept}</dd></div><div><dt>भूमिका</dt><dd>{item.role}</dd></div></dl></article>)}</div><ContentSection title="MLA और MLC के offices"><OfficeCards ids={['speaker','mla','mlc']}/></ContentSection><ContentSection title="चार जरूरी अंतर"><ComparisonGrid ids={['assembly-council','mp-mla','constituency-district','court-department']}/></ContentSection><CurrentDataNotice/><Sources sources={sourceValues(['constitution','assembly','council','eci'])}/></section></main>}

export function ExecutivePage(){return <main className="governance-page"><SEO title="बिहार की कार्यपालिका — political और permanent executive" description="State political executive, civil administration, Secretariat and field offices की institutional guide।" canonicalPath="/governance/executive"/><Breadcrumbs items={govCrumbs('कार्यपालिका')}/><GovernanceHero eyebrow="Political leadership · administrative continuity" title="राज्य कार्यपालिका" description="नीति-नेतृत्व और permanent civil administration अलग हैं, पर constitutional government में coordinated रूप से काम करते हैं।"/><section className="governance-wrap"><div className="executive-grid">{executiveRecords.map(item=><article key={item.id}><small>{item.type.replaceAll('-',' ')}</small><h2>{item.nameHi}</h2><p>{item.summary}</p></article>)}</div><ContentSection title="राज्य से field administration तक"><OfficeCards ids={['governor','chief-minister','chief-secretary','divisional-commissioner','district-magistrate','sub-divisional-officer']}/></ContentSection><CurrentDataNotice/><Sources sources={sourceValues(['constitution','gad'])}/></section></main>}

export function JudiciaryPage(){return <main className="governance-page"><SEO title="बिहार की न्यायपालिका — पटना उच्च न्यायालय और जिला न्यायालय" description="Patna High Court, Bihar district judiciary and judicial independence की high-level, non-legal-advice guide।" canonicalPath="/governance/judiciary"/><Breadcrumbs items={govCrumbs('न्यायपालिका')}/><GovernanceHero eyebrow="Independent judicial branch" title="बिहार की न्यायपालिका" description="उच्च न्यायालय और district judiciary को Executive department की तरह नहीं, स्वतंत्र judicial institutions की तरह समझें।"/><section className="governance-wrap"><aside className="governance-notice legal"><Gavel/><div><b>सामान्य संस्थागत जानकारी—कानूनी सलाह नहीं</b><p>Case status, jurisdiction, limitation या procedure के लिए संबंधित official court portal और योग्य legal professional से पुष्टि करें। G8 में judge roster या current officeholder names नहीं हैं।</p></div></aside><div className="judiciary-grid">{judiciaryRecords.map(item=><article id={item.id==='district-judiciary'?'district':undefined} key={item.id}><Scale/><small>{item.nameEn}</small><h2>{item.nameHi}</h2><p>{item.mandate}</p><b>{item.jurisdiction}</b>{item.slug!=='district-judiciary'&&<Link to={item.seo.canonical}>विस्तृत profile</Link>}</article>)}</div><ContentSection title="संस्थागत सीमा"><ComparisonGrid ids={['court-department']}/></ContentSection><Sources sources={sourceValues(['constitution','highCourt','eCourts'])}/></section></main>}

export function LocalGovernmentPage(){return <main className="governance-page"><SEO title="बिहार में स्थानीय शासन — ग्रामीण और शहरी संस्थाएँ" description="Panchayati Raj and urban local bodies की separate constitutional and legal branches।" canonicalPath="/governance/local-government"/><Breadcrumbs items={govCrumbs('स्थानीय शासन')}/><GovernanceHero eyebrow="Rural branch ≠ urban branch" title="स्थानीय शासन" description="ग्राम पंचायत और नगर पंचायत नाम में समान हैं, पर वे दो अलग legal और administrative branches में आते हैं।"/><section className="governance-wrap"><div className="local-branch-grid"><article><UsersRound/><small>RURAL</small><h2>पंचायती राज</h2><p>Gram Sabha और तीन-tier elected institutions: Gram Panchayat, Panchayat Samiti, Zila Parishad।</p><Link to="/governance/panchayati-raj">ग्रामीण संरचना</Link></article><article><Building2/><small>URBAN</small><h2>नगर निकाय</h2><p>Nagar Panchayat, Municipal Council/Nagar Parishad और Municipal Corporation; भीतर municipal wards।</p><Link to="/governance/urban-local-bodies">शहरी संरचना</Link></article></div><ContentSection title="स्थानीय और field administration का अंतर"><ComparisonGrid ids={['gp-np','district-zp','gram-sabha-panchayat','block-circle']}/></ContentSection><Sources sources={sourceValues(['constitution','panchayatAct','municipalAct','sec'])}/></section></main>}

export function PanchayatiRajPage(){return <main className="governance-page"><SEO title="बिहार पंचायती राज — Gram Sabha से Zila Parishad तक" description="Gram Sabha, Gram Panchayat, Panchayat Samiti and Zila Parishad की source-aware rural local-government guide।" canonicalPath="/governance/panchayati-raj"/><Breadcrumbs items={govCrumbs('पंचायती राज')}/><GovernanceHero eyebrow="Participation + three elected tiers" title="बिहार में पंचायती राज" description="Gram Sabha को elected Gram Panchayat समझे बिना rural local-government institutions का स्पष्ट ढाँचा।"/><section className="governance-wrap"><div className="panchayat-ladder">{ruralLocalGovernment.map((item,index)=><article key={item.id}><span>{String(index+1).padStart(2,'0')}</span><div><small>{item.nameEn}</small><h2>{item.nameHi}</h2><p>{item.description}</p></div></article>)}</div><p className="governance-boundary">Panchayat totals और elected-officeholder lists बदलते रहते हैं; G8 उन्हें timeless counts की तरह प्रकाशित नहीं करता। Current delimitation/election information State Election Commission से देखें।</p><ContentSection title="संस्थाओं को अलग रखें"><ComparisonGrid ids={['gram-sabha-panchayat','village-panchayat','gp-np','district-zp']}/></ContentSection><ContentSection title="जुड़े offices"><OfficeCards ids={['mukhiya','block-development-officer']}/></ContentSection><Sources sources={sourceValues(['constitution','panchayatAct','panchayat','sec'])}/></section></main>}

export function UrbanLocalBodiesPage(){return <main className="governance-page"><SEO title="बिहार के नगर निकाय — नगर पंचायत, परिषद और निगम" description="Bihar Nagar Panchayat, Municipal Council, Municipal Corporation and municipal ward की institutional guide।" canonicalPath="/governance/urban-local-bodies"/><Breadcrumbs items={govCrumbs('नगर निकाय')}/><GovernanceHero eyebrow="Municipal status can change" title="शहरी स्थानीय निकाय" description="तीन urban-body types और ward structure—बिना stale ULB counts या बदलते classification thresholds को स्थायी तथ्य बनाए।"/><section className="governance-wrap"><div className="urban-body-grid">{urbanLocalGovernment.map(item=><article key={item.id}><Building2/><small>{item.nameEn}</small><h2>{item.nameHi}</h2><p>{item.description}</p><b>{item.legalContext}</b><Link to={item.seo.canonical}>संस्था profile</Link></article>)}</div><aside className="governance-notice"><ShieldCheck/><div><b>ULB count और classification समय-संवेदी हैं</b><p>नए notifications, boundary changes और upgrades के कारण exact list official Urban Development portal और State Election Commission से सत्यापित करें।</p></div></aside><ContentSection title="Rural–urban सीमा"><ComparisonGrid ids={['gp-np','constituency-district']}/></ContentSection><ContentSection title="नगर निगम का leadership office"><OfficeCards ids={['mayor']}/></ContentSection><Sources sources={sourceValues(['constitution','municipalAct','urban','sec'])}/></section></main>}

export function DistrictAdministrationPage(){return <main className="governance-page"><SEO title="बिहार जिला प्रशासन — DM, SDO, BDO, Circle और SP" description="District field administration offices and their distinction from elected local government।" canonicalPath="/governance/district-administration"/><Breadcrumbs items={govCrumbs('जिला प्रशासन')}/><GovernanceHero eyebrow="District machinery ≠ elected Zila Parishad" title="जिला और field administration" description="Coordination, development, revenue और police offices की high-level roles—case-specific powers का substitute नहीं।"/><section className="governance-wrap"><OfficeCards ids={['district-magistrate','sub-divisional-officer','block-development-officer','circle-officer','superintendent-of-police']}/><ContentSection title="प्रखंड और अंचल क्यों अलग हैं"><ComparisonGrid ids={['block-circle','district-zp','district-headquarters']}/></ContentSection><ContentSection title="सभी जिलों के canonical profiles"><div className="all-district-links">{divisions.map(div=><section key={div.id}><h3>{div.nameHi}</h3>{div.districtIds.map(id=>{const d=districts.find(x=>x.slug===id);return <Link key={id} to={`/district/${id}`}>{d?.nameHindi||id}</Link>})}</section>)}</div></ContentSection><Sources sources={sourceValues(['administration','gad','revenue','panchayat'])}/></section></main>}

export function PublicServicesPage(){return <main className="governance-page"><SEO title="बिहार लोक सेवाएँ — RTPS, grievance, RTI और land services" description="Official Bihar public-service channels with verification dates and safe boundaries।" canonicalPath="/governance/public-services"/><Breadcrumbs items={govCrumbs('लोक सेवाएँ')}/><GovernanceHero eyebrow="Official links · verified 13 September 2026" title="लोक सेवाएँ और नागरिक channels" description="यह directory official entry points देती है; बदलते forms, fees, eligibility या processing time को duplicate नहीं करती।"/><section className="governance-wrap"><div className="service-grid">{publicServices.map(item=><a key={item.id} href={item.officialUrl} target="_blank" rel="noreferrer"><FileCheck2/><small>{item.category.replaceAll('-',' ')}</small><h2>{item.nameHi}</h2><p>{item.summary}</p><span>Official portal · सत्यापित {item.lastVerified} <ExternalLink/></span></a>)}</div><aside className="governance-notice legal"><ShieldCheck/><div><b>Service guidance boundary</b><p>Portal availability, documents, fees, timelines और eligibility बदल सकते हैं। Submission से पहले official page पढ़ें; कोई outcome guarantee या legal/property advice यहाँ नहीं दी जाती।</p></div></aside><ContentSection title="संबंधित public institutions"><InstitutionCards/></ContentSection><Sources sources={sourceValues(['rtps','grievance','information','revenue','bpsc','sec','humanRights','lokayukta'])}/></section></main>}

export function GovernanceDetailPage({item}){const sourceSet=item.sources||item.legalSources||[];const details=[['Institution type',item.institutionType],['Administrative type',item.levelType],['Level',scopeLabel[item.level]||item.level],['Branch',item.branch],['Jurisdiction',item.jurisdiction],['Legal context',item.legalContext],['Selection / appointment',item.appointmentOrElectionContext]].filter(([,value])=>value);const text=item.description||item.mandate;return <main className="governance-page"><SEO title={item.seo.title} description={item.seo.description} canonicalPath={item.seo.canonical} type="article"/><Breadcrumbs items={govCrumbs(item.nameHi)}/><GovernanceHero eyebrow={item.nameEn} title={item.nameHi} description={text}/><section className="governance-wrap"><CurrentDataNotice/>{['governor','chief-minister'].includes(item.id)&&<CurrentOfficeholder officeId={item.id}/>} {details.length>0&&<dl className="governance-facts">{details.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{item.principalAdministrativeRole&&<ContentSection title="मुख्य प्रशासनिक भूमिका"><p>{item.principalAdministrativeRole}</p></ContentSection>}{item.coreFunctions?.length>0&&<ContentSection title="स्थायी functions"><ul className="governance-function-list">{item.coreFunctions.map(value=><li key={value}>{value}</li>)}</ul></ContentSection>}<p className="governance-boundary">यह institutional explainer है—current officeholder directory, election result, legal opinion या case-specific service instruction नहीं।</p><CrossModuleLinks/><Sources sources={sourceSet}/></section></main>}
